import AppKit
import XCTest
@testable import ExpanderEngine

final class SecretClipboardWriteFailureTests: XCTestCase {
    private final class Writer: SecretPasteboardWriting {
        enum Failure { case none, string, concealed, transient, generated }

        let failure: Failure
        private(set) var clearCount = 0
        private(set) var stringWrites = 0
        private(set) var dataWrites: [NSPasteboard.PasteboardType] = []
        private(set) var changeCount = 0
        private(set) var currentString: String?
        var externalCopyDuringGeneratedMarker: String?

        init(failure: Failure) { self.failure = failure }

        @discardableResult
        func clearContents() -> Int {
            clearCount += 1
            changeCount += 1
            currentString = nil
            return changeCount
        }

        func setString(_ string: String, forType dataType: NSPasteboard.PasteboardType) -> Bool {
            stringWrites += 1
            guard failure != .string else { return false }
            currentString = string
            return true
        }

        func setData(_ data: Data?, forType dataType: NSPasteboard.PasteboardType) -> Bool {
            dataWrites.append(dataType)
            let shouldFail = (failure == .concealed && dataType == PasteboardBroker.concealedType)
                || (failure == .transient && dataType == PasteboardBroker.transientType)
                || (failure == .generated && dataType == PasteboardBroker.autoGeneratedType)
            guard !shouldFail else { return false }
            if dataType == PasteboardBroker.autoGeneratedType,
               let externalCopyDuringGeneratedMarker {
                simulateExternalCopy(externalCopyDuringGeneratedMarker)
            }
            return true
        }

        func simulateExternalCopy(_ string: String) {
            changeCount += 1
            currentString = string
        }
    }

    func testStringWriteFailureReturnsTypedFailureAndSchedulesNothing() {
        let clipboard = SecretClipboard()
        let writer = Writer(failure: .string)
        var scheduled = 0

        let result = clipboard.copyResult(
            "secret",
            pasteboardWriter: writer,
            schedule: { _, _ in scheduled += 1 }
        )

        XCTAssertEqual(result, .writeFailed)
        XCTAssertEqual(scheduled, 0)
        XCTAssertFalse(clipboard.hasOutstandingSecret)
    }

    func testAnyMissingConcealmentMarkerFailsClosedAndRemovesOurPayload() {
        for failure in [Writer.Failure.concealed, .transient, .generated] {
            let clipboard = SecretClipboard()
            let writer = Writer(failure: failure)
            var scheduled = 0

            let result = clipboard.copyResult(
                "secret",
                pasteboardWriter: writer,
                schedule: { _, _ in scheduled += 1 }
            )

            XCTAssertEqual(result, .writeFailed)
            XCTAssertEqual(writer.clearCount, 2, "The initial clear and failure cleanup must both run")
            XCTAssertEqual(scheduled, 0)
            XCTAssertFalse(clipboard.hasOutstandingSecret)
        }
    }

    func testSuccessfulWriteReportsDeadlineAndSchedulesExactlyOnce() {
        let clipboard = SecretClipboard()
        let writer = Writer(failure: .none)
        var scheduled = 0

        let result = clipboard.copyResult(
            "secret",
            clearAfter: 20,
            pasteboardWriter: writer,
            schedule: { _, delay in
                scheduled += 1
                XCTAssertEqual(delay, 20)
            }
        )

        guard case .copied(let clearAt) = result else {
            return XCTFail("expected copied, got \(result)")
        }
        XCTAssertGreaterThan(clearAt, Date())
        XCTAssertEqual(scheduled, 1)
        XCTAssertTrue(clipboard.hasOutstandingSecret)
    }

    func testSupersededScheduledClearCannotEraseNewerOwnership() {
        let clipboard = SecretClipboard()
        let writer = Writer(failure: .none)
        var scheduled: [() -> Void] = []

        XCTAssertTrue(clipboard.copyResult(
            "first secret",
            pasteboardWriter: writer,
            schedule: { action, _ in scheduled.append(action) }
        ).didCopy)
        XCTAssertTrue(clipboard.copyResult(
            "newer secret",
            pasteboardWriter: writer,
            schedule: { action, _ in scheduled.append(action) }
        ).didCopy)
        XCTAssertEqual(scheduled.count, 2)

        scheduled[0]()
        XCTAssertTrue(
            clipboard.hasOutstandingSecret,
            "An old timer must not clear the ownership ticket installed by a newer copy."
        )
        XCTAssertEqual(
            writer.clearCount,
            2,
            "The stale timer must not touch the newer pasteboard payload."
        )
        XCTAssertEqual(writer.currentString, "newer secret")

        scheduled[1]()
        XCTAssertFalse(clipboard.hasOutstandingSecret)
        XCTAssertEqual(writer.clearCount, 3)
        XCTAssertNil(writer.currentString)
    }

    func testExternalOwnershipTakenDuringWriteIsNeverAdoptedOrCleared() {
        let clipboard = SecretClipboard()
        let writer = Writer(failure: .none)
        writer.externalCopyDuringGeneratedMarker = "external owner"
        var scheduled = 0

        XCTAssertEqual(
            clipboard.copyResult(
                "secret",
                pasteboardWriter: writer,
                schedule: { _, _ in scheduled += 1 }
            ),
            .writeFailed
        )
        XCTAssertEqual(scheduled, 0)
        XCTAssertFalse(clipboard.hasOutstandingSecret)
        XCTAssertEqual(writer.clearCount, 1)
        XCTAssertEqual(writer.currentString, "external owner")
    }

    func testEmptyInputIsDistinctAndLeavesWriterUntouched() {
        let clipboard = SecretClipboard()
        let writer = Writer(failure: .none)

        XCTAssertEqual(clipboard.copyResult("", pasteboardWriter: writer), .empty)
        XCTAssertEqual(writer.clearCount, 0)
        XCTAssertFalse(clipboard.hasOutstandingSecret)
    }
}
