import AppKit
import ApplicationServices
import CoreGraphics
import Foundation

/// §8.1 / §1.7: the whole clipboard snapshot → paste → restore invariant, in one place.
///
/// The invariant this type exists to protect: **the user's clipboard must survive an expansion.**
/// That is harder than it looks, because the payload has to stay on the pasteboard long enough for
/// the target app to read it, which means restore is always deferred, which means two expansions
/// can overlap. Before §1.7 the second expansion snapshotted the *first* expansion's payload as
/// "the user's clipboard" and later restored it — so a back-to-back expand could leave a previous
/// snippet, including the concealed secure-clipboard password payload, on the clipboard forever.
///
/// Ownership is therefore explicit: a `ClipboardTicket` records what we replaced and the
/// generation token that decides whether our restore is still the current one, and a new expansion
/// *inherits* the pending ticket's contents when it finds its own payload still on the board.
public final class PasteboardBroker {
    public static let shared = PasteboardBroker()

    // MARK: - Types

    /// Outcome of clipboard paste after optional AX verification + Cmd+V retry.
    public enum PasteDeliveryResult: Equatable {
        /// Cmd+V could not be posted (Post Events denied / CGEvent create failed).
        case notPosted
        /// AX confirmed the expected text landed.
        case delivered
        /// AX can read the field and the expected text is still missing after retries.
        case failed
        /// Cmd+V was posted but AX cannot confirm (normal for Chrome / Electron / many terminals).
        case unavailable
    }

    /// Pure policy for the post-Cmd+V clipboard-hold loop (unit-tested without AppKit paste).
    public enum PasteHoldDecision: Equatable {
        case succeed
        case failConfirmed
        case retryPaste
        case waitMore
        case giveUpUnverified
    }

    public typealias PasteboardSnapshot = [[NSPasteboard.PasteboardType: Data]]

    /// nspasteboard.org markers: tell clipboard managers not to record our payload.
    public static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    public static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    public static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// §1.7: `oldItems` used to eagerly materialise **every** representation of **every** item on
    /// the main thread. A 20-image clipboard is tens of megabytes of copying on the keystroke path,
    /// and a lazily-provided item (a file promise, a Photos drag) is either paid for in full or
    /// silently lost. Bounded instead, with the tradeoff stated explicitly: we restore the first
    /// `snapshotMaxItems` items up to `snapshotMaxBytes`, and we do **not** attempt to preserve
    /// promised-file representations at all — forcing a promise here can block main indefinitely.
    /// Anything skipped is logged, so a user who loses a promise sees why.
    public static let snapshotMaxItems = 8
    public static let snapshotMaxBytes = 4 * 1024 * 1024
    public static let snapshotSkippedTypes: Set<String> = [
        "com.apple.pasteboard.promised-file-content-type",
        "com.apple.pasteboard.promised-file-url",
        "com.apple.pasteboard.promised-suggested-file-name",
        "com.apple.pasteboard.PasteboardName",
        "NSPromiseContentsPboardType"
    ]

    /// One expansion's ownership of the pasteboard.
    private struct ClipboardTicket {
        let pasteboard: NSPasteboard
        let oldItems: PasteboardSnapshot?
        let generation: UInt64
        /// The `changeCount` we produced. Anything else means someone else wrote the board.
        var targetChangeCount: Int
    }

    // MARK: - State

    private let hid: HIDKeyPoster
    private let verifier: DeliveryVerifier
    private let timing: InjectTimingStore

    /// §2.4: `os_unfair_lock` rather than `NSLock` — taken from the inject path.
    private let restoreLock = UnfairLock()
    private var restoreGeneration: UInt64 = 0
    private var pendingTicket: ClipboardTicket?

    public init(
        hid: HIDKeyPoster = HIDKeyPoster.shared,
        verifier: DeliveryVerifier = DeliveryVerifier.shared,
        timing: InjectTimingStore = InjectTimingStore.shared
    ) {
        self.hid = hid
        self.verifier = verifier
        self.timing = timing
    }

    // MARK: - Generation tokens

    /// Next restore generation token. Pure helper for tests; production uses `beginRestoreGeneration()`.
    public static func nextRestoreGeneration(current: UInt64) -> UInt64 {
        current &+ 1
    }

    @discardableResult
    public func beginRestoreGeneration() -> UInt64 {
        restoreLock.lock()
        restoreGeneration = PasteboardBroker.nextRestoreGeneration(current: restoreGeneration)
        let token = restoreGeneration
        restoreLock.unlock()
        return token
    }

    public func currentRestoreGeneration() -> UInt64 {
        restoreLock.lock()
        defer { restoreLock.unlock() }
        return restoreGeneration
    }

    // MARK: - Delays

    /// Blind size-only restore delay — the pre-§3.4 behaviour, kept for callers (and tests) that
    /// ask for the delay without an app to adapt to.
    public func calculateRestoreDelay(payloadBytes: Int) -> TimeInterval {
        InjectTimingStore.blindRestoreDelay(payloadBytes: payloadBytes)
    }

    /// §3.4: adaptive when we have measured this app, identical to `calculateRestoreDelay` when not.
    public func restoreDelay(bundleID: String?, payloadBytes: Int) -> TimeInterval {
        timing.restoreDelay(bundleID: bundleID, payloadBytes: payloadBytes)
    }

    public func calculateImageRestoreDelay(payloadBytes: Int) -> TimeInterval {
        InjectTimingStore.imageRestoreDelay(payloadBytes: payloadBytes)
    }

    // MARK: - Hold policy

    /// Decide the next step of the clipboard-hold loop. `pasteAttemptsCompleted` counts Cmd+V posts so far.
    /// Consecutive `.failed` observations required before a retry is allowed.
    ///
    /// `DeliveryVerifier` reports `.failed` when the AXValue is *readable* and does not contain
    /// the expected text. On hosts that return a readable-but-stale value straight after a paste
    /// (WebKit, Electron), that is a false negative — and acting on it posts a second Cmd+V,
    /// duplicating text the user already has. One re-read costs a settle delay; a wrong retry
    /// corrupts the document.
    public static let requiredFailureConfirmations = 2

    public static func decidePasteHold(
        delivery: DeliveryVerifier.TextDeliveryVerification,
        pasteAttemptsCompleted: Int,
        maxAttempts: Int = InjectTiming.pasteDeliveryMaxAttempts,
        elapsed: TimeInterval,
        holdTimeout: TimeInterval = InjectTiming.pasteDeliveryHoldTimeout,
        /// How many times in a row `delivery` has been `.failed`, including this observation.
        /// Defaults to "already confirmed" so callers that do not track it keep the old
        /// behaviour; the live hold loop passes the real count.
        consecutiveFailures: Int = .max,
        /// False when this app's AX cannot be believed about delivery (Electron / Chromium
        /// virtualised views). Their AXValue is readable and never contains the pasted text, so
        /// `.failed` is permanent and re-pasting duplicates the expansion every single time.
        /// Such a paste is reported unverified and left alone rather than repeated.
        trustFailureVerdict: Bool = true
    ) -> PasteHoldDecision {
        switch delivery {
        case .delivered:
            return .succeed
        case .failed where !trustFailureVerdict:
            return elapsed < holdTimeout ? .waitMore : .giveUpUnverified
        case .failed:
            // A single `.failed` is not proof. Re-read before re-pasting, provided there is
            // still time — a duplicate paste is worse than an unverified one.
            if consecutiveFailures < requiredFailureConfirmations, elapsed < holdTimeout {
                return .waitMore
            }
            if pasteAttemptsCompleted < maxAttempts {
                return .retryPaste
            }
            return .failConfirmed
        case .unavailable:
            if elapsed < holdTimeout {
                return .waitMore
            }
            return .giveUpUnverified
        }
    }

    public static func label(for result: PasteDeliveryResult) -> String {
        switch result {
        case .notPosted: return "notPosted"
        case .delivered: return "delivered"
        case .failed: return "failed"
        case .unavailable: return "unavailable"
        }
    }

    // MARK: - User clipboard write

    /// Writes a string the user intends to keep (e.g. Preview → Copy).
    ///
    /// Invalidates any in-flight expansion restore so a later restore cannot clobber
    /// the copied text, and so `changeCount` tracking stays coherent with ownership.
    public func writeUserClipboardString(_ string: String) {
        _ = beginRestoreGeneration()
        restoreLock.lock()
        pendingTicket = nil
        restoreLock.unlock()
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(string, forType: .string)
    }

    // MARK: - Text paste

    public func pasteViaClipboard(text: String, completion: ((Bool) -> Void)? = nil) {
        pasteViaClipboard(text: text, expectedText: nil, baseline: nil) { result in
            completion?(result != .notPosted)
        }
    }

    /// Clipboard paste that holds our payload until AX confirms delivery, a confirmed miss exhausts
    /// retries, or the hold timeout expires (unverified). Restores the prior pasteboard afterward.
    ///
    /// - Parameters:
    ///   - bundleID: frontmost app, used only for §3.4 timing adaptation. Captured by the caller at
    ///     paste time rather than read here, so an app switch mid-paste cannot mislabel the sample.
    ///   - leaveClipboardOnFailure: When true, skip immediate restore on `.notPosted` / `.failed` so the
    ///     concealed payload remains for a manual ⌘V (secure clipboard paste under Secure Input).
    ///   - holdTimeoutOverride: Optional longer hold (e.g. secure clipboard paste under SI).
    ///   - completeBeforeRestore: When true and no `expectedText`, report `.unavailable` right after
    ///     Cmd+V so callers are not blocked for the full hold window.
    public func pasteViaClipboard(
        text: String,
        expectedText: String?,
        baseline: DeliveryVerifier.FocusedTextObservation?,
        bundleID: String? = nil,
        leaveClipboardOnFailure: Bool = false,
        holdTimeoutOverride: TimeInterval? = nil,
        completeBeforeRestore: Bool = false,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        // Re-check Post Events at paste time.
        guard CGPreflightPostEventAccess() else {
            DevTypeLog.inject.error("[Inject] paste refused — Post Events denied at paste time")
            completion(.notPosted)
            return
        }

        let pasteboard = NSPasteboard.general
        let oldItems = acquireUserClipboardSnapshot(pasteboard: pasteboard)
        let generation = beginRestoreGeneration()

        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        pasteboard.setData(Data(), forType: PasteboardBroker.transientType)
        pasteboard.setData(Data(), forType: PasteboardBroker.concealedType)
        pasteboard.setData(Data(), forType: PasteboardBroker.autoGeneratedType)

        let ticket = ClipboardTicket(
            pasteboard: pasteboard,
            oldItems: oldItems,
            generation: generation,
            targetChangeCount: pasteboard.changeCount
        )
        registerPendingTicket(ticket)

        let restoreDelayValue = holdTimeoutOverride
            ?? restoreDelay(bundleID: bundleID, payloadBytes: text.utf8.count)
        let holdTimeoutValue = holdTimeoutOverride
            ?? max(timing.holdTimeout(bundleID: bundleID), restoreDelayValue)

        DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.prePasteSettleDelay) {
            self.hid.postCmdVKeyEventsAsync { posted in
                guard posted else {
                    // §8.1: one restore scheduler for all three former copies of this if/else.
                    self.finishOwnership(
                        ticket,
                        deferBy: leaveClipboardOnFailure ? restoreDelayValue : nil
                    )
                    completion(.notPosted)
                    return
                }

                guard let expectedText, !expectedText.isEmpty else {
                    if completeBeforeRestore {
                        completion(.unavailable)
                        self.finishOwnership(ticket, deferBy: restoreDelayValue)
                    } else {
                        DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelayValue) {
                            self.finishOwnership(ticket, deferBy: nil)
                            completion(.unavailable)
                        }
                    }
                    return
                }

                self.runPasteHoldLoop(
                    expectedText: expectedText,
                    baseline: baseline,
                    bundleID: bundleID,
                    pasteAttemptsCompleted: 1,
                    holdStarted: Date(),
                    holdTimeout: holdTimeoutValue,
                    ticket: ticket,
                    leaveClipboardOnFailure: leaveClipboardOnFailure,
                    completion: completion
                )
            }
        }
    }

    private func runPasteHoldLoop(
        expectedText: String,
        baseline: DeliveryVerifier.FocusedTextObservation?,
        bundleID: String?,
        pasteAttemptsCompleted: Int,
        holdStarted: Date,
        holdTimeout: TimeInterval,
        ticket: ClipboardTicket,
        leaveClipboardOnFailure: Bool,
        consecutiveFailures: Int = 0,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.pasteDeliverySettleDelay) {
            let delivery = self.verifier.verifyFocusedTextDelivery(
                expectedText: expectedText,
                baseline: baseline
            )
            let elapsed = Date().timeIntervalSince(holdStarted)
            // Reset on any non-failure so only an uninterrupted run of failures counts as proof.
            let failures = (delivery == .failed) ? consecutiveFailures + 1 : 0
            // An app already condemned as AX-false-success cannot testify that a paste missed.
            let trustFailure = AXWriteCapabilityStore.shared.canConfirmDelivery(bundleID: bundleID)
            // Logged once per hold — the loop re-reads every `pasteDeliverySettleDelay`, and a
            // line per tick would bury the decision it is meant to explain.
            if delivery == .failed, !trustFailure, failures == 1 {
                DevTypeLog.inject.notice(
                    """
                    [Inject] paste hold: AX says missing but \(bundleID ?? "(unknown)", privacy: .public) \
                    cannot confirm delivery — not re-pasting (would duplicate)
                    """
                )
                InjectTelemetryLog.shared.recordSuppressedMissVerdict(bundleID: bundleID)
            }
            let decision = PasteboardBroker.decidePasteHold(
                delivery: delivery,
                pasteAttemptsCompleted: pasteAttemptsCompleted,
                elapsed: elapsed,
                holdTimeout: holdTimeout,
                consecutiveFailures: failures,
                trustFailureVerdict: trustFailure
            )

            switch decision {
            case .succeed:
                // §3.4: this is the one moment the system actually *measures* how long this app
                // takes to consume a paste. Everything else in `InjectTiming` is a guess.
                self.timing.recordDeliveryLatency(elapsed, bundleID: bundleID)
                self.finishOwnership(ticket, deferBy: nil)
                completion(.delivered)

            case .failConfirmed:
                DevTypeLog.inject.error(
                    """
                    [Inject] paste hold: AX readable but expected text missing after \
                    \(pasteAttemptsCompleted, privacy: .public) Cmd+V attempt(s) — \
                    app=\(bundleID ?? "(unknown)", privacy: .public) \
                    elapsed=\(Int(elapsed * 1000), privacy: .public)ms
                    """
                )
                self.finishOwnership(
                    ticket,
                    deferBy: leaveClipboardOnFailure ? holdTimeout : nil
                )
                completion(.failed)

            case .giveUpUnverified:
                self.finishOwnership(ticket, deferBy: nil)
                completion(.unavailable)

            case .retryPaste:
                // The one action in this file that can duplicate the user's text if the verdict
                // driving it is wrong, so it says exactly what convinced it.
                DevTypeLog.inject.notice(
                    """
                    [Inject] paste hold: retrying Cmd+V (attempt \(pasteAttemptsCompleted + 1, privacy: .public)) — \
                    app=\(bundleID ?? "(unknown)", privacy: .public) \
                    consecutiveMisses=\(failures, privacy: .public) \
                    elapsed=\(Int(elapsed * 1000), privacy: .public)ms
                    """
                )
                InjectTelemetryLog.shared.recordPasteRetry(bundleID: bundleID)
                self.hid.postCmdVKeyEventsAsync { posted in
                    guard posted else {
                        self.finishOwnership(
                            ticket,
                            deferBy: leaveClipboardOnFailure ? holdTimeout : nil
                        )
                        completion(.failed)
                        return
                    }
                    self.runPasteHoldLoop(
                        expectedText: expectedText,
                        baseline: baseline,
                        bundleID: bundleID,
                        pasteAttemptsCompleted: pasteAttemptsCompleted + 1,
                        holdStarted: holdStarted,
                        holdTimeout: holdTimeout,
                        ticket: ticket,
                        leaveClipboardOnFailure: leaveClipboardOnFailure,
                        consecutiveFailures: 0,
                        completion: completion
                    )
                }

            case .waitMore:
                self.runPasteHoldLoop(
                    expectedText: expectedText,
                    baseline: baseline,
                    bundleID: bundleID,
                    pasteAttemptsCompleted: pasteAttemptsCompleted,
                    holdStarted: holdStarted,
                    holdTimeout: holdTimeout,
                    ticket: ticket,
                    leaveClipboardOnFailure: leaveClipboardOnFailure,
                    consecutiveFailures: failures,
                    completion: completion
                )
            }
        }
    }

    // MARK: - Image paste

    /// Clipboard-pastes an image (TIFF + PNG reps) with the same snapshot/restore
    /// discipline as `pasteViaClipboard`. Used by image snippets only.
    ///
    /// §3.4: two fixes here. The restore delay no longer runs image bytes through the *text*
    /// formula (a 1 MB image computed 25 s and clamped to 0.45 s, i.e. the number was noise), and
    /// the paste is no longer fire-and-forget — the payload is held while AX is polled for
    /// evidence the field changed, exactly like the text hold loop.
    ///
    /// Deliberately **no** automatic re-paste: unlike text there is no expected string to look for,
    /// and several hosts (Slack, Mail) attach an image without changing the focused element's
    /// `AXValue` at all. Re-pasting on that evidence would insert the image twice, which is worse
    /// than reporting `postedUnverified`. Verification here is reporting-only.
    public func pasteImageViaClipboard(
        image: NSImage,
        bundleID: String? = nil,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        guard CGPreflightPostEventAccess() else {
            DevTypeLog.inject.error("[Inject] image paste refused — Post Events denied at paste time")
            completion(.notPosted)
            return
        }

        let pasteboard = NSPasteboard.general
        let oldItems = acquireUserClipboardSnapshot(pasteboard: pasteboard)
        let generation = beginRestoreGeneration()

        pasteboard.clearContents()
        var wrote = false
        if let tiff = image.tiffRepresentation {
            pasteboard.setData(tiff, forType: .tiff)
            wrote = true
        }
        if let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil) {
            let rep = NSBitmapImageRep(cgImage: cgImage)
            if let png = rep.representation(using: .png, properties: [:]) {
                pasteboard.setData(png, forType: .png)
                wrote = true
            }
        }
        guard wrote else {
            // Nothing of ours is on the board beyond the clear; put the user's clipboard back.
            let emptyTicket = ClipboardTicket(
                pasteboard: pasteboard,
                oldItems: oldItems,
                generation: generation,
                targetChangeCount: pasteboard.changeCount
            )
            registerPendingTicket(emptyTicket)
            finishOwnership(emptyTicket, deferBy: nil)
            completion(.notPosted)
            return
        }
        pasteboard.setData(Data(), forType: PasteboardBroker.transientType)
        pasteboard.setData(Data(), forType: PasteboardBroker.concealedType)
        pasteboard.setData(Data(), forType: PasteboardBroker.autoGeneratedType)

        let ticket = ClipboardTicket(
            pasteboard: pasteboard,
            oldItems: oldItems,
            generation: generation,
            targetChangeCount: pasteboard.changeCount
        )
        registerPendingTicket(ticket)

        let payloadBytes = (pasteboard.data(forType: .tiff)?.count ?? 0)
            + (pasteboard.data(forType: .png)?.count ?? 0)
        let restoreDelayValue = calculateImageRestoreDelay(payloadBytes: payloadBytes)
        let holdTimeoutValue = max(restoreDelayValue, InjectTiming.imageDeliveryHoldTimeout)

        DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.prePasteSettleDelay) {
            let baseline = self.verifier.captureFocusedTextObservation()
            self.hid.postCmdVKeyEventsAsync { posted in
                guard posted else {
                    self.finishOwnership(ticket, deferBy: nil)
                    completion(.notPosted)
                    return
                }
                self.runImageHoldLoop(
                    baseline: baseline,
                    bundleID: bundleID,
                    holdStarted: Date(),
                    holdTimeout: holdTimeoutValue,
                    ticket: ticket,
                    completion: completion
                )
            }
        }
    }

    private func runImageHoldLoop(
        baseline: DeliveryVerifier.FocusedTextObservation?,
        bundleID: String?,
        holdStarted: Date,
        holdTimeout: TimeInterval,
        ticket: ClipboardTicket,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.pasteDeliverySettleDelay) {
            let elapsed = Date().timeIntervalSince(holdStarted)
            if self.focusedFieldChanged(since: baseline) {
                self.timing.recordDeliveryLatency(elapsed, bundleID: bundleID)
                self.finishOwnership(ticket, deferBy: nil)
                completion(.delivered)
                return
            }
            guard elapsed >= holdTimeout else {
                self.runImageHoldLoop(
                    baseline: baseline,
                    bundleID: bundleID,
                    holdStarted: holdStarted,
                    holdTimeout: holdTimeout,
                    ticket: ticket,
                    completion: completion
                )
                return
            }
            // Held long enough. AX saw nothing change, which for an image is weak evidence at
            // best — report unverified rather than failed, and never re-paste (see the doc above).
            self.finishOwnership(ticket, deferBy: nil)
            completion(.unavailable)
        }
    }

    /// Best-effort "something landed" probe for the image path. Requires a *readable, non-empty*
    /// baseline so virtualised hosts that always report an empty AXValue cannot produce a verdict.
    private func focusedFieldChanged(since baseline: DeliveryVerifier.FocusedTextObservation?) -> Bool {
        guard let baseline, let baselineValue = baseline.value, !baselineValue.isEmpty else {
            return false
        }
        guard let after = self.verifier.captureFocusedTextObservation(), after.value != nil else {
            return false
        }
        return after.value != baseline.value || after.selectedText != baseline.selectedText
    }

    // MARK: - Ownership

    /// §1.7 step 1: work out what the *user's* clipboard actually is, before we overwrite it.
    ///
    /// If our own payload from a previous, still-pending expansion is on the board, then the user's
    /// real clipboard is whatever that expansion was holding — not what we can read right now.
    /// Snapshotting the board here is exactly the bug: expansion #2 would adopt expansion #1's
    /// snippet as "the user's clipboard" and faithfully restore it later.
    private func acquireUserClipboardSnapshot(pasteboard: NSPasteboard) -> PasteboardSnapshot? {
        restoreLock.lock()
        let pending = pendingTicket
        restoreLock.unlock()

        if let pending, pending.targetChangeCount == pasteboard.changeCount {
            DevTypeLog.inject.notice(
                "[Inject] §1.7 clipboard still holds our previous payload — inheriting the pending restore instead of snapshotting it"
            )
            return pending.oldItems
        }
        if pending != nil {
            // The board moved on: either the user copied something (their content is what we are
            // about to snapshot, correctly) or the previous restore already ran. Either way the
            // stale ticket must not fire later — the generation bump below guarantees that.
            DevTypeLog.inject.debug(
                "[Inject] §1.7 abandoning stale clipboard ticket — pasteboard changed since our last paste"
            )
        }
        return PasteboardBroker.snapshotPasteboard(pasteboard)
    }

    private func registerPendingTicket(_ ticket: ClipboardTicket) {
        restoreLock.lock()
        pendingTicket = ticket
        restoreLock.unlock()
    }

    private func clearPendingTicket(generation: UInt64) {
        restoreLock.lock()
        if pendingTicket?.generation == generation {
            pendingTicket = nil
        }
        restoreLock.unlock()
    }

    /// §8.1: the single restore scheduler. `deferBy` non-nil means "leave the payload up for a
    /// manual ⌘V first" — the three identical `if leaveClipboardOnFailure { asyncAfter … } else
    /// { … }` blocks the broker inherited all collapse into this.
    private func finishOwnership(_ ticket: ClipboardTicket, deferBy delay: TimeInterval?) {
        guard let delay, delay > 0 else {
            restore(ticket)
            return
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
            self.restore(ticket)
        }
    }

    // MARK: - Copy capture (clipboard-fallback selection read)

    /// How long to wait for the target app to answer a synthetic ⌘C with a pasteboard write,
    /// and how often to look. Copies are near-instant in practice; the timeout exists for apps
    /// that write the board from a secondary thread after the key event round-trips.
    public static let copyCaptureTimeout: TimeInterval = 0.30
    public static let copyCapturePollInterval: TimeInterval = 0.02

    /// What a `captureSelectionViaCopy` attempt produced. The label is recorded in the selection
    /// diagnostics — a fallback that ran and found the board untouched is a different bug report
    /// from one that never posted.
    public enum CopyCaptureOutcome: Equatable {
        /// The app answered ⌘C with a string. May still be blank — the *reader* owns blankness.
        case captured(String)
        /// ⌘C was posted and the pasteboard never changed: nothing selected, or the app ignores
        /// the chord. Indistinguishable from outside, and both mean "no selection to use".
        case boardUnchanged
        /// The app wrote the board but with no string representation (an image, a file).
        case noStringOnBoard
        /// The key events could not be posted (Post Events revoked mid-session).
        case postFailed

        public var diagnosticLabel: String {
            switch self {
            case .captured: return "captured"
            case .boardUnchanged: return "unchanged"
            case .noStringOnBoard: return "noString"
            case .postFailed: return "postFailed"
            }
        }
    }

    /// Pure: restore only when the board still shows the copy we observed. Anything else means
    /// another writer got there after our capture, and writing over them would eat *their* data
    /// to clean up after ours.
    public static func shouldRestoreAfterCopyCapture(
        changeCountNow: Int,
        changeCountAfterCopy: Int
    ) -> Bool {
        changeCountNow == changeCountAfterCopy
    }

    /// Last-resort selection read: snapshot the board, post ⌘C, wait briefly for the target app
    /// to write, read the string, put the user's clipboard back.
    ///
    /// This is the one sanctioned synthetic-copy path — `SelectionReader`'s "no unmanaged ⌘C"
    /// rule is about clipboard *ownership*, and this method is the owner: the same snapshot /
    /// changeCount / verified-restore machinery every paste already goes through, including
    /// inheriting a still-pending expansion restore rather than adopting our own payload as
    /// "the user's clipboard".
    ///
    /// Costs up to `copyCaptureTimeout` of calling-thread wait, so it is only for explicit user
    /// gestures, and only after every AX tier has failed. Two limits it cannot remove: a clipboard
    /// manager will see the transient copy (the *target app* writes the board, so nspasteboard.org
    /// markers cannot be attached), and an app that treats ⌘C-with-no-selection as "copy the
    /// current line" will report that line as the selection — which is why the caller only runs
    /// this when AX could not even resolve a focused element, never on a readable-but-empty
    /// selection.
    ///
    /// - Parameter postCopy: the ⌘C itself, injectable so tests can simulate the target app.
    public func captureSelectionViaCopy(
        pasteboard: NSPasteboard = .general,
        timeout: TimeInterval = copyCaptureTimeout,
        pollInterval: TimeInterval = copyCapturePollInterval,
        postCopy: (() -> Bool)? = nil
    ) -> CopyCaptureOutcome {
        let snapshot = acquireUserClipboardSnapshot(pasteboard: pasteboard)
        let baseline = pasteboard.changeCount

        let posted = postCopy.map { $0() } ?? hid.postCmdCKeyEvents()
        guard posted else { return .postFailed }

        let deadline = Date().addingTimeInterval(timeout)
        while pasteboard.changeCount == baseline, Date() < deadline {
            usleep(useconds_t(max(pollInterval, 0.001) * 1_000_000))
        }
        guard pasteboard.changeCount != baseline else {
            // Nothing was written, so nothing needs restoring — the board was never touched.
            return .boardUnchanged
        }

        let afterCopy = pasteboard.changeCount

        // One extra poll interval: apps that declare types first and provide data second bump
        // `changeCount` before the string is actually there.
        usleep(useconds_t(max(pollInterval, 0.001) * 1_000_000))
        let captured = pasteboard.string(forType: .string)

        if Self.shouldRestoreAfterCopyCapture(
            changeCountNow: pasteboard.changeCount,
            changeCountAfterCopy: afterCopy
        ) {
            pasteboard.clearContents()
            if let snapshot, !snapshot.isEmpty {
                let restoredItems: [NSPasteboardItem] = snapshot.map { itemDict in
                    let newItem = NSPasteboardItem()
                    itemDict.forEach { type, data in newItem.setData(data, forType: type) }
                    return newItem
                }
                if !pasteboard.writeObjects(restoredItems) {
                    DevTypeLog.inject.error(
                        "[Inject] copy-capture clipboard restore write failed — the user's clipboard was not restored"
                    )
                }
            }
            // An empty snapshot restores to an empty board: leaving the captured selection up
            // would hand it to every clipboard manager watching the board.
        } else {
            DevTypeLog.inject.notice(
                "[Inject] copy-capture restore abandoned — another owner wrote the pasteboard during capture"
            )
        }

        guard let captured else { return .noStringOnBoard }
        return .captured(captured)
    }

    /// §1.7: bounded pasteboard snapshot. See `snapshotMaxItems` for the tradeoff.
    private static func snapshotPasteboard(_ pasteboard: NSPasteboard) -> PasteboardSnapshot? {
        guard let items = pasteboard.pasteboardItems else { return nil }
        var result: PasteboardSnapshot = []
        var budget = snapshotMaxBytes
        var skipped = 0

        for item in items.prefix(snapshotMaxItems) {
            var dict = [NSPasteboard.PasteboardType: Data]()
            for type in item.types {
                if snapshotSkippedTypes.contains(type.rawValue) {
                    skipped += 1
                    continue
                }
                guard let data = item.data(forType: type) else { continue }
                if data.count > budget {
                    skipped += 1
                    continue
                }
                budget -= data.count
                dict[type] = data
            }
            if !dict.isEmpty {
                result.append(dict)
            }
        }
        if items.count > snapshotMaxItems {
            skipped += items.count - snapshotMaxItems
        }
        if skipped > 0 {
            DevTypeLog.inject.notice(
                "[Inject] §1.7 clipboard snapshot bounded — \(skipped, privacy: .public) representation(s) not preserved (promised files and payloads over \(snapshotMaxBytes, privacy: .public) bytes are skipped)"
            )
        }
        return result
    }

    /// True when the board still carries our nspasteboard.org markers, i.e. the content on it is
    /// still our payload even though `changeCount` moved (some hosts rewrite the board while
    /// handling ⌘V).
    private static func holdsOurPayload(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains(autoGeneratedType)
            || types.contains(concealedType)
            || types.contains(transientType)
    }

    private func restore(_ ticket: ClipboardTicket, attempt: Int = 0) {
        // Generation gate: a newer expand owns the pasteboard — skip stale restore.
        guard currentRestoreGeneration() == ticket.generation else { return }

        let pasteboard = ticket.pasteboard
        if pasteboard.changeCount != ticket.targetChangeCount {
            if PasteboardBroker.holdsOurPayload(pasteboard) {
                // Still our content, just rewritten by the host mid-paste. Safe to restore.
                DevTypeLog.inject.notice(
                    "[Inject] §1.7 clipboard changeCount moved (\(pasteboard.changeCount, privacy: .public) != \(ticket.targetChangeCount, privacy: .public)) but our markers are still present — restoring anyway"
                )
            } else {
                // §1.7: this used to be a silent `return` — the user's clipboard was simply gone
                // with no log, no fallback and no retry. It is still not safe to write here (a
                // real owner would be clobbered), but it is no longer invisible.
                DevTypeLog.inject.notice(
                    "[Inject] §1.7 clipboard restore abandoned — another owner wrote the pasteboard (change \(pasteboard.changeCount, privacy: .public) != \(ticket.targetChangeCount, privacy: .public)); leaving their contents in place"
                )
                clearPendingTicket(generation: ticket.generation)
                return
            }
        }

        pasteboard.clearContents()
        guard let oldItems = ticket.oldItems, !oldItems.isEmpty else {
            clearPendingTicket(generation: ticket.generation)
            return
        }

        let restoredItems: [NSPasteboardItem] = oldItems.map { itemDict in
            let newItem = NSPasteboardItem()
            itemDict.forEach { type, data in
                newItem.setData(data, forType: type)
            }
            return newItem
        }
        let wrote = pasteboard.writeObjects(restoredItems)
        if !wrote {
            if attempt + 1 < InjectTiming.maxPasteboardRestoreAttempts {
                DevTypeLog.inject.notice(
                    "[Inject] §1.7 clipboard restore write failed — retry \(attempt + 1, privacy: .public)"
                )
                // We already cleared the board, so our clear is now the current change count.
                var retryTicket = ticket
                retryTicket.targetChangeCount = pasteboard.changeCount
                DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.pasteboardRestoreRetryDelay) {
                    self.restore(retryTicket, attempt: attempt + 1)
                }
                return
            }
            DevTypeLog.inject.error(
                "[Inject] §1.7 clipboard restore failed after \(InjectTiming.maxPasteboardRestoreAttempts, privacy: .public) attempts — the user's clipboard was not restored"
            )
        }
        clearPendingTicket(generation: ticket.generation)
    }
}
