import AppKit
import ApplicationServices
import CoreGraphics
import Foundation

/// §8.1 / §1.7: the whole clipboard snapshot → paste → restore invariant, in one place.
///
/// The invariant this type exists to protect: **the user's clipboard must survive an expansion.**
/// That is harder than it looks, because the payload has to stay on the pasteboard long enough for
/// the target app to read it, which means restore is always deferred, which means two expansions
/// can overlap. Before §1.7 the second expansion snapshotted the *first* expansion's payload as
/// "the user's clipboard" and later restored it — so a back-to-back expand could leave a previous
/// snippet, including the concealed secure-clipboard password payload, on the clipboard forever.
///
/// Ownership is therefore explicit: a `ClipboardTicket` records what we replaced and the
/// generation token that decides whether our restore is still the current one, and a new expansion
/// *inherits* the pending ticket's contents when it finds its own payload still on the board.
public final class PasteboardBroker {
    public static let shared = PasteboardBroker()

    // MARK: - Types

    /// Outcome of clipboard paste after optional AX verification + Cmd+V retry.
    public enum PasteDeliveryResult: Equatable {
        /// Cmd+V could not be posted (Post Events denied / CGEvent create failed).
        case notPosted
        /// AX confirmed the expected text landed.
        case delivered
        /// AX can read the field and the expected text is still missing after retries.
        case failed
        /// Cmd+V was posted but AX cannot confirm (normal for Chrome / Electron / many terminals).
        case unavailable
    }

    /// Pure policy for the post-Cmd+V clipboard-hold loop (unit-tested without AppKit paste).
    public enum PasteHoldDecision: Equatable {
        case succeed
        case failConfirmed
        case retryPaste
        case waitMore
        case giveUpUnverified
    }

    public typealias PasteboardSnapshot = [[NSPasteboard.PasteboardType: Data]]

    /// Exact result of a deliberate user clipboard write. The public UI contract is the
    /// `didWrite` boolean; the richer internal result keeps tests and diagnostics from collapsing
    /// "write failed but the old board was recovered" into either success or silent data loss.
    enum UserClipboardWriteOutcome: Equatable {
        case written
        case writeFailedPriorRestored
        case writeFailedNoPriorSnapshot
        case writeFailedRestoreFailed
        case ownershipLost

        var didWrite: Bool { self == .written }

        fileprivate var diagnosticLabel: String {
            switch self {
            case .written: return "written"
            case .writeFailedPriorRestored: return "writeFailedPriorRestored"
            case .writeFailedNoPriorSnapshot: return "writeFailedNoPriorSnapshot"
            case .writeFailedRestoreFailed: return "writeFailedRestoreFailed"
            case .ownershipLost: return "ownershipLost"
            }
        }
    }

    enum UserClipboardRestoreOutcome: Equatable {
        case restored
        case ownershipLost
        case failed
    }

    /// Fault-injectable boundary around AppKit's boolean-returning pasteboard writes. Production
    /// supplies closures over `NSPasteboard.general`; tests can force each refusal and ownership
    /// race without touching the user's real clipboard.
    struct UserClipboardWriteOperations {
        let clearContents: () -> Int
        let currentChangeCount: () -> Int
        let setString: (String) -> Bool
        let restoreSnapshot: (PasteboardSnapshot, Int) -> UserClipboardRestoreOutcome
    }

    /// nspasteboard.org markers: tell clipboard managers not to record our payload.
    public static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    public static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    public static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// §1.7: `oldItems` used to eagerly materialise **every** representation of **every** item on
    /// the main thread. A 20-image clipboard is tens of megabytes of copying on the keystroke path,
    /// and a lazily-provided item (a file promise, a Photos drag) is either paid for in full or
    /// silently lost. Bounded instead, with the tradeoff stated explicitly: we restore the first
    /// `snapshotMaxItems` items up to `snapshotMaxBytes`, and we do **not** attempt to preserve
    /// promised-file representations at all — forcing a promise here can block main indefinitely.
    /// Anything skipped is logged, so a user who loses a promise sees why.
    public static let snapshotMaxItems = 8
    public static let snapshotMaxBytes = 4 * 1024 * 1024
    public static let snapshotSkippedTypes: Set<String> = [
        "com.apple.pasteboard.promised-file-content-type",
        "com.apple.pasteboard.promised-file-url",
        "com.apple.pasteboard.promised-suggested-file-name",
        "com.apple.pasteboard.PasteboardName",
        "NSPromiseContentsPboardType"
    ]

    /// One expansion's ownership of the pasteboard.
    private struct ClipboardTicket {
        let pasteboard: NSPasteboard
        let oldItems: PasteboardSnapshot?
        let generation: UInt64
        /// The `changeCount` we produced. Anything else means someone else wrote the board.
        var targetChangeCount: Int
    }

    /// §8.12: everything the release decision needs, captured at the moment ⌘V was posted.
    ///
    /// Residency is a property of the *keystroke*, not of whichever code path happens to finish
    /// first, so the deadline is absolute. The previous `deferBy:` delay was measured from wherever
    /// the caller stood: an outcome reached in 0 ms and one reached in 300 ms both waited the same
    /// extra interval, so the actual time the bytes spent on the board was never a stated number.
    private struct PayloadResidency {
        /// When ⌘V finished posting.
        let postedAt: Date
        /// Minimum time on the board when nothing proves the host read it.
        let unverifiedHold: TimeInterval
        /// Hard cap including stall extensions. Never below `unverifiedHold`.
        let ceiling: TimeInterval
        /// Process the ⌘V was aimed at, for the stall probe. `nil` disables the probe.
        let targetPID: pid_t?
        /// Whether that process was answering AX when we posted. Without a positive baseline a
        /// silent app is just an app that never speaks AX, not a stalled one, and extending on
        /// that would hold every expansion in an AX-dead host to the ceiling.
        let hostRespondedAtPaste: Bool
        let bundleID: String?

        var deadline: Date { postedAt.addingTimeInterval(unverifiedHold) }
        var hardDeadline: Date { postedAt.addingTimeInterval(max(ceiling, unverifiedHold)) }

        /// A retry posts a second ⌘V, which owes its own full residency — the first keystroke
        /// having aged out is not evidence about this one.
        func restarted(at postedAt: Date) -> PayloadResidency {
            PayloadResidency(
                postedAt: postedAt,
                unverifiedHold: unverifiedHold,
                ceiling: ceiling,
                targetPID: targetPID,
                hostRespondedAtPaste: hostRespondedAtPaste,
                bundleID: bundleID
            )
        }
    }

    // MARK: - State

    private let hid: HIDKeyPoster
    private let verifier: DeliveryVerifier
    private let timing: InjectTimingStore

    /// §2.4: `os_unfair_lock` rather than `NSLock` — taken from the inject path.
    private let restoreLock = UnfairLock()
    private var restoreGeneration: UInt64 = 0
    private var pendingTicket: ClipboardTicket?

    public init(
        hid: HIDKeyPoster = HIDKeyPoster.shared,
        verifier: DeliveryVerifier = DeliveryVerifier.shared,
        timing: InjectTimingStore = InjectTimingStore.shared
    ) {
        self.hid = hid
        self.verifier = verifier
        self.timing = timing
    }

    // MARK: - Generation tokens

    /// Next restore generation token. Pure helper for tests; production uses `beginRestoreGeneration()`.
    public static func nextRestoreGeneration(current: UInt64) -> UInt64 {
        current &+ 1
    }

    @discardableResult
    public func beginRestoreGeneration() -> UInt64 {
        restoreLock.lock()
        restoreGeneration = PasteboardBroker.nextRestoreGeneration(current: restoreGeneration)
        let token = restoreGeneration
        restoreLock.unlock()
        return token
    }

    /// Abandon any scheduled restore, because someone else now owns the pasteboard on purpose.
    ///
    /// Any code that deliberately writes the *user's* clipboard must call this first. Without it
    /// a restore scheduled by the previous expansion fires afterwards and puts the old contents
    /// back over the new write — and `holdsOurPayload` makes that worse rather than better,
    /// because a deliberate write that carries our concealed / transient markers (which
    /// `SecretClipboard` sets, correctly, so clipboard managers skip it) reads to `restore` as
    /// "our own payload, safe to overwrite". A secret copied inside the restore window was being
    /// silently replaced by the pre-expansion clipboard, and the window is 8 s under Secure
    /// Input — precisely when secrets are used.
    public func invalidatePendingRestore() {
        _ = beginRestoreGeneration()
        restoreLock.lock()
        pendingTicket = nil
        restoreLock.unlock()
    }

    /// Pure policy: may the contents currently on the board be adopted as "the user's clipboard"
    /// and restored after an expansion?
    ///
    /// Not when they are concealed. A concealed payload is either a secret the user copied or a
    /// leftover of ours; restoring either one later would put a password back on the pasteboard
    /// *after* `SecretClipboard` cleared it, with nothing left to clear it again.
    public static func mayAdoptAsUserClipboard(types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types else { return true }
        return !types.contains(concealedType)
    }

    public func currentRestoreGeneration() -> UInt64 {
        restoreLock.lock()
        defer { restoreLock.unlock() }
        return restoreGeneration
    }

    // MARK: - Delays

    /// Blind size-only restore delay — the pre-§3.4 behaviour, kept for callers (and tests) that
    /// ask for the delay without an app to adapt to.
    public func calculateRestoreDelay(payloadBytes: Int) -> TimeInterval {
        InjectTimingStore.blindRestoreDelay(payloadBytes: payloadBytes)
    }

    /// §3.4: adaptive when we have measured this app, identical to `calculateRestoreDelay` when not.
    public func restoreDelay(bundleID: String?, payloadBytes: Int) -> TimeInterval {
        timing.restoreDelay(bundleID: bundleID, payloadBytes: payloadBytes)
    }

    public func calculateImageRestoreDelay(payloadBytes: Int) -> TimeInterval {
        InjectTimingStore.imageRestoreDelay(payloadBytes: payloadBytes)
    }

    // MARK: - Hold policy

    /// Decide the next step of the clipboard-hold loop. `pasteAttemptsCompleted` counts Cmd+V posts so far.
    /// Consecutive `.failed` observations required before a retry is allowed.
    ///
    /// `DeliveryVerifier` reports `.failed` when the AXValue is *readable* and does not contain
    /// the expected text. On hosts that return a readable-but-stale value straight after a paste
    /// (WebKit, Electron), that is a false negative — and acting on it posts a second Cmd+V,
    /// duplicating text the user already has. One re-read costs a settle delay; a wrong retry
    /// corrupts the document.
    public static let requiredFailureConfirmations = 2

    public static func decidePasteHold(
        delivery: DeliveryVerifier.TextDeliveryVerification,
        pasteAttemptsCompleted: Int,
        maxAttempts: Int = InjectTiming.pasteDeliveryMaxAttempts,
        elapsed: TimeInterval,
        holdTimeout: TimeInterval = InjectTiming.pasteDeliveryHoldTimeout,
        /// How many times in a row `delivery` has been `.failed`, including this observation.
        /// Defaults to "already confirmed" so callers that do not track it keep the old
        /// behaviour; the live hold loop passes the real count.
        consecutiveFailures: Int = .max,
        /// False when this app's AX cannot be believed about delivery (Electron / Chromium
        /// virtualised views). Their AXValue is readable and never contains the pasted text, so
        /// `.failed` is permanent and re-pasting duplicates the expansion every single time.
        /// Such a paste is reported unverified and left alone rather than repeated.
        trustFailureVerdict: Bool = true
    ) -> PasteHoldDecision {
        switch delivery {
        case .delivered:
            return .succeed
        case .failed where !trustFailureVerdict:
            return elapsed < holdTimeout ? .waitMore : .giveUpUnverified
        case .failed:
            // A single `.failed` is not proof. Re-read before re-pasting, provided there is
            // still time — a duplicate paste is worse than an unverified one.
            if consecutiveFailures < requiredFailureConfirmations, elapsed < holdTimeout {
                return .waitMore
            }
            if pasteAttemptsCompleted < maxAttempts {
                return .retryPaste
            }
            return .failConfirmed
        case .unavailable:
            if elapsed < holdTimeout {
                return .waitMore
            }
            return .giveUpUnverified
        }
    }

    // MARK: - Payload residency policy (§8.12)

    /// How much longer our payload must stay on the pasteboard, given how the paste ended.
    ///
    /// The question this answers is **not** "did the text arrive" but "has the host read the
    /// bytes yet" — and only one outcome answers it:
    ///
    /// - `.delivered`: AX found the text in the field, so the host demonstrably read the board.
    ///   Restore immediately; the user gets their clipboard back as fast as ever.
    /// - `.notPosted`: no ⌘V exists, so there is nothing to be consumed. Restore immediately.
    /// - `.unavailable`: ⌘V went out and AX could tell us nothing. This is the Electron/Chromium
    ///   case, the majority of real pastes, and it is *zero* evidence — hold for the full residency.
    /// - `.failed`: AX is readable and the text is absent. That is evidence about the *field*, not
    ///   about the pasteboard: a host that has not yet dequeued the keystroke reads exactly the
    ///   same. Hold.
    ///
    /// Returns 0 rather than a negative interval when the residency has already elapsed — by the
    /// time a slow verification ladder finishes, it usually has.
    public static func remainingPayloadResidency(
        result: PasteDeliveryResult,
        elapsedSincePaste: TimeInterval,
        unverifiedHold: TimeInterval
    ) -> TimeInterval {
        switch result {
        case .delivered, .notPosted:
            return 0
        case .failed, .unavailable:
            return max(0, unverifiedHold - max(0, elapsedSincePaste))
        }
    }

    /// May an unverified paste keep the payload *past* its residency because the target app has
    /// stopped answering AX?
    ///
    /// A frozen host is the failure mode a fixed residency cannot cover: our ⌘V sits in its event
    /// queue for as long as its main thread is busy, and no timer chosen in advance is long enough.
    /// An app that is not servicing AX is not servicing its event queue either, so "still stalled"
    /// is a live reason to believe the keystroke has not been consumed.
    ///
    /// Three conditions, all required, because the cost of a false extension is the user's
    /// clipboard staying wrong:
    /// 1. the host answered AX when we posted — otherwise silence is its normal state and proves
    ///    nothing (a check that could not run must not read as a check that ran);
    /// 2. it is not answering now;
    /// 3. we are still inside the hard ceiling.
    public static func shouldExtendResidencyForStalledHost(
        hostRespondedAtPaste: Bool,
        hostRespondsNow: Bool,
        elapsedSincePaste: TimeInterval,
        ceiling: TimeInterval = InjectTiming.unverifiedPayloadResidencyCeiling
    ) -> Bool {
        guard hostRespondedAtPaste, !hostRespondsNow else { return false }
        return elapsedSincePaste < ceiling
    }

    public static func label(for result: PasteDeliveryResult) -> String {
        switch result {
        case .notPosted: return "notPosted"
        case .delivered: return "delivered"
        case .failed: return "failed"
        case .unavailable: return "unavailable"
        }
    }

    // MARK: - User clipboard write

    /// Writes a string the user intends to keep (e.g. Preview → Copy).
    ///
    /// Invalidates any in-flight expansion restore so a later restore cannot clobber
    /// the copied text, and so `changeCount` tracking stays coherent with ownership.
    @discardableResult
    public func writeUserClipboardString(_ string: String) -> Bool {
        let pasteboard = NSPasteboard.general
        // Snapshot before invalidation: if an expansion payload is still on the board, the
        // pending ticket owns the user's actual pre-expansion clipboard. Invalidating first would
        // throw that only copy away and snapshot our generated payload as though it were theirs.
        let priorSnapshot = acquireUserClipboardSnapshot(pasteboard: pasteboard)
        let outcome = performUserClipboardWrite(
            string,
            priorSnapshot: priorSnapshot,
            operations: UserClipboardWriteOperations(
                clearContents: { pasteboard.clearContents() },
                currentChangeCount: { pasteboard.changeCount },
                setString: { pasteboard.setString($0, forType: .string) },
                restoreSnapshot: { snapshot, ownedChangeCount in
                    Self.restoreUserClipboardSnapshot(
                        snapshot,
                        ownedChangeCount: ownedChangeCount,
                        currentChangeCount: { pasteboard.changeCount },
                        writeObjects: { pasteboard.writeObjects($0) }
                    )
                }
            )
        )
        return outcome.didWrite
    }

    /// One canonical clear → write → conditional recovery transaction.
    ///
    /// Recovery is deliberately immediate and single-attempt: returning `false` must be truthful
    /// now, while retrying later would extend the interval in which another process can claim the
    /// pasteboard. The snapshot itself is capped by `snapshotMaxItems` / `snapshotMaxBytes`.
    @discardableResult
    func performUserClipboardWrite(
        _ string: String,
        priorSnapshot: PasteboardSnapshot?,
        operations: UserClipboardWriteOperations
    ) -> UserClipboardWriteOutcome {
        invalidatePendingRestore()
        let ownedClearChangeCount = operations.clearContents()
        let wrote = operations.setString(string)

        let outcome: UserClipboardWriteOutcome
        if wrote {
            // AppKit normally keeps the clear's `changeCount` while adding representations. A
            // different count means another owner arrived during the operation; never claim that
            // their now-current board contains our string.
            outcome = operations.currentChangeCount() == ownedClearChangeCount
                ? .written
                : .ownershipLost
        } else if operations.currentChangeCount() != ownedClearChangeCount {
            // Another writer already owns the board. Restoring here would destroy their copy.
            outcome = .ownershipLost
        } else if let priorSnapshot, !priorSnapshot.isEmpty {
            switch operations.restoreSnapshot(priorSnapshot, ownedClearChangeCount) {
            case .restored:
                outcome = .writeFailedPriorRestored
            case .ownershipLost:
                outcome = .ownershipLost
            case .failed:
                outcome = .writeFailedRestoreFailed
            }
        } else {
            // The old board was empty or intentionally unadoptable (for example a concealed
            // secret whose expiry ownership must not be broken by resurrecting it).
            outcome = .writeFailedNoPriorSnapshot
        }

        let characterCount = string.count
        let snapshotItemCount = priorSnapshot?.count ?? 0
        if outcome.didWrite {
            DevTypeLog.inject.info(
                "[Clipboard] user write outcome=written chars=\(characterCount, privacy: .public)"
            )
        } else {
            DevTypeLog.inject.error(
                "[Clipboard] user write outcome=\(outcome.diagnosticLabel, privacy: .public) chars=\(characterCount, privacy: .public) boundedSnapshotItems=\(snapshotItemCount, privacy: .public)"
            )
        }
        return outcome
    }

    // MARK: - Text paste

    public func pasteViaClipboard(text: String, completion: ((Bool) -> Void)? = nil) {
        pasteViaClipboard(text: text, expectedText: nil, baseline: nil) { result in
            completion?(result != .notPosted)
        }
    }

    /// Clipboard paste that holds our payload until AX confirms delivery, a confirmed miss exhausts
    /// retries, or the hold timeout expires (unverified). Restores the prior pasteboard afterward.
    ///
    /// - Parameters:
    ///   - bundleID: frontmost app, used only for §3.4 timing adaptation. Captured by the caller at
    ///     paste time rather than read here, so an app switch mid-paste cannot mislabel the sample.
    ///   - focusedRole: AX role of the focused element at inject time. §8.4: delivery-trust
    ///     verdicts are role-scoped (a Chromium web view must not decide for the same app's
    ///     native fields), so the hold loop must ask with the same key the condemnation was
    ///     recorded under — asking bundle-only is how the antigravity incident re-pasted.
    ///   - staleProbe: text the caller *removed* from the field just before this paste (the
    ///     erased trigger). If a verification read still shows it, the mirror is stale by
    ///     construction and its "missing" answer is discarded.
    ///   - leaveClipboardOnFailure: When true, skip immediate restore on `.notPosted` / `.failed` so the
    ///     concealed payload remains for a manual ⌘V (secure clipboard paste under Secure Input).
    ///   - holdTimeoutOverride: Optional longer hold (e.g. secure clipboard paste under SI).
    ///   - completeBeforeRestore: When true and no `expectedText`, report `.unavailable` right after
    ///     Cmd+V so callers are not blocked for the full hold window.
    public func pasteViaClipboard(
        text: String,
        expectedText: String?,
        baseline: DeliveryVerifier.FocusedTextObservation?,
        bundleID: String? = nil,
        focusedRole: String? = nil,
        staleProbe: String? = nil,
        staleProbeCaseInsensitive: Bool = false,
        leaveClipboardOnFailure: Bool = false,
        holdTimeoutOverride: TimeInterval? = nil,
        completeBeforeRestore: Bool = false,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        // Re-check Post Events at paste time.
        guard CGPreflightPostEventAccess() else {
            DevTypeLog.inject.error("[Inject] paste refused — Post Events denied at paste time")
            completion(.notPosted)
            return
        }

        let pasteboard = NSPasteboard.general
        let oldItems = acquireUserClipboardSnapshot(pasteboard: pasteboard)
        let generation = beginRestoreGeneration()

        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        pasteboard.setData(Data(), forType: PasteboardBroker.transientType)
        pasteboard.setData(Data(), forType: PasteboardBroker.concealedType)
        pasteboard.setData(Data(), forType: PasteboardBroker.autoGeneratedType)

        let ticket = ClipboardTicket(
            pasteboard: pasteboard,
            oldItems: oldItems,
            generation: generation,
            targetChangeCount: pasteboard.changeCount
        )
        registerPendingTicket(ticket)

        let restoreDelayValue = holdTimeoutOverride
            ?? restoreDelay(bundleID: bundleID, payloadBytes: text.utf8.count)
        let holdTimeoutValue = holdTimeoutOverride
            ?? max(timing.holdTimeout(bundleID: bundleID), restoreDelayValue)
        // §8.12: the board must stay readable for the *host*, which is a different and longer
        // question than how long we keep interrogating AX. `atLeast` keeps an explicit caller
        // override (the 8 s secure-clipboard window) from being clamped down to the ceiling.
        let unverifiedHold = timing.unverifiedPayloadResidency(
            bundleID: bundleID,
            payloadBytes: text.utf8.count,
            atLeast: restoreDelayValue
        )
        // The ⌘V goes to whoever is frontmost when it is posted; resolving the pid here rather
        // than at release time means a later app switch cannot re-point the stall probe at an
        // innocent process.
        let targetPID = NSWorkspace.shared.frontmostApplication?.processIdentifier
        // Free responsiveness baseline: `baseline` is a completed AX read of this app's focused
        // element taken moments ago by the caller. If it answered, the app was alive; if it never
        // speaks AX, the stall probe stays disarmed rather than firing on every expansion.
        let hostRespondedAtPaste = baseline != nil

        DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.prePasteSettleDelay) {
            self.hid.postCmdVKeyEventsAsync { posted in
                guard posted else {
                    // No ⌘V exists, so nothing is waiting to read the board — only an explicit
                    // manual-paste window can keep the payload up.
                    self.releaseOwnership(
                        ticket,
                        result: .notPosted,
                        residency: nil,
                        notBefore: leaveClipboardOnFailure
                            ? Date().addingTimeInterval(restoreDelayValue)
                            : nil
                    )
                    completion(.notPosted)
                    return
                }

                let residency = PayloadResidency(
                    postedAt: Date(),
                    unverifiedHold: unverifiedHold,
                    ceiling: max(InjectTiming.unverifiedPayloadResidencyCeiling, unverifiedHold),
                    targetPID: targetPID,
                    hostRespondedAtPaste: hostRespondedAtPaste,
                    bundleID: bundleID
                )

                guard let expectedText, !expectedText.isEmpty else {
                    // Nothing to verify, so this paste can never produce read evidence: it always
                    // owes the full residency.
                    if completeBeforeRestore {
                        completion(.unavailable)
                        self.releaseOwnership(ticket, result: .unavailable, residency: residency)
                    } else {
                        self.releaseOwnership(
                            ticket,
                            result: .unavailable,
                            residency: residency,
                            onReleased: { completion(.unavailable) }
                        )
                    }
                    return
                }

                self.runPasteHoldLoop(
                    expectedText: expectedText,
                    baseline: baseline,
                    bundleID: bundleID,
                    focusedRole: focusedRole,
                    staleProbe: staleProbe,
                    staleProbeCaseInsensitive: staleProbeCaseInsensitive,
                    pasteAttemptsCompleted: 1,
                    holdStarted: Date(),
                    holdTimeout: holdTimeoutValue,
                    ticket: ticket,
                    residency: residency,
                    leaveClipboardOnFailure: leaveClipboardOnFailure,
                    completion: completion
                )
            }
        }
    }

    private func runPasteHoldLoop(
        expectedText: String,
        baseline: DeliveryVerifier.FocusedTextObservation?,
        bundleID: String?,
        focusedRole: String?,
        staleProbe: String?,
        staleProbeCaseInsensitive: Bool,
        pasteAttemptsCompleted: Int,
        holdStarted: Date,
        holdTimeout: TimeInterval,
        ticket: ClipboardTicket,
        residency: PayloadResidency,
        leaveClipboardOnFailure: Bool,
        consecutiveFailures: Int = 0,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.pasteDeliverySettleDelay) {
            let safeBundleID = DevTypeLog.boundedPublicIdentifier(bundleID, label: "bundleID")
            let delivery = self.verifier.verifyFocusedTextDelivery(
                expectedText: expectedText,
                baseline: baseline,
                staleProbe: staleProbe,
                staleProbeCaseInsensitive: staleProbeCaseInsensitive
            )
            let elapsed = Date().timeIntervalSince(holdStarted)
            // Reset on any non-failure so only an uninterrupted run of failures counts as proof.
            let failures = (delivery == .failed) ? consecutiveFailures + 1 : 0
            // §8.4: a `.failed` read may only drive corrective writes (re-paste here, the trigger
            // restore downstream) when this `(bundle, role)` is a proven truthful witness — never
            // condemned, and with at least one earlier in-window AX-confirmed delivery. Unknown
            // apps are *not* trusted by default: the first contact with a readable-but-lying
            // mirror (com.google.antigravity) is exactly where "trust until condemned" doubled
            // the user's text.
            let trustFailure = AXWriteCapabilityStore.shared.mayActOnDeliveryFailure(
                bundleID: bundleID,
                role: focusedRole
            )
            // Logged once per hold — the loop re-reads every `pasteDeliverySettleDelay`, and a
            // line per tick would bury the decision it is meant to explain.
            if delivery == .failed, !trustFailure, failures == 1 {
                DevTypeLog.inject.notice(
                    """
                    [Inject] paste hold: AX says missing but \(safeBundleID, privacy: .public) \
                    is not a proven delivery witness — not re-pasting (would duplicate)
                    """
                )
                InjectTelemetryLog.shared.recordSuppressedMissVerdict(bundleID: bundleID)
            }
            let decision = PasteboardBroker.decidePasteHold(
                delivery: delivery,
                pasteAttemptsCompleted: pasteAttemptsCompleted,
                elapsed: elapsed,
                holdTimeout: holdTimeout,
                consecutiveFailures: failures,
                trustFailureVerdict: trustFailure
            )

            switch decision {
            case .succeed:
                // §3.4: this is the one moment the system actually *measures* how long this app
                // takes to consume a paste. Everything else in `InjectTiming` is a guess.
                self.timing.recordDeliveryLatency(elapsed, bundleID: bundleID)
                // §8.4: an in-window AX confirmation is the one event that earns read trust —
                // this `(bundle, role)` may now have future confirmed misses acted on. Late
                // confirmations (the pipeline's deferred re-verify) deliberately do not qualify.
                AXWriteCapabilityStore.shared.recordDeliveryConfirmed(
                    bundleID: bundleID,
                    role: focusedRole
                )
                // §8.12: the one outcome that proves the host read the board. Restore at once.
                self.releaseOwnership(ticket, result: .delivered, residency: residency)
                completion(.delivered)

            case .failConfirmed:
                DevTypeLog.inject.error(
                    """
                    [Inject] paste hold: AX readable but expected text missing after \
                    \(pasteAttemptsCompleted, privacy: .public) Cmd+V attempt(s) — \
                    app=\(safeBundleID, privacy: .public) \
                    elapsed=\(Int(elapsed * 1000), privacy: .public)ms
                    """
                )
                self.releaseOwnership(
                    ticket,
                    result: .failed,
                    residency: residency,
                    notBefore: leaveClipboardOnFailure
                        ? Date().addingTimeInterval(holdTimeout)
                        : nil
                )
                completion(.failed)

            case .giveUpUnverified:
                // §8.12: no evidence at all that the host read the board — the payload owes its
                // full residency, and a stalled host extends it further.
                self.releaseOwnership(ticket, result: .unavailable, residency: residency)
                completion(.unavailable)

            case .retryPaste:
                // The one action in this file that can duplicate the user's text if the verdict
                // driving it is wrong, so it says exactly what convinced it.
                DevTypeLog.inject.notice(
                    """
                    [Inject] paste hold: retrying Cmd+V (attempt \(pasteAttemptsCompleted + 1, privacy: .public)) — \
                    app=\(safeBundleID, privacy: .public) \
                    consecutiveMisses=\(failures, privacy: .public) \
                    elapsed=\(Int(elapsed * 1000), privacy: .public)ms
                    """
                )
                InjectTelemetryLog.shared.recordPasteRetry(bundleID: bundleID)
                self.hid.postCmdVKeyEventsAsync { posted in
                    guard posted else {
                        self.releaseOwnership(
                            ticket,
                            result: .failed,
                            residency: residency,
                            notBefore: leaveClipboardOnFailure
                                ? Date().addingTimeInterval(holdTimeout)
                                : nil
                        )
                        completion(.failed)
                        return
                    }
                    // §8.12: a retry is a *new* keystroke, so the residency clock restarts. The
                    // first ⌘V having aged out says nothing about when this one will be consumed.
                    self.runPasteHoldLoop(
                        expectedText: expectedText,
                        baseline: baseline,
                        bundleID: bundleID,
                        focusedRole: focusedRole,
                        staleProbe: staleProbe,
                        staleProbeCaseInsensitive: staleProbeCaseInsensitive,
                        pasteAttemptsCompleted: pasteAttemptsCompleted + 1,
                        holdStarted: holdStarted,
                        holdTimeout: holdTimeout,
                        ticket: ticket,
                        residency: residency.restarted(at: Date()),
                        leaveClipboardOnFailure: leaveClipboardOnFailure,
                        consecutiveFailures: 0,
                        completion: completion
                    )
                }

            case .waitMore:
                self.runPasteHoldLoop(
                    expectedText: expectedText,
                    baseline: baseline,
                    bundleID: bundleID,
                    focusedRole: focusedRole,
                    staleProbe: staleProbe,
                    staleProbeCaseInsensitive: staleProbeCaseInsensitive,
                    pasteAttemptsCompleted: pasteAttemptsCompleted,
                    holdStarted: holdStarted,
                    holdTimeout: holdTimeout,
                    ticket: ticket,
                    residency: residency,
                    leaveClipboardOnFailure: leaveClipboardOnFailure,
                    consecutiveFailures: failures,
                    completion: completion
                )
            }
        }
    }

    // MARK: - Image paste

    /// Clipboard-pastes an image (TIFF + PNG reps) with the same snapshot/restore
    /// discipline as `pasteViaClipboard`. Used by image snippets only.
    ///
    /// §3.4: two fixes here. The restore delay no longer runs image bytes through the *text*
    /// formula (a 1 MB image computed 25 s and clamped to 0.45 s, i.e. the number was noise), and
    /// the paste is no longer fire-and-forget — the payload is held while AX is polled for
    /// evidence the field changed, exactly like the text hold loop.
    ///
    /// Deliberately **no** automatic re-paste: unlike text there is no expected string to look for,
    /// and several hosts (Slack, Mail) attach an image without changing the focused element's
    /// `AXValue` at all. Re-pasting on that evidence would insert the image twice, which is worse
    /// than reporting `postedUnverified`. Verification here is reporting-only.
    public func pasteImageViaClipboard(
        image: NSImage,
        bundleID: String? = nil,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        guard CGPreflightPostEventAccess() else {
            DevTypeLog.inject.error("[Inject] image paste refused — Post Events denied at paste time")
            completion(.notPosted)
            return
        }

        let pasteboard = NSPasteboard.general
        let oldItems = acquireUserClipboardSnapshot(pasteboard: pasteboard)
        let generation = beginRestoreGeneration()

        pasteboard.clearContents()
        var wrote = false
        if let tiff = image.tiffRepresentation {
            pasteboard.setData(tiff, forType: .tiff)
            wrote = true
        }
        if let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil) {
            let rep = NSBitmapImageRep(cgImage: cgImage)
            if let png = rep.representation(using: .png, properties: [:]) {
                pasteboard.setData(png, forType: .png)
                wrote = true
            }
        }
        guard wrote else {
            // Nothing of ours is on the board beyond the clear; put the user's clipboard back.
            let emptyTicket = ClipboardTicket(
                pasteboard: pasteboard,
                oldItems: oldItems,
                generation: generation,
                targetChangeCount: pasteboard.changeCount
            )
            registerPendingTicket(emptyTicket)
            releaseOwnership(emptyTicket, result: .notPosted, residency: nil)
            completion(.notPosted)
            return
        }
        pasteboard.setData(Data(), forType: PasteboardBroker.transientType)
        pasteboard.setData(Data(), forType: PasteboardBroker.concealedType)
        pasteboard.setData(Data(), forType: PasteboardBroker.autoGeneratedType)

        let ticket = ClipboardTicket(
            pasteboard: pasteboard,
            oldItems: oldItems,
            generation: generation,
            targetChangeCount: pasteboard.changeCount
        )
        registerPendingTicket(ticket)

        let payloadBytes = (pasteboard.data(forType: .tiff)?.count ?? 0)
            + (pasteboard.data(forType: .png)?.count ?? 0)
        let restoreDelayValue = calculateImageRestoreDelay(payloadBytes: payloadBytes)
        let holdTimeoutValue = max(restoreDelayValue, InjectTiming.imageDeliveryHoldTimeout)
        // §8.12: an image snippet that pastes the user's old clipboard is the same defect wearing
        // a different payload type, so it gets the same residency floor. Image bytes are a poor
        // proxy for host read time, hence `max` with the size-derived delay rather than a swap.
        let unverifiedHold = max(restoreDelayValue, InjectTiming.unverifiedPayloadResidencyFloor)
        let targetPID = NSWorkspace.shared.frontmostApplication?.processIdentifier

        DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.prePasteSettleDelay) {
            let baseline = self.verifier.captureFocusedTextObservation()
            self.hid.postCmdVKeyEventsAsync { posted in
                guard posted else {
                    self.releaseOwnership(ticket, result: .notPosted, residency: nil)
                    completion(.notPosted)
                    return
                }
                let residency = PayloadResidency(
                    postedAt: Date(),
                    unverifiedHold: unverifiedHold,
                    ceiling: max(InjectTiming.unverifiedPayloadResidencyCeiling, unverifiedHold),
                    targetPID: targetPID,
                    hostRespondedAtPaste: baseline != nil,
                    bundleID: bundleID
                )
                self.runImageHoldLoop(
                    baseline: baseline,
                    bundleID: bundleID,
                    holdStarted: Date(),
                    holdTimeout: holdTimeoutValue,
                    ticket: ticket,
                    residency: residency,
                    completion: completion
                )
            }
        }
    }

    private func runImageHoldLoop(
        baseline: DeliveryVerifier.FocusedTextObservation?,
        bundleID: String?,
        holdStarted: Date,
        holdTimeout: TimeInterval,
        ticket: ClipboardTicket,
        residency: PayloadResidency,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.pasteDeliverySettleDelay) {
            let elapsed = Date().timeIntervalSince(holdStarted)
            if self.focusedFieldChanged(since: baseline) {
                self.timing.recordDeliveryLatency(elapsed, bundleID: bundleID)
                self.releaseOwnership(ticket, result: .delivered, residency: residency)
                completion(.delivered)
                return
            }
            guard elapsed >= holdTimeout else {
                self.runImageHoldLoop(
                    baseline: baseline,
                    bundleID: bundleID,
                    holdStarted: holdStarted,
                    holdTimeout: holdTimeout,
                    ticket: ticket,
                    residency: residency,
                    completion: completion
                )
                return
            }
            // Held long enough. AX saw nothing change, which for an image is weak evidence at
            // best — report unverified rather than failed, and never re-paste (see the doc above).
            self.releaseOwnership(ticket, result: .unavailable, residency: residency)
            completion(.unavailable)
        }
    }

    /// Best-effort "something landed" probe for the image path. Requires a *readable, non-empty*
    /// baseline so virtualised hosts that always report an empty AXValue cannot produce a verdict.
    private func focusedFieldChanged(since baseline: DeliveryVerifier.FocusedTextObservation?) -> Bool {
        guard let baseline, let baselineValue = baseline.value, !baselineValue.isEmpty else {
            return false
        }
        guard let after = self.verifier.captureFocusedTextObservation(), after.value != nil else {
            return false
        }
        return after.value != baseline.value || after.selectedText != baseline.selectedText
    }

    // MARK: - Ownership

    /// §1.7 step 1: work out what the *user's* clipboard actually is, before we overwrite it.
    ///
    /// If our own payload from a previous, still-pending expansion is on the board, then the user's
    /// real clipboard is whatever that expansion was holding — not what we can read right now.
    /// Snapshotting the board here is exactly the bug: expansion #2 would adopt expansion #1's
    /// snippet as "the user's clipboard" and faithfully restore it later.
    private func acquireUserClipboardSnapshot(pasteboard: NSPasteboard) -> PasteboardSnapshot? {
        restoreLock.lock()
        let pending = pendingTicket
        restoreLock.unlock()

        if let pending, pending.targetChangeCount == pasteboard.changeCount {
            DevTypeLog.inject.notice(
                "[Inject] §1.7 clipboard still holds our previous payload — inheriting the pending restore instead of snapshotting it"
            )
            return pending.oldItems
        }
        if pending != nil {
            // The board moved on: either the user copied something (their content is what we are
            // about to snapshot, correctly) or the previous restore already ran. Either way the
            // stale ticket must not fire later — the generation bump below guarantees that.
            DevTypeLog.inject.debug(
                "[Inject] §1.7 abandoning stale clipboard ticket — pasteboard changed since our last paste"
            )
        }
        guard PasteboardBroker.mayAdoptAsUserClipboard(types: pasteboard.types) else {
            DevTypeLog.inject.info(
                "[Inject] clipboard holds a concealed payload — not adopting it as the user's clipboard"
            )
            return nil
        }
        return PasteboardBroker.snapshotPasteboard(pasteboard)
    }

    private func registerPendingTicket(_ ticket: ClipboardTicket) {
        restoreLock.lock()
        pendingTicket = ticket
        restoreLock.unlock()
    }

    private func clearPendingTicket(generation: UInt64) {
        restoreLock.lock()
        if pendingTicket?.generation == generation {
            pendingTicket = nil
        }
        restoreLock.unlock()
    }

    /// §8.1 / §8.12: the single pasteboard release. Every path that finishes with our payload on
    /// the board goes through here, and none of them decides its own timing.
    ///
    /// - Parameters:
    ///   - result: how the paste ended — the only input that can authorise an immediate release.
    ///   - residency: the ⌘V's residency, `nil` when no ⌘V was ever posted.
    ///   - notBefore: an independent floor, used by `leaveClipboardOnFailure` to keep a concealed
    ///     payload up for a manual ⌘V. Composed with residency by `max`, never by replacement —
    ///     a caller asking for an 8 s secure-paste window must not shorten it to the residency,
    ///     and the residency must not be shortened to a caller's smaller number either.
    ///   - onReleased: run after the user's clipboard is back, for callers whose contract is
    ///     "tell me when the board is theirs again".
    private func releaseOwnership(
        _ ticket: ClipboardTicket,
        result: PasteDeliveryResult,
        residency: PayloadResidency?,
        notBefore: Date? = nil,
        onReleased: (() -> Void)? = nil
    ) {
        var deadline = notBefore ?? .distantPast
        if let residency {
            let remaining = PasteboardBroker.remainingPayloadResidency(
                result: result,
                elapsedSincePaste: Date().timeIntervalSince(residency.postedAt),
                unverifiedHold: residency.unverifiedHold
            )
            deadline = max(deadline, Date().addingTimeInterval(remaining))
        }
        releaseWhenDue(
            ticket,
            result: result,
            residency: residency,
            notBefore: deadline,
            onReleased: onReleased
        )
    }

    /// Belt to the ceiling's braces. The ceiling is expressed in wall-clock time, and wall clock
    /// is not monotonic — an NTP step backwards during a hold would keep `elapsed` under the
    /// ceiling indefinitely. A plain count cannot be argued with.
    public static let maxStallExtensions = 16

    /// Waits out the deadline, then re-asks the stall question before letting go.
    private func releaseWhenDue(
        _ ticket: ClipboardTicket,
        result: PasteDeliveryResult,
        residency: PayloadResidency?,
        notBefore: Date,
        extensionsUsed: Int = 0,
        onReleased: (() -> Void)?
    ) {
        // A newer expansion (or a deliberate user-clipboard write) owns the board now. Bail before
        // spending an AX round trip on a ticket `restore` would refuse anyway.
        guard currentRestoreGeneration() == ticket.generation else {
            onReleased?()
            return
        }

        let wait = notBefore.timeIntervalSinceNow
        if wait > 0 {
            DispatchQueue.main.asyncAfter(deadline: .now() + wait) {
                self.releaseWhenDue(
                    ticket,
                    result: result,
                    residency: residency,
                    notBefore: notBefore,
                    extensionsUsed: extensionsUsed,
                    onReleased: onReleased
                )
            }
            return
        }

        if let residency,
           extensionsUsed < Self.maxStallExtensions,
           Self.wantsStallExtension(result: result, residency: residency) {
            let elapsed = Date().timeIntervalSince(residency.postedAt)
            if PasteboardBroker.shouldExtendResidencyForStalledHost(
                hostRespondedAtPaste: residency.hostRespondedAtPaste,
                hostRespondsNow: residency.targetPID.map { AXContextChecker.appRespondsToAX(pid: $0) } ?? true,
                elapsedSincePaste: elapsed,
                ceiling: max(residency.ceiling, residency.unverifiedHold)
            ) {
                InjectTelemetryLog.shared.recordClipboardHoldExtension(bundleID: residency.bundleID)
                let safeBundleID = DevTypeLog.boundedPublicIdentifier(
                    residency.bundleID,
                    label: "bundleID"
                )
                DevTypeLog.inject.notice(
                    """
                    [Inject] §8.12 holding the payload past its \
                    \(Int(residency.unverifiedHold * 1000), privacy: .public)ms residency — \
                    \(safeBundleID, privacy: .public) has stopped answering AX, \
                    so it has not consumed ⌘V yet \
                    (elapsed=\(Int(elapsed * 1000), privacy: .public)ms)
                    """
                )
                let next = min(
                    Date().addingTimeInterval(InjectTiming.stalledHostResidencyProbeInterval),
                    residency.hardDeadline
                )
                releaseWhenDue(
                    ticket,
                    result: result,
                    residency: residency,
                    notBefore: next,
                    extensionsUsed: extensionsUsed + 1,
                    onReleased: onReleased
                )
                return
            }
        }

        if let residency, result != .delivered, result != .notPosted {
            InjectTelemetryLog.shared.recordUnverifiedClipboardHold(
                bundleID: residency.bundleID,
                heldFor: Date().timeIntervalSince(residency.postedAt)
            )
        }
        restore(ticket)
        onReleased?()
    }

    /// Only outcomes with no read evidence can be extended — `.delivered` already proved the read
    /// and `.notPosted` has nothing to be read.
    private static func wantsStallExtension(
        result: PasteDeliveryResult,
        residency: PayloadResidency
    ) -> Bool {
        guard residency.targetPID != nil, residency.hostRespondedAtPaste else { return false }
        switch result {
        case .delivered, .notPosted: return false
        case .failed, .unavailable: return true
        }
    }

    // MARK: - Copy capture (clipboard-fallback selection read)

    /// How long to wait for the target app to answer a synthetic ⌘C with a pasteboard write,
    /// and how often to look. Copies are near-instant in practice; the timeout exists for apps
    /// that write the board from a secondary thread after the key event round-trips.
    public static let copyCaptureTimeout: TimeInterval = 0.30
    public static let copyCapturePollInterval: TimeInterval = 0.02

    /// What a `captureSelectionViaCopy` attempt produced. The label is recorded in the selection
    /// diagnostics — a fallback that ran and found the board untouched is a different bug report
    /// from one that never posted.
    public enum CopyCaptureOutcome: Equatable {
        /// The app answered ⌘C with a string. May still be blank — the *reader* owns blankness.
        case captured(String)
        /// ⌘C was posted and the pasteboard never changed: nothing selected, or the app ignores
        /// the chord. Indistinguishable from outside, and both mean "no selection to use".
        case boardUnchanged
        /// The app wrote the board but with no string representation (an image, a file).
        case noStringOnBoard
        /// The key events could not be posted (Post Events revoked mid-session).
        case postFailed
        /// The app that owned the selection lost focus before ⌘C could be posted.
        case sourceAppChanged
        /// Secure Event Input became active after the reader's earlier preflight.
        case secureInputActive

        public var diagnosticLabel: String {
            switch self {
            case .captured: return "captured"
            case .boardUnchanged: return "unchanged"
            case .noStringOnBoard: return "noString"
            case .postFailed: return "postFailed"
            case .sourceAppChanged: return "sourceChanged"
            case .secureInputActive: return "secureInput"
            }
        }
    }

    /// Pure identity check shared by the reader's early gate and the broker's immediate pre-post
    /// gate. Unknown and non-process ids fail closed; equality alone is insufficient for pid 0.
    public static func frontmostProcessMatches(expectedPID: pid_t, actualPID: pid_t?) -> Bool {
        expectedPID > 0 && actualPID == expectedPID
    }

    /// Pure: restore only when the board still shows the copy we observed. Anything else means
    /// another writer got there after our capture, and writing over them would eat *their* data
    /// to clean up after ours.
    public static func shouldRestoreAfterCopyCapture(
        changeCountNow: Int,
        changeCountAfterCopy: Int
    ) -> Bool {
        changeCountNow == changeCountAfterCopy
    }

    /// Last-resort selection read: snapshot the board, post ⌘C, wait briefly for the target app
    /// to write, read the string, put the user's clipboard back.
    ///
    /// This is the one sanctioned synthetic-copy path — `SelectionReader`'s "no unmanaged ⌘C"
    /// rule is about clipboard *ownership*, and this method is the owner: the same snapshot /
    /// changeCount / verified-restore machinery every paste already goes through, including
    /// inheriting a still-pending expansion restore rather than adopting our own payload as
    /// "the user's clipboard".
    ///
    /// Costs up to `copyCaptureTimeout` of calling-thread wait, so it is only for explicit user
    /// gestures, and only after every AX tier has failed. Two limits it cannot remove: a clipboard
    /// manager will see the transient copy (the *target app* writes the board, so nspasteboard.org
    /// markers cannot be attached), and an app that treats ⌘C-with-no-selection as "copy the
    /// current line" will report that line as the selection — which is why the caller only runs
    /// this when AX could not even resolve a focused element, never on a readable-but-empty
    /// selection.
    ///
    /// - Parameters:
    ///   - expectedFrontmostPID: Process that owned the selection before AX probing. Required so
    ///     callers cannot accidentally post an unpinned copy.
    ///   - frontmostPIDProvider: Live process lookup immediately before posting; injectable only
    ///     so the focus-theft branch can be tested without moving the user's real focus.
    ///   - secureInputProvider: Live Secure Input lookup at the same boundary.
    ///   - postCopy: The ⌘C itself, injectable so tests can simulate the target app.
    public func captureSelectionViaCopy(
        pasteboard: NSPasteboard = .general,
        expectedFrontmostPID: pid_t,
        timeout: TimeInterval = copyCaptureTimeout,
        pollInterval: TimeInterval = copyCapturePollInterval,
        frontmostPIDProvider: () -> pid_t? = {
            NSWorkspace.shared.frontmostApplication?.processIdentifier
        },
        secureInputProvider: () -> Bool = {
            AXContextChecker.isSecureEventInputEnabledLive()
        },
        postCopy: (() -> Bool)? = nil
    ) -> CopyCaptureOutcome {
        let snapshot = acquireUserClipboardSnapshot(pasteboard: pasteboard)
        let baseline = pasteboard.changeCount

        // Snapshotting can traverse several clipboard representations. Re-check both volatile
        // gates after that work and immediately before input posting, not merely on reader entry.
        guard !secureInputProvider() else { return .secureInputActive }
        guard Self.frontmostProcessMatches(
            expectedPID: expectedFrontmostPID,
            actualPID: frontmostPIDProvider()
        ) else {
            return .sourceAppChanged
        }

        let posted: Bool
        if let postCopy {
            posted = postCopy()
        } else {
            posted = hid.postCmdCKeyEvents {
                !secureInputProvider()
                    && Self.frontmostProcessMatches(
                        expectedPID: expectedFrontmostPID,
                        actualPID: frontmostPIDProvider()
                    )
            }
        }
        guard posted else {
            if secureInputProvider() { return .secureInputActive }
            if !Self.frontmostProcessMatches(
                expectedPID: expectedFrontmostPID,
                actualPID: frontmostPIDProvider()
            ) {
                return .sourceAppChanged
            }
            return .postFailed
        }

        let deadline = Date().addingTimeInterval(timeout)
        while pasteboard.changeCount == baseline, Date() < deadline {
            usleep(useconds_t(max(pollInterval, 0.001) * 1_000_000))
        }
        guard pasteboard.changeCount != baseline else {
            // Nothing was written, so nothing needs restoring — the board was never touched.
            return .boardUnchanged
        }

        let afterCopy = pasteboard.changeCount

        // One extra poll interval: apps that declare types first and provide data second bump
        // `changeCount` before the string is actually there.
        usleep(useconds_t(max(pollInterval, 0.001) * 1_000_000))
        let captured = pasteboard.string(forType: .string)

        if Self.shouldRestoreAfterCopyCapture(
            changeCountNow: pasteboard.changeCount,
            changeCountAfterCopy: afterCopy
        ) {
            pasteboard.clearContents()
            let postClearChangeCount = pasteboard.changeCount
            if let snapshot, !snapshot.isEmpty {
                writeCopyCaptureRestore(
                    snapshot,
                    to: pasteboard,
                    ownedChangeCount: postClearChangeCount,
                    attempt: 0
                )
            }
            // An empty snapshot restores to an empty board: leaving the captured selection up
            // would hand it to every clipboard manager watching the board.
        } else {
            DevTypeLog.inject.notice(
                "[Inject] copy-capture restore abandoned — another owner wrote the pasteboard during capture"
            )
        }

        guard let captured else { return .noStringOnBoard }
        return .captured(captured)
    }

    /// §1.7: bounded pasteboard snapshot. See `snapshotMaxItems` for the tradeoff.
    private static func snapshotPasteboard(_ pasteboard: NSPasteboard) -> PasteboardSnapshot? {
        guard let items = pasteboard.pasteboardItems else { return nil }
        var result: PasteboardSnapshot = []
        var budget = snapshotMaxBytes
        var skipped = 0

        for item in items.prefix(snapshotMaxItems) {
            var dict = [NSPasteboard.PasteboardType: Data]()
            for type in item.types {
                if snapshotSkippedTypes.contains(type.rawValue) {
                    skipped += 1
                    continue
                }
                guard let data = item.data(forType: type) else { continue }
                if data.count > budget {
                    skipped += 1
                    continue
                }
                budget -= data.count
                dict[type] = data
            }
            if !dict.isEmpty {
                result.append(dict)
            }
        }
        if items.count > snapshotMaxItems {
            skipped += items.count - snapshotMaxItems
        }
        if skipped > 0 {
            DevTypeLog.inject.notice(
                "[Inject] §1.7 clipboard snapshot bounded — \(skipped, privacy: .public) representation(s) not preserved (promised files and payloads over \(snapshotMaxBytes, privacy: .public) bytes are skipped)"
            )
        }
        return result
    }

    /// True when the board still carries our nspasteboard.org markers, i.e. the content on it is
    /// still our payload even though `changeCount` moved (some hosts rewrite the board while
    /// handling ⌘V).
    private static func holdsOurPayload(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains(autoGeneratedType)
            || types.contains(concealedType)
            || types.contains(transientType)
    }

    /// Rebuilds `NSPasteboardItem`s from a bounded snapshot, atomically at the item-set level.
    /// `NSPasteboardItem.setData` can refuse an individual representation. Returning an item with
    /// only the successful flavors would let an outer `writeObjects` report success for an
    /// incomplete restore, so one refusal rejects the entire reconstruction before any item is
    /// published to the pasteboard.
    private static func makeRestoredItems(
        _ snapshot: PasteboardSnapshot,
        setData: (NSPasteboardItem, Data, NSPasteboard.PasteboardType) -> Bool = {
            item, data, type in item.setData(data, forType: type)
        }
    ) -> [NSPasteboardItem]? {
        guard !snapshot.isEmpty else { return nil }
        var restoredItems: [NSPasteboardItem] = []
        restoredItems.reserveCapacity(snapshot.count)
        for itemDict in snapshot {
            guard !itemDict.isEmpty else { return nil }
            let newItem = NSPasteboardItem()
            for (type, data) in itemDict {
                guard setData(newItem, data, type) else { return nil }
            }
            restoredItems.append(newItem)
        }
        return restoredItems
    }

    /// Conditional complete-snapshot restore used by the deliberate user-write transaction.
    /// Fault injection lives here so a representation refusal is tested through the same
    /// ownership checks and outcome type as production.
    static func restoreUserClipboardSnapshot(
        _ snapshot: PasteboardSnapshot,
        ownedChangeCount: Int,
        currentChangeCount: () -> Int,
        setData: (NSPasteboardItem, Data, NSPasteboard.PasteboardType) -> Bool = {
            item, data, type in item.setData(data, forType: type)
        },
        writeObjects: ([NSPasteboardItem]) -> Bool
    ) -> UserClipboardRestoreOutcome {
        // Check both before and after rebuilding local items. Clipboard data providers can be
        // non-trivial, and a newer external owner that arrives during reconstruction stays put.
        guard currentChangeCount() == ownedChangeCount else { return .ownershipLost }
        guard let restoredItems = makeRestoredItems(snapshot, setData: setData) else {
            DevTypeLog.inject.error(
                "[Clipboard] bounded snapshot reconstruction failed — no partial representation set was written"
            )
            return .failed
        }
        guard currentChangeCount() == ownedChangeCount else { return .ownershipLost }
        return writeObjects(restoredItems) ? .restored : .failed
    }

    /// Writes a copy-capture snapshot back onto `pasteboard` with the same bounded retry policy
    /// as `restore(_:attempt:)`. The board was already cleared for this capture, so every attempt
    /// first re-checks that we still own it (`changeCount` unchanged since our clear, or our
    /// markers present) — an owner that claimed the board during the retry window is left alone
    /// rather than clobbered.
    private func writeCopyCaptureRestore(
        _ snapshot: PasteboardSnapshot,
        to pasteboard: NSPasteboard,
        ownedChangeCount: Int,
        attempt: Int
    ) {
        guard pasteboard.changeCount == ownedChangeCount || Self.holdsOurPayload(pasteboard) else {
            DevTypeLog.inject.notice(
                "[Inject] copy-capture restore retry abandoned — another owner wrote the pasteboard during recovery"
            )
            return
        }
        guard let restoredItems = Self.makeRestoredItems(snapshot) else {
            DevTypeLog.inject.error(
                "[Inject] copy-capture clipboard restore refused — a snapshot representation could not be rebuilt"
            )
            return
        }
        // Re-check after rebuilding the local items as well as before it.
        guard pasteboard.changeCount == ownedChangeCount || Self.holdsOurPayload(pasteboard) else {
            DevTypeLog.inject.notice(
                "[Inject] copy-capture restore abandoned — another owner wrote the pasteboard during reconstruction"
            )
            return
        }
        if pasteboard.writeObjects(restoredItems) {
            return
        }
        guard attempt + 1 < InjectTiming.maxPasteboardRestoreAttempts else {
            DevTypeLog.inject.error(
                "[Inject] copy-capture clipboard restore failed after \(InjectTiming.maxPasteboardRestoreAttempts, privacy: .public) attempts — the user's clipboard was not restored"
            )
            return
        }
        DevTypeLog.inject.notice(
            "[Inject] copy-capture clipboard restore write failed — retry \(attempt + 1, privacy: .public)"
        )
        DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.pasteboardRestoreRetryDelay) { [weak self] in
            self?.writeCopyCaptureRestore(
                snapshot,
                to: pasteboard,
                ownedChangeCount: ownedChangeCount,
                attempt: attempt + 1
            )
        }
    }

    private func restore(_ ticket: ClipboardTicket, attempt: Int = 0) {
        // Generation gate: a newer expand owns the pasteboard — skip stale restore.
        guard currentRestoreGeneration() == ticket.generation else { return }

        let pasteboard = ticket.pasteboard
        if pasteboard.changeCount != ticket.targetChangeCount {
            if PasteboardBroker.holdsOurPayload(pasteboard) {
                // Still our content, just rewritten by the host mid-paste. Safe to restore.
                DevTypeLog.inject.notice(
                    "[Inject] §1.7 clipboard changeCount moved (\(pasteboard.changeCount, privacy: .public) != \(ticket.targetChangeCount, privacy: .public)) but our markers are still present — restoring anyway"
                )
            } else {
                // §1.7: this used to be a silent `return` — the user's clipboard was simply gone
                // with no log, no fallback and no retry. It is still not safe to write here (a
                // real owner would be clobbered), but it is no longer invisible.
                DevTypeLog.inject.notice(
                    "[Inject] §1.7 clipboard restore abandoned — another owner wrote the pasteboard (change \(pasteboard.changeCount, privacy: .public) != \(ticket.targetChangeCount, privacy: .public)); leaving their contents in place"
                )
                clearPendingTicket(generation: ticket.generation)
                return
            }
        }

        pasteboard.clearContents()
        guard let oldItems = ticket.oldItems, !oldItems.isEmpty else {
            clearPendingTicket(generation: ticket.generation)
            return
        }

        guard let restoredItems = Self.makeRestoredItems(oldItems) else {
            DevTypeLog.inject.error(
                "[Inject] §1.7 clipboard restore refused — a snapshot representation could not be rebuilt"
            )
            clearPendingTicket(generation: ticket.generation)
            return
        }
        let wrote = pasteboard.writeObjects(restoredItems)
        if !wrote {
            if attempt + 1 < InjectTiming.maxPasteboardRestoreAttempts {
                DevTypeLog.inject.notice(
                    "[Inject] §1.7 clipboard restore write failed — retry \(attempt + 1, privacy: .public)"
                )
                // We already cleared the board, so our clear is now the current change count.
                var retryTicket = ticket
                retryTicket.targetChangeCount = pasteboard.changeCount
                DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.pasteboardRestoreRetryDelay) {
                    self.restore(retryTicket, attempt: attempt + 1)
                }
                return
            }
            DevTypeLog.inject.error(
                "[Inject] §1.7 clipboard restore failed after \(InjectTiming.maxPasteboardRestoreAttempts, privacy: .public) attempts — the user's clipboard was not restored"
            )
        }
        clearPendingTicket(generation: ticket.generation)
    }
}
