import AppKit
import Foundation

/// Puts a secret on the pasteboard for a manual ⌘V, and takes it off again.
///
/// This is the path that works when nothing else does. While a password field holds focus, macOS
/// Secure Event Input withholds keyboard events from every event tap *and* from hotkey
/// registration (TN2150), so DevType can neither see a typed trigger nor be summoned by a chord.
/// A menu-bar click needs neither: the menu is driven by the mouse, and the clipboard write is an
/// ordinary API call rather than a synthesised keystroke. The user then presses ⌘V themselves,
/// which is their own keystroke going to their own app — nothing DevType has to intercept.
///
/// The cost is that the value sits on the pasteboard, so this class exists mainly to bound that:
/// marked concealed for clipboard managers, and cleared on a timer that refuses to clear anything
/// the user copied afterwards.
public final class SecretClipboard {
    public static let shared = SecretClipboard()

    /// How long a copied secret stays on the pasteboard before being cleared.
    ///
    /// Long enough to switch apps, click the field and paste — including a slow first attempt in a
    /// browser that re-prompts for the account. Short enough that walking away from the machine
    /// does not leave a password on the clipboard for the rest of the day. The clear is also
    /// forced at quit; a timer alone would leave the value behind on a crash.
    public static let defaultClearAfter: TimeInterval = 90

    /// Result of a scheduled clear, so the caller can report honestly instead of assuming.
    public enum ClearOutcome: String, Equatable, Sendable {
        /// Our payload was still there and has been removed.
        case cleared
        /// The user (or another app) copied something afterwards. Left strictly alone.
        case supersededByUser
        /// Nothing was outstanding.
        case nothingToClear
    }

    private let lock = UnfairLock()
    /// `changeCount` of the write we own. Any later value means someone else owns the board now.
    private var ownedChangeCount: Int?
    private var clearWorkItem: DispatchWorkItem?

    public init() {}

    /// Pure policy: may a scheduled clear actually wipe the pasteboard?
    ///
    /// Only when the board still holds *our* write. This is the same rule as the expansion
    /// restore path and it matters more here: a user who copies a bank account number thirty
    /// seconds after copying a password must not have it wiped by our timer. When in doubt, leave
    /// the clipboard alone — the cost of a missed clear is a secret living longer than intended,
    /// the cost of a wrong clear is destroying something the user is mid-way through using.
    public static func mayClear(ownedChangeCount: Int?, currentChangeCount: Int) -> Bool {
        guard let ownedChangeCount else { return false }
        return ownedChangeCount == currentChangeCount
    }

    /// Copy a secret to the pasteboard and schedule its removal.
    ///
    /// - Returns: when the value will be cleared, for the confirmation the UI shows. `nil` when
    ///   nothing was copied (empty value — never write an empty "secret" and claim success).
    @discardableResult
    public func copy(
        _ secret: String,
        clearAfter: TimeInterval = defaultClearAfter,
        pasteboard: NSPasteboard = .general,
        broker: PasteboardBroker? = .shared,
        schedule: ((@escaping () -> Void, TimeInterval) -> Void)? = nil
    ) -> Date? {
        guard !secret.isEmpty else { return nil }

        cancelPendingClear()

        // Before the write, not after: an expansion's restore may still be scheduled, and it would
        // put the pre-expansion clipboard back over this secret. Worse, the markers set below make
        // `holdsOurPayload` read this write as our own payload, so the restore would consider
        // overwriting it *safe*. The hold window is 8 s under Secure Input — which is exactly when
        // a secret is being copied.
        broker?.invalidatePendingRestore()

        pasteboard.clearContents()
        pasteboard.setString(secret, forType: .string)
        // `ConcealedType` is the convention clipboard managers honour to mean "do not record
        // this" — it is what password managers mark their own copies with. Transient says "do not
        // persist"; AutoGenerated says a human did not type it. None of them are enforced by the
        // OS, so they reduce exposure rather than remove it.
        pasteboard.setData(Data(), forType: PasteboardBroker.concealedType)
        pasteboard.setData(Data(), forType: PasteboardBroker.transientType)
        pasteboard.setData(Data(), forType: PasteboardBroker.autoGeneratedType)

        lock.lock()
        ownedChangeCount = pasteboard.changeCount
        lock.unlock()

        let work = DispatchWorkItem { [weak self] in
            _ = self?.clearIfStillOurs(pasteboard: pasteboard)
        }
        lock.lock()
        clearWorkItem = work
        lock.unlock()

        if let schedule {
            schedule({ work.perform() }, clearAfter)
        } else {
            DispatchQueue.main.asyncAfter(deadline: .now() + clearAfter, execute: work)
        }

        // Length only. The value never reaches a log line, here or anywhere.
        DevTypeLog.inject.info(
            """
            [Secret] copied to clipboard chars=\(secret.count, privacy: .public) \
            clearAfter=\(Int(clearAfter), privacy: .public)s
            """
        )
        return Date().addingTimeInterval(clearAfter)
    }

    /// Remove the secret now, if the board still holds ours. Safe to call at any time.
    @discardableResult
    public func clearIfStillOurs(pasteboard: NSPasteboard = .general) -> ClearOutcome {
        lock.lock()
        let owned = ownedChangeCount
        lock.unlock()

        guard owned != nil else { return .nothingToClear }

        let outcome: ClearOutcome
        if Self.mayClear(ownedChangeCount: owned, currentChangeCount: pasteboard.changeCount) {
            pasteboard.clearContents()
            outcome = .cleared
        } else {
            outcome = .supersededByUser
        }

        lock.lock()
        ownedChangeCount = nil
        clearWorkItem = nil
        lock.unlock()

        DevTypeLog.inject.info("[Secret] clipboard clear → \(outcome.rawValue, privacy: .public)")
        return outcome
    }

    /// True while a copied secret is still believed to be on the pasteboard.
    public var hasOutstandingSecret: Bool {
        lock.lock()
        defer { lock.unlock() }
        return ownedChangeCount != nil
    }

    private func cancelPendingClear() {
        lock.lock()
        let pending = clearWorkItem
        clearWorkItem = nil
        lock.unlock()
        pending?.cancel()
    }
}
