import AppKit
import ApplicationServices
import Carbon
import CoreGraphics
import Foundation

/// §8.2: the four values that describe "the key the event tap ate on our behalf".
///
/// `swallowedFinalKey` / `swallowedUnicode` / `swallowedKeyCode` / `swallowedFlags` used to travel
/// as four separate parameters through nine signatures — `inject`, `injectOnMain`,
/// `injectSecureClipboardPasteOnMain`, `refuseInjectKeepingSwallow`, `finishPasteDelivery`,
/// `restoreTriggerAfterFailedPaste`, and their mirrors in `EventTapEngine`. Thirty-six parameters
/// carrying nine pieces of information.
///
/// This also folds in `EventTapEngine.mustReinjectOnRefuse(didSwallow:)`, which is the single rule
/// that makes the swallow contract safe: the tap only returns `nil` for the trigger key after the
/// planner has synchronously said the expand may proceed, so **any** later refuse owes the user
/// that keystroke back.
public struct SwallowedKey {
    /// True when the event tap swallowed the final trigger key (`return nil` from the callback).
    public let didSwallow: Bool
    public let unicode: String
    public let keyCode: Int64
    public let flags: CGEventFlags

    public init(
        didSwallow: Bool,
        unicode: String = "",
        keyCode: Int64 = 0,
        flags: CGEventFlags = []
    ) {
        self.didSwallow = didSwallow
        self.unicode = unicode
        self.keyCode = keyCode
        self.flags = flags
    }

    /// Nothing was swallowed — explicit inject paths (hotkey, inline search, Test Expansion Lab).
    public static let notSwallowed = SwallowedKey(didSwallow: false)

    /// §8.2: `EventTapEngine.mustReinjectOnRefuse(didSwallow:)` is delegated to rather than
    /// duplicated, so the swallow contract keeps exactly one definition.
    public var mustReinjectOnRefuse: Bool {
        EventTapEngine.mustReinjectOnRefuse(didSwallow: didSwallow)
    }

    /// False when there is nothing to post back (no character and no key code).
    public var hasPayload: Bool {
        !unicode.isEmpty || keyCode != 0
    }
}

/// The policy coordinator for text injection.
///
/// §8.1: the mechanics live in five collaborators this type owns — `HIDKeyPoster` (every CGEvent),
/// `PasteboardBroker` (the clipboard snapshot/restore invariant), `AXTextWriter` (the only code
/// touching `kAXSelectedText*`), `DeliveryVerifier` (did it land?) and `EraseExecutor` (what gets
/// deleted, and proving that is safe). What is left here is the decision-making: which path to
/// take, when to refuse, and what to tell the user afterwards.
///
/// The safety contract, unchanged:
/// * fail closed when AX is unavailable,
/// * refuse inside secure text fields, during IME composition, and in muted apps,
/// * the trigger key is swallowed only after a sync-safe planner allow, and every asynchronous
///   refuse reinjects it.
public final class TextInjectionPipeline {
    public static let shared = TextInjectionPipeline()

    // MARK: - Types (re-exported so existing call sites and tests are untouched)

    public typealias FocusedTextObservation = DeliveryVerifier.FocusedTextObservation
    public typealias TextDeliveryVerification = DeliveryVerifier.TextDeliveryVerification
    public typealias PasteDeliveryResult = PasteboardBroker.PasteDeliveryResult
    public typealias PasteHoldDecision = PasteboardBroker.PasteHoldDecision
    public typealias AXReplaceOutcome = AXTextWriter.AXReplaceOutcome

    public let transientType = PasteboardBroker.transientType
    public let concealedType = PasteboardBroker.concealedType
    public let autoGeneratedType = PasteboardBroker.autoGeneratedType

    /// §3.1: what the last delivered expansion did, so the user can take it back.
    ///
    /// Every competing expander reverts to the trigger when you press backspace right after an
    /// expansion. All the machinery for it already existed — `ErasePlan` knows the trigger text and
    /// both unit counts, and `restoreTriggerAfterFailedPaste` is a working "put the trigger back"
    /// implementation — it simply was not reachable by the user.
    public struct LastExpansion {
        /// The erase that made room for the expansion (i.e. the trigger side).
        public let erasePlan: ErasePlan
        /// Exactly what was injected. Undo erases this.
        public let injectedText: String
        /// What the user typed, restored by undo. This is the erased text plus the swallowed key,
        /// because the swallowed key never reached the field but the user did type it.
        public let triggerText: String
        public let bundleID: String?
        public let timestamp: Date

        public init(
            erasePlan: ErasePlan,
            injectedText: String,
            triggerText: String,
            bundleID: String?,
            timestamp: Date = Date()
        ) {
            self.erasePlan = erasePlan
            self.injectedText = injectedText
            self.triggerText = triggerText
            self.bundleID = bundleID
            self.timestamp = timestamp
        }

        public func isFresh(
            now: Date = Date(),
            window: TimeInterval = InjectTiming.undoExpansionWindow
        ) -> Bool {
            let age = now.timeIntervalSince(timestamp)
            return age >= 0 && age <= window
        }
    }

    // MARK: - Collaborators

    /// Serializes inject + pasteboard restore so back-to-back expands cannot contaminate clipboard.
    private let injectQueue = DispatchQueue(label: "com.devtype.inject", qos: .userInteractive)
    private let planner = InjectionPlanner()

    private let hid: HIDKeyPoster
    private let ax: AXTextWriter
    private let verifier: DeliveryVerifier
    private let clipboard: PasteboardBroker
    private let eraser: EraseExecutor
    private let timing: InjectTimingStore
    private let bracketedPaste: BracketedPasteCapabilityStore

    /// §2.4: `os_unfair_lock`, taken from both the inject queue and main.
    private let lastExpansionLock = UnfairLock()
    private var _lastExpansion: LastExpansion?

    public init() {
        hid = HIDKeyPoster.shared
        ax = AXTextWriter.shared
        verifier = DeliveryVerifier.shared
        clipboard = PasteboardBroker.shared
        eraser = EraseExecutor.shared
        timing = InjectTimingStore.shared
        bracketedPaste = BracketedPasteCapabilityStore.shared
    }

    // MARK: - Timing constants (see `InjectTiming` — these are kept as the public surface)

    /// Floor raised from 0.10 → 0.15 so slow Chromium/Electron hosts can read the pasteboard
    /// before we restore the user's previous clipboard contents.
    ///
    /// §3.4: this is the *blind* formula, used for apps DevType has never measured. Once an app has
    /// a p90 delivery latency, `PasteboardBroker` uses `InjectTimingStore.restoreDelay` instead.
    public func calculateRestoreDelay(payloadBytes: Int) -> TimeInterval {
        clipboard.calculateRestoreDelay(payloadBytes: payloadBytes)
    }

    /// Settle between Cmd+V and the first AX delivery check (while our text is still on the board).
    public static let pasteDeliverySettleDelay: TimeInterval = InjectTiming.pasteDeliverySettleDelay
    /// Max time to hold our pasteboard contents waiting for AX to become readable / catch up.
    public static let pasteDeliveryHoldTimeout: TimeInterval = InjectTiming.pasteDeliveryHoldTimeout
    /// Longer hold for password-field secure clipboard paste so the user can press ⌘V if
    /// synthetic paste is dropped under Secure Input.
    public static let secureClipboardPasteHoldTimeout: TimeInterval = InjectTiming.secureClipboardPasteHoldTimeout
    /// First Cmd+V + one retry when AX proves the field did not change.
    public static let pasteDeliveryMaxAttempts = InjectTiming.pasteDeliveryMaxAttempts
    /// Settle delay for the deferred AX re-verification pass after unverified HID paste.
    public static let pasteReverifyDelay: TimeInterval = InjectTiming.pasteReverifyDelay
    /// Settle delay before re-checking a failed precondition.
    public static let erasePreconditionRetryDelay: TimeInterval = InjectTiming.erasePreconditionRetryDelay

    /// Shown when secure clipboard paste cannot confirm delivery under Secure Input —
    /// concealed payload stays on the pasteboard for a manual ⌘V.
    public static let secureClipboardManualPasteMessage =
        "Password on clipboard — press ⌘V"

    /// Optional UI hook when secure clipboard paste leaves the payload for manual ⌘V.
    public var onSecureClipboardManualPasteHint: (() -> Void)?

    // MARK: - Pure policy re-exports

    /// Decide the next step of the clipboard-hold loop. `pasteAttemptsCompleted` counts Cmd+V posts so far.
    public static func decidePasteHold(
        delivery: TextDeliveryVerification,
        pasteAttemptsCompleted: Int,
        maxAttempts: Int = pasteDeliveryMaxAttempts,
        elapsed: TimeInterval,
        holdTimeout: TimeInterval = pasteDeliveryHoldTimeout
    ) -> PasteHoldDecision {
        PasteboardBroker.decidePasteHold(
            delivery: delivery,
            pasteAttemptsCompleted: pasteAttemptsCompleted,
            maxAttempts: maxAttempts,
            elapsed: elapsed,
            holdTimeout: holdTimeout
        )
    }

    /// Apps whose AX `AXSelectedText` / range replace returns success without mutating the field,
    /// or whose AX focus/selection is too weak to trust. Prefer HID backspace + paste (axPlusHID).
    ///
    /// This is only the *seed* list. The live decision goes through `AXWriteCapabilityStore`, which
    /// also learns unknown apps at runtime — see `shouldSkipAXSelectedText(bundleID:)`.
    public static func prefersHIDPasteOverAXSelectedText(bundleID: String) -> Bool {
        AXWriteCapabilityStore.seedVerdict(bundleID: bundleID) == .falseSuccess
    }

    /// Live decision: seeded priors plus anything learned this session or persisted from earlier ones.
    public static func shouldSkipAXSelectedText(bundleID: String) -> Bool {
        AXWriteCapabilityStore.shared.shouldSkipAXSelectedText(bundleID: bundleID)
    }

    /// §3.3: role-aware skip so a condemned `AXTextArea` does not force HID on the same app's
    /// native fields — and so a role learned mid-inject is honoured for the AX-direct step.
    public static func shouldSkipAXSelectedText(bundleID: String, role: String?) -> Bool {
        AXWriteCapabilityStore.shared.shouldSkipAXSelectedText(bundleID: bundleID, role: role)
    }

    /// Next restore generation token. Pure helper for tests; production uses `beginRestoreGeneration()`.
    public static func nextRestoreGeneration(current: UInt64) -> UInt64 {
        PasteboardBroker.nextRestoreGeneration(current: current)
    }

    /// UTF-16 code units still present in the focused field that must be erased before injection.
    public static func eraseCount(
        triggerLength: Int,
        swallowedFinalKey: Bool,
        lastEventCharacterCount: Int = 1
    ) -> Int {
        EraseExecutor.eraseCount(
            triggerLength: triggerLength,
            swallowedFinalKey: swallowedFinalKey,
            lastEventCharacterCount: lastEventCharacterCount
        )
    }

    /// Erase planning for AbbreviationMatcher results under DevType swallow.
    public static func eraseCountForMatch(
        triggerUTF16Length: Int,
        terminator: String,
        swallowedFinalKey: Bool,
        lastEventCharacterCount: Int = 1
    ) -> Int {
        EraseExecutor.eraseCountForMatch(
            triggerUTF16Length: triggerUTF16Length,
            terminator: terminator,
            swallowedFinalKey: swallowedFinalKey,
            lastEventCharacterCount: lastEventCharacterCount
        )
    }

    /// Reads the focused field and decides whether the erase described by `plan` is safe to run.
    /// §8.3: the retry is now off-main only here — main-thread callers should use `EraseExecutor`'s
    /// asynchronous form, which retries without blocking anything.
    public func evaluateErasePrecondition(
        plan: ErasePlan,
        element: AXUIElement? = nil,
        retryOnMismatch: Bool = true
    ) -> ErasePreconditionResult {
        eraser.evaluateErasePrecondition(
            plan: plan,
            element: element,
            retryOnMismatch: retryOnMismatch
        )
    }

    /// Bracketed paste sequence for shell-like contexts (prevents metachar execution).
    public static func bracketPastePayload(_ text: String) -> String {
        BracketedPasteCapabilityStore.bracketStart + text + BracketedPasteCapabilityStore.bracketEnd
    }

    // MARK: - Entry points

    /// Async inject on a dedicated queue. Calls `completion` only after clipboard restore settles
    /// (or immediately when no pasteboard path was used). Never blocks the event-tap run loop.
    ///
    /// §8.2: this is the legacy parameter list, kept verbatim because `EventTapEngine`,
    /// `AppDelegate` and `TestExpansionLab` call it. It forwards to the `SwallowedKey` form.
    public func inject(
        snippet: SnippetModel,
        triggerLength: Int,
        clipboardOverride: String? = nil,
        swallowedFinalKey: Bool = false,
        lastEventCharacterCount: Int = 1,
        plan: InjectionPlan? = nil,
        swallowedUnicode: String = "",
        swallowedKeyCode: Int64 = 0,
        swallowedFlags: CGEventFlags = [],
        terminator: String = "",
        eraseCountOverride: Int? = nil,
        erasePlan: ErasePlan? = nil,
        preResolvedText: String? = nil,
        preResolvedCursorOffset: Int? = nil,
        trailingKeys: [String] = [],
        snippetLookup: ((String) -> String?)? = nil,
        secureClipboardPaste: Bool = false,
        completion: (() -> Void)? = nil
    ) {
        inject(
            snippet: snippet,
            triggerLength: triggerLength,
            swallowed: SwallowedKey(
                didSwallow: swallowedFinalKey,
                unicode: swallowedUnicode,
                keyCode: swallowedKeyCode,
                flags: swallowedFlags
            ),
            clipboardOverride: clipboardOverride,
            lastEventCharacterCount: lastEventCharacterCount,
            plan: plan,
            terminator: terminator,
            eraseCountOverride: eraseCountOverride,
            erasePlan: erasePlan,
            preResolvedText: preResolvedText,
            preResolvedCursorOffset: preResolvedCursorOffset,
            trailingKeys: trailingKeys,
            snippetLookup: snippetLookup,
            secureClipboardPaste: secureClipboardPaste,
            completion: completion
        )
    }

    /// §8.2: the collapsed form. Identical semantics; `swallowed` replaces four parameters.
    public func inject(
        snippet: SnippetModel,
        triggerLength: Int,
        swallowed: SwallowedKey,
        clipboardOverride: String? = nil,
        lastEventCharacterCount: Int = 1,
        plan: InjectionPlan? = nil,
        terminator: String = "",
        eraseCountOverride: Int? = nil,
        erasePlan: ErasePlan? = nil,
        preResolvedText: String? = nil,
        preResolvedCursorOffset: Int? = nil,
        trailingKeys: [String] = [],
        snippetLookup: ((String) -> String?)? = nil,
        secureClipboardPaste: Bool = false,
        completion: (() -> Void)? = nil
    ) {
        injectQueue.async {
            // Prefer the fully-specified plan. Fall back to count-only planning for callers that
            // cannot supply the matched text (tests, Test Expansion Lab, physical Hangul overrides);
            // those degrade to `.unavailable` in the precondition guard rather than blocking.
            let resolvedPlan: ErasePlan
            if let erasePlan {
                resolvedPlan = erasePlan
            } else if let eraseCountOverride {
                resolvedPlan = .counted(eraseCountOverride)
            } else {
                resolvedPlan = .counted(
                    TextInjectionPipeline.eraseCountForMatch(
                        triggerUTF16Length: triggerLength,
                        terminator: terminator,
                        swallowedFinalKey: swallowed.didSwallow,
                        lastEventCharacterCount: lastEventCharacterCount
                    )
                )
            }

            // §1.3: `injectQueue` is serial and `group.wait()` had no timeout. One inject path that
            // failed to call its completion — most plausibly the fill-in panel being closed by
            // another route — blocked this queue forever *and* left `EventTapEngine._isExpanding`
            // set, so every keystroke was passed straight through. DevType stopped expanding until
            // relaunch, silently, with no log line. Both halves are now bounded and logged.
            let group = DispatchGroup()
            let completionGuard = InjectCompletionGuard()
            group.enter()

            DispatchQueue.main.async {
                self.injectOnMain(
                    snippet: snippet,
                    erasePlan: resolvedPlan,
                    clipboardOverride: clipboardOverride,
                    plan: plan,
                    swallowed: swallowed,
                    preResolvedText: preResolvedText,
                    preResolvedCursorOffset: preResolvedCursorOffset,
                    trailingKeys: trailingKeys,
                    snippetLookup: snippetLookup,
                    secureClipboardPaste: secureClipboardPaste
                ) {
                    let invocation = completionGuard.markCompleted()
                    if invocation == 1 {
                        group.leave()
                    } else {
                        // §1.3: the other way a completion corrupts this queue — leaving a
                        // DispatchGroup twice traps, so this must be caught rather than forwarded.
                        DevTypeLog.inject.error(
                            "[Inject] §1.3 inject completion invoked \(invocation, privacy: .public)× — ignoring the duplicate (an inject path is calling completion on more than one exit)"
                        )
                    }
                    if completionGuard.didTimeOut {
                        DevTypeLog.inject.error(
                            "[Inject] §1.3 inject completed after the watchdog already fired — expansion state was force-cleared"
                        )
                    }
                }
            }

            if group.wait(timeout: .now() + InjectTiming.injectCompletionTimeout) == .timedOut {
                completionGuard.markTimedOut()
                DevTypeLog.inject.error(
                    "[Inject] §1.3 watchdog: inject did not complete within \(InjectTiming.injectCompletionTimeout, privacy: .public)s — releasing the inject queue and force-clearing expansion state"
                )
                PermissionCoordinator.shared.recordInjectOutcome(
                    .failedSilent,
                    refuseContext: nil,
                    path: "watchdogTimeout"
                )
            }
            // Runs on either exit: the caller's completion is what clears `isExpanding`, so it must
            // not be conditional on the inject having finished.
            completion?()
        }
    }

    /// Restores a swallowed trigger key after refuse. Prefers HID post; falls back to AX insert.
    /// Call while `EventTapEngine.isExpanding` so the tap does not rematch the reinjected key.
    @discardableResult
    public func reinjectSwallowedKey(
        unicode: String,
        keyCode: Int64,
        flags: CGEventFlags
    ) -> Bool {
        reinjectSwallowedKey(
            SwallowedKey(didSwallow: true, unicode: unicode, keyCode: keyCode, flags: flags)
        )
    }

    /// §8.2: `SwallowedKey` form of the above.
    @discardableResult
    public func reinjectSwallowedKey(_ swallowed: SwallowedKey) -> Bool {
        guard swallowed.hasPayload else { return false }

        if CGPreflightPostEventAccess() {
            if hid.postUnicodeKeyEvent(
                unicode: swallowed.unicode,
                keyCode: CGKeyCode(truncatingIfNeeded: swallowed.keyCode),
                flags: swallowed.flags
            ) {
                return true
            }
        }

        // AX-only hosts: insert the swallowed character at the caret (no Post Events).
        if !swallowed.unicode.isEmpty {
            return ax.attemptAXDirectInjection(text: swallowed.unicode)
        }
        return false
    }

    // MARK: - §3.1 Undo

    /// The last delivered expansion, if any. Cleared by a successful undo.
    public var lastExpansion: LastExpansion? {
        lastExpansionLock.withLock { _lastExpansion }
    }

    /// True when `undoLastExpansion()` would do something right now.
    public func canUndoLastExpansion(now: Date = Date()) -> Bool {
        guard let record = lastExpansion, record.isFresh(now: now) else { return false }
        guard let recorded = record.bundleID,
              let current = EventTapEngine.shared.cachedFrontmostBundleID else { return true }
        return recorded == current
    }

    /// §3.1: revert the last expansion — erase what was injected and put the trigger back.
    ///
    /// Returns `true` when an undo was accepted and started (the erase itself is asynchronous and
    /// still runs behind the erase precondition guard, so a user who typed more text after the
    /// expansion gets a refusal rather than a destroyed field). Returns `false` when there is
    /// nothing to undo, the record has aged out of `InjectTiming.undoExpansionWindow`, or focus has
    /// moved to a different app.
    ///
    /// Single-shot: the record is consumed whether or not the erase ultimately succeeds, so a held
    /// backspace cannot walk backwards through the document.
    ///
    /// Keystroke detection is deliberately **not** wired here — `EventTapEngine` owns that decision
    /// and this is the API it should call from its backspace handling.
    @discardableResult
    public func undoLastExpansion(now: Date = Date()) -> Bool {
        lastExpansionLock.lock()
        guard let record = _lastExpansion, record.isFresh(now: now) else {
            lastExpansionLock.unlock()
            return false
        }
        _lastExpansion = nil
        lastExpansionLock.unlock()

        if let recorded = record.bundleID,
           let current = EventTapEngine.shared.cachedFrontmostBundleID,
           recorded != current {
            DevTypeLog.inject.notice(
                "[Inject] §3.1 undo skipped — expansion happened in \(recorded, privacy: .public), frontmost is now \(current, privacy: .public)"
            )
            return false
        }

        if Thread.isMainThread {
            performUndo(record)
        } else {
            DispatchQueue.main.async { self.performUndo(record) }
        }
        return true
    }

    /// Forget the last expansion (e.g. the user moved the caret, so undo would be destructive).
    public func clearLastExpansion() {
        lastExpansionLock.lock()
        _lastExpansion = nil
        lastExpansionLock.unlock()
    }

    /// Forget the last expansion only if it is the one that injected `text` — used by the deferred
    /// paste re-verification, which must not discard a newer expansion's undo point.
    public func clearLastExpansion(ifInjectedTextIs text: String) {
        lastExpansionLock.lock()
        if _lastExpansion?.injectedText == text {
            _lastExpansion = nil
        }
        lastExpansionLock.unlock()
    }

    /// Characters the user may type after an expansion and still have undo work. Bounded so a
    /// stale record can never authorise erasing an unbounded amount of text.
    static let undoMaxTypedAfter = 16

    /// Widens the undo to cover text typed *after* the expansion.
    ///
    /// The naive plan erases exactly `injectedText` from the caret backwards, which assumes the
    /// caret is still where injection left it. Type one more character and the window shifts:
    /// for an injected "ScholarLM" followed by a typed "l", the check reads "cholarLMl" and
    /// refuses. Correct (erasing there would eat the wrong nine characters and strand an "S"),
    /// but the user's undo silently does nothing.
    ///
    /// So locate the injected text at its real offset, allowing up to `undoMaxTypedAfter`
    /// trailing characters, and undo the whole span — restoring the trigger *plus* what was
    /// typed after it, which is exactly what the field would hold had the expansion never run.
    ///
    /// Returns `nil` when the field is unreadable or the injected text is not found, leaving the
    /// caller on the original fail-closed path.
    static func widenedUndo(
        injectedText: String,
        triggerText: String,
        value: String?,
        caretLocation: Int?,
        maxTypedAfter: Int = undoMaxTypedAfter
    ) -> (plan: ErasePlan, restore: String)? {
        guard let value, let caret = caretLocation, caret >= 0 else { return nil }
        let units = Array(value.utf16)
        guard caret <= units.count else { return nil }
        let injected = Array(injectedText.utf16)
        guard !injected.isEmpty else { return nil }

        // k == 0 is the untouched case and is handled by the normal plan; start at 1.
        for k in 1...max(1, maxTypedAfter) {
            let end = caret - k
            let start = end - injected.count
            guard start >= 0, end <= units.count else { break }
            guard Array(units[start..<end]) == injected else { continue }

            let tailSlice = Array(units[end..<caret])
            let typedAfter = String(utf16CodeUnits: tailSlice, count: tailSlice.count)
            // A newline may have submitted a form or moved focus; the text after it is not
            // safely ours to re-type.
            guard !typedAfter.contains(where: \.isNewline) else { return nil }
            return (
                plan: ErasePlan(text: injectedText + typedAfter),
                restore: triggerText + typedAfter
            )
        }
        return nil
    }

    /// Reads AXValue + caret for `widenedUndo`. Returns `(nil, nil)` when unreadable.
    private func readFieldForUndo() -> (value: String?, caret: Int?) {
        guard let element = AXContextChecker.shared.focusedElement() else { return (nil, nil) }
        AXContextChecker.applyMessagingTimeout(to: element)

        var value: String?
        var valueRef: CFTypeRef?
        if AXUIElementCopyAttributeValue(element, kAXValueAttribute as CFString, &valueRef) == .success {
            value = valueRef as? String
        }
        var caret: Int?
        var rangeRef: CFTypeRef?
        if AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &rangeRef) == .success,
           let rangeValue = rangeRef,
           CFGetTypeID(rangeValue) == AXValueGetTypeID() {
            var range = CFRange(location: 0, length: 0)
            if AXValueGetValue(unsafeBitCast(rangeValue, to: AXValue.self), .cfRange, &range) {
                caret = range.location
            }
        }
        return (value, caret)
    }

    private func performUndo(_ record: LastExpansion) {
        var undoPlan = ErasePlan(text: record.injectedText)
        var restoreText = record.triggerText

        // If the plain plan would not verify, try widening over text typed since the expansion
        // before giving up. Only ever widens on a positive match of the injected text.
        if case .mismatch = eraser.evaluateErasePrecondition(plan: undoPlan, retryOnMismatch: false) {
            let field = readFieldForUndo()
            if let widened = Self.widenedUndo(
                injectedText: record.injectedText,
                triggerText: record.triggerText,
                value: field.value,
                caretLocation: field.caret
            ) {
                DevTypeLog.inject.info(
                    "[Inject] §3.1 undo widened over \(widened.plan.utf16Count - undoPlan.utf16Count, privacy: .public) unit(s) typed after the expansion"
                )
                undoPlan = widened.plan
                restoreText = widened.restore
            }
        }
        eraser.evaluateErasePrecondition(plan: undoPlan) { result in
            if case .mismatch(let why) = result {
                DevTypeLog.inject.notice(
                    "[Inject] §3.1 undo refused — \(why, privacy: .public)"
                )
                PermissionCoordinator.shared.recordInjectOutcome(
                    .refused("Undo refused — \(why)"),
                    refuseContext: nil,
                    path: "undo"
                )
                return
            }

            // One transactional AX replace is the cleanest undo: no backspaces, no clipboard.
            let bundle = record.bundleID ?? ""
            var undoWriteMayHaveMutated = false
            if !bundle.isEmpty, !TextInjectionPipeline.shouldSkipAXSelectedText(bundleID: bundle) {
                let undoOutcome = self.ax.performAXRangeReplace(
                    text: restoreText,
                    eraseCount: undoPlan.utf16Count,
                    bundleID: record.bundleID
                )
                if undoOutcome == .replaced {
                    DevTypeLog.inject.info("[Inject] §3.1 undo via AX range replace")
                    PermissionCoordinator.shared.recordInjectOutcome(
                        .succeeded,
                        refuseContext: nil,
                        path: "undoAXRange"
                    )
                    return
                }
                // Same provenance rule as the expand path: only a write that actually reached
                // the field makes unverifiable state a reason to abort the HID fallback.
                undoWriteMayHaveMutated = undoOutcome.fieldMayHaveMutated
            }

            // HID fallback: the guarded erase re-verifies that the injected text is still sitting
            // left of the caret before a single backspace is posted.
            self.eraser.performGuardedErase(
                plan: undoPlan,
                afterPossibleWrite: undoWriteMayHaveMutated
            ) { erased in
                guard erased else {
                    DevTypeLog.inject.notice(
                        "[Inject] §3.1 undo aborted — field no longer holds the injected text"
                    )
                    PermissionCoordinator.shared.recordInjectOutcome(
                        .refused("Undo aborted — field no longer holds the injected text"),
                        refuseContext: nil,
                        path: "undo"
                    )
                    return
                }
                if self.ax.attemptAXDirectInjection(
                    text: restoreText,
                    bundleID: record.bundleID
                ) {
                    PermissionCoordinator.shared.recordInjectOutcome(
                        .succeeded,
                        refuseContext: nil,
                        path: "undoAXDirect"
                    )
                    return
                }
                self.clipboard.pasteViaClipboard(text: restoreText) { posted in
                    PermissionCoordinator.shared.recordInjectOutcome(
                        posted ? .succeeded : .failedSilent,
                        refuseContext: nil,
                        path: "undoPaste"
                    )
                }
            }
        }
    }

    // MARK: - Inject (main thread)

    /// Everything the main-thread inject needs after the gates have passed. §8.2: bundling these
    /// keeps the post-precondition continuation to one parameter instead of eleven.
    private struct InjectContext {
        let snippet: SnippetModel
        let erasePlan: ErasePlan
        let clipboardOverride: String?
        let plan: InjectionPlan?
        let swallowed: SwallowedKey
        let preResolvedText: String?
        let preResolvedCursorOffset: Int?
        let trailingKeys: [String]
        let snippetLookup: ((String) -> String?)?
        let snapshot: PermissionSnapshot
        /// Keep the optional: a bundle-less frontmost app must not be learned under the literal
        /// key "nil", which would then disable AX writes for every other bundle-less app.
        let frontBundleID: String?

        var frontBundle: String { frontBundleID ?? "nil" }
    }

    private func injectOnMain(
        snippet: SnippetModel,
        erasePlan: ErasePlan,
        clipboardOverride: String?,
        plan: InjectionPlan?,
        swallowed: SwallowedKey,
        preResolvedText: String?,
        preResolvedCursorOffset: Int?,
        trailingKeys: [String],
        snippetLookup: ((String) -> String?)?,
        secureClipboardPaste: Bool,
        completion: @escaping () -> Void
    ) {
        // Re-check Secure Input / IME / focus at inject time (may have changed since match).
        let snapshot = PermissionCoordinator.shared.cachedSnapshot

        // Probe IME only when focus is available — missing focus stays non-IME for the
        // explicit secure-clipboard intent (Chrome password fields often expose no AX focus).
        var hasIME = false
        if snapshot.canUseAX,
           AXContextChecker.shared.isProcessTrusted(),
           case .available(let element) = AXContextChecker.shared.queryFocusedElement() {
            hasIME = AXContextChecker.shared.hasActiveIMEMarkedText(element: element)
        }

        let allowSecureClipboard = AXContextChecker.mayAllowSecureClipboardPaste(
            intent: secureClipboardPaste,
            canPostEvents: snapshot.canPostEvents,
            eraseEmpty: erasePlan.isEmpty,
            hasIME: hasIME
        )

        if allowSecureClipboard {
            injectSecureClipboardPasteOnMain(
                snippet: snippet,
                clipboardOverride: clipboardOverride,
                swallowed: swallowed,
                preResolvedText: preResolvedText,
                trailingKeys: trailingKeys,
                snippetLookup: snippetLookup,
                completion: completion
            )
            return
        }

        if AXContextChecker.isSecureEventInputEnabledLive() {
            let decision = AXContextChecker.shared.evaluateExpandGate(
                canUseAX: snapshot.canUseAX,
                canPostEvents: snapshot.canPostEvents
            )
            refuseInject(
                AXContextChecker.secureInputActiveReason,
                path: "gateSecureInput",
                swallowed: swallowed,
                refuseContext: .capture(
                    reason: AXContextChecker.secureInputActiveReason,
                    decision: decision
                ),
                completion: completion
            )
            return
        }

        let decision = AXContextChecker.shared.evaluateExpandGate(
            canUseAX: snapshot.canUseAX,
            canPostEvents: snapshot.canPostEvents
        )
        let frontBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        let frontBundle = frontBundleID ?? "nil"
        // #region agent log
        TextInjectionPipeline.debugLogInject(
            hypothesisId: "M1",
            message: "injectOnMain gate",
            data: [
                "frontmostBundle": frontBundle,
                "shouldBlock": decision.shouldBlock,
                "reason": decision.reason,
                "focusedAvailable": decision.snapshot.focusedAvailable,
                "isSecure": decision.snapshot.isSecureField.map { $0 ? "true" : "false" } ?? "nil",
                "hasIME": decision.snapshot.hasIMEMarkedText.map { $0 ? "true" : "false" } ?? "nil",
                "eraseUTF16": erasePlan.utf16Count,
                "eraseBackspaces": erasePlan.backspaceCount,
                "triggerLen": snippet.triggerKeyword.utf16.count,
                "textLen": (preResolvedText ?? snippet.replacementText).utf16.count
            ]
        )
        // #endregion
        if decision.shouldBlock {
            refuseInject(
                decision.reason,
                path: "gateBlocked",
                swallowed: swallowed,
                refuseContext: .capture(reason: decision.reason, decision: decision),
                completion: completion
            )
            return
        }

        let context = InjectContext(
            snippet: snippet,
            erasePlan: erasePlan,
            clipboardOverride: clipboardOverride,
            plan: plan,
            swallowed: swallowed,
            preResolvedText: preResolvedText,
            preResolvedCursorOffset: preResolvedCursorOffset,
            trailingKeys: trailingKeys,
            snippetLookup: snippetLookup,
            snapshot: snapshot,
            frontBundleID: frontBundleID
        )

        // Backstop before anything destructive: if AX can read the field, the trigger must actually
        // be sitting left of the caret. A mismatch means our model of the field is wrong, and
        // erasing would eat the user's own text — refuse instead.
        //
        // §8.3: asynchronous, so the one-shot retry is available here (on main) without a 30 ms
        // `Thread.sleep` that would stall the event tap.
        eraser.evaluateErasePrecondition(plan: erasePlan) { eraseCheck in
            // #region agent log
            if eraseCheck != .ok {
                let label: String
                switch eraseCheck {
                case .ok: label = "ok"
                case .unavailable(let why): label = "unavailable: \(why)"
                case .mismatch(let why): label = "mismatch: \(why)"
                }
                TextInjectionPipeline.debugLogInject(
                    hypothesisId: "M5",
                    message: "erase precondition",
                    data: [
                        "frontmostBundle": frontBundle,
                        "result": label,
                        "eraseUTF16": erasePlan.utf16Count,
                        "hasExpectedText": erasePlan.expectedText != nil
                    ]
                )
            }
            // #endregion
            if case .mismatch(let why) = eraseCheck {
                DevTypeLog.inject.error(
                    "[Inject] erase precondition failed — \(why, privacy: .public)"
                )
                self.refuseInject(
                    "Erase precondition failed — \(why)",
                    path: "erasePrecondition",
                    swallowed: swallowed,
                    completion: completion
                )
                return
            }
            self.performInject(context: context, completion: completion)
        }
    }

    private func performInject(context: InjectContext, completion: @escaping () -> Void) {
        let swallowed = context.swallowed
        let erasePlan = context.erasePlan
        let frontBundle = context.frontBundle

        // Image snippets bypass all text/AX paths: erase the trigger with HID
        // backspaces, then paste the image through the clipboard.
        if context.snippet.isImageSnippet {
            guard CGPreflightPostEventAccess() else {
                refuseInject(
                    "Image expansion requires Post Events (clipboard paste)",
                    path: "imagePaste",
                    swallowed: swallowed,
                    completion: completion
                )
                return
            }
            guard let image = ImageAttachmentStore.shared.loadImage(path: context.snippet.imagePath) else {
                refuseInject(
                    "Image attachment missing or unreadable: \(context.snippet.imagePath)",
                    path: "imagePaste",
                    swallowed: swallowed,
                    completion: completion
                )
                return
            }
            eraser.performGuardedErase(plan: erasePlan) { erased in
                guard erased else {
                    self.refuseInject(
                        "Erase precondition failed before image paste — field no longer holds the trigger",
                        path: "imagePaste",
                        swallowed: swallowed,
                        completion: completion
                    )
                    return
                }
                self.clipboard.pasteImageViaClipboard(
                    image: image,
                    bundleID: context.frontBundleID
                ) { result in
                    // §3.4: the image path now reports what it actually observed instead of
                    // "posted, therefore succeeded".
                    let outcome: PermissionCoordinator.InjectOutcome
                    switch result {
                    case .delivered:
                        outcome = .succeeded
                    case .unavailable:
                        outcome = .postedUnverified
                    case .notPosted, .failed:
                        outcome = .failedSilent
                    }
                    PermissionCoordinator.shared.recordInjectOutcome(
                        outcome,
                        refuseContext: nil,
                        path: "imagePaste"
                    )
                    completion()
                }
            }
            return
        }

        let shellLike = AXContextChecker.shared.isFrontmostShellLikeContext()
        // Snapshot clipboard before any paste mutate when macros need it.
        let clipboardArg = context.clipboardOverride.map { DynamicTemplateEngine.sanitizeClipboardText($0) }
        let cursorOffset: Int?
        let textToInject: String
        let keysToPress: [String]
        if let preResolvedText = context.preResolvedText {
            textToInject = preResolvedText
            cursorOffset = context.preResolvedCursorOffset
            keysToPress = context.trailingKeys
        } else {
            let lookup = context.snippetLookup ?? { _ in nil }
            let expanded = MacroRenderer.expand(
                content: context.snippet.replacementText,
                fillValues: [:],
                lookup: lookup,
                clipboardText: clipboardArg
            )
            if expanded.needsFillIn {
                refuseInject(
                    "Fill-in required — present FillInPanel before inject",
                    path: "fillInRequired",
                    swallowed: swallowed,
                    completion: completion
                )
                return
            }
            textToInject = expanded.text
            cursorOffset = expanded.cursorOffset
            keysToPress = expanded.trailingKeys
        }
        let totalUTF16 = textToInject.utf16.count
        let needsCursor = InjectionPlanner.needsCursorHID(
            cursorOffset: cursorOffset,
            totalUTF16Length: totalUTF16
        )
        let isMultiLine = textToInject.contains(where: \.isNewline)

        let effectivePlan = context.plan ?? planner.plan(
            snapshot: context.snapshot,
            isTerminal: shellLike,
            needsCursorHID: needsCursor,
            isMultiLine: isMultiLine
        )

        // Shell-like + multi-line without Post: refuse (planner should already catch this).
        if shellLike, isMultiLine, !context.snapshot.canPostEvents {
            refuseInject(
                "Multi-line shell inject requires Post Events (bracket paste)",
                path: "shellNoPostEvents",
                swallowed: swallowed,
                completion: completion
            )
            return
        }

        // #region agent log
        let planLabel: String
        switch effectivePlan {
        case .refuse: planLabel = "refuse"
        case .axOnly: planLabel = "axOnly"
        case .axPlusHID: planLabel = "axPlusHID"
        }
        TextInjectionPipeline.debugLogInject(
            hypothesisId: "M2",
            message: "injectOnMain plan",
            data: [
                "frontmostBundle": frontBundle,
                "shellLike": shellLike,
                "plan": planLabel,
                "isMultiLine": isMultiLine,
                "eraseUTF16": erasePlan.utf16Count,
                "eraseBackspaces": erasePlan.backspaceCount
            ]
        )
        // #endregion

        // Skip the AX selected-text write when this app/role is known — seeded, learned this
        // session, or persisted from an earlier launch — to report success without mutating.
        // Role-aware: WhatsApp's AXTextArea can be condemned without affecting other roles.
        let focusedRole = AXContextChecker.shared.focusedElementRole()
        var preferHID = TextInjectionPipeline.shouldSkipAXSelectedText(
            bundleID: frontBundle,
            role: focusedRole
        )
        // #region agent log
        if preferHID {
            TextInjectionPipeline.debugLogInject(
                hypothesisId: "M3",
                message: "skip AX range — weak selected-text app",
                data: [
                    "frontmostBundle": frontBundle,
                    "preferHID": true,
                    "role": focusedRole ?? ""
                ]
            )
        }
        // #endregion

        switch effectivePlan {
        case .refuse(let reason):
            refuseInject(
                reason,
                path: "plannerRefuse",
                swallowed: swallowed,
                completion: completion
            )
            return

        case .axOnly:
            // AX only — no HID. Range replace + optional AX caret; never erase-less direct inject.
            // A known-lying app has no fallback here, so this correctly refuses rather than
            // pretending the expand happened.
            let axOnlyOutcome = (shellLike || preferHID)
                ? AXReplaceOutcome.notAttempted(shellLike ? "shell-like context" : "weak AX app")
                : ax.performAXRangeReplace(
                    text: textToInject,
                    eraseCount: erasePlan.utf16Count,
                    bundleID: context.frontBundleID
                )
            if axOnlyOutcome == .replaced {
                // #region agent log
                TextInjectionPipeline.debugLogInject(
                    hypothesisId: "M3",
                    message: "inject path",
                    data: ["frontmostBundle": frontBundle, "path": "axOnlyRange", "outcome": "degradedAXOnly"]
                )
                // #endregion
                positionCursorIfNeeded(
                    text: textToInject,
                    cursorOffset: cursorOffset,
                    totalUTF16Length: totalUTF16,
                    allowHID: false
                ) {
                    self.hid.postTrailingKeys(keysToPress)
                    self.finishSucceeded(
                        outcome: .degradedAXOnly,
                        path: "axOnlyRange",
                        context: context,
                        injectedText: textToInject,
                        completion: completion
                    )
                }
                return
            }
            refuseInject(
                "AX-only inject failed — range replace required (no erase-less direct inject); Post Events needed for HID fallback",
                path: "axOnlyRange",
                swallowed: swallowed,
                completion: completion
            )
            return

        case .axPlusHID:
            break
        }

        // Tracks whether a text write actually *reached* the field. A non-`.replaced` outcome
        // does not prove nothing changed — some hosts mutate and then report a stale AXValue —
        // so the HID fallback below must not erase on unverifiable state. But the outcome's own
        // provenance decides: a `.notAttempted` return means the writer bailed before issuing
        // any write (no focused element, learned skip, unreadable range), and treating *that*
        // as "may have mutated" refused every expand in AX-opaque hosts — a Chrome PWA cannot
        // verify the field either, so the guard tripped on a write that never happened.
        var attemptedAXWrite = false
        if !shellLike, !preferHID {
            let axOutcome = ax.performAXRangeReplace(
                text: textToInject,
                eraseCount: erasePlan.utf16Count,
                bundleID: context.frontBundleID
            )
            attemptedAXWrite = axOutcome.fieldMayHaveMutated
            if axOutcome == .replaced {
                // #region agent log
                TextInjectionPipeline.debugLogInject(
                    hypothesisId: "M3",
                    message: "inject path",
                    data: ["frontmostBundle": frontBundle, "path": "axRange", "outcome": "succeeded"]
                )
                // #endregion
                positionCursorIfNeeded(
                    text: textToInject,
                    cursorOffset: cursorOffset,
                    totalUTF16Length: totalUTF16,
                    allowHID: true
                ) {
                    self.hid.postTrailingKeys(keysToPress)
                    self.finishSucceeded(
                        outcome: .succeeded,
                        path: "axRange",
                        context: context,
                        injectedText: textToInject,
                        completion: completion
                    )
                }
                return
            }
            // Range replace did not apply. If this call just condemned the control (falseSuccess)
            // or the role was already marked weak, skip AX direct after erase — that path can
            // report succeeded after deleting the trigger when verification is unverifiable.
            if case .falseSuccess = axOutcome {
                preferHID = true
            } else if TextInjectionPipeline.shouldSkipAXSelectedText(
                bundleID: frontBundle,
                role: focusedRole
            ) {
                preferHID = true
            }
        }

        // Fallback: HID backspaces then AX set or paste.
        // The guarded erase collapses any stray selection and re-verifies the trigger is still left
        // of the caret, so a half-applied AX edit above cannot be swallowed by backspace #1 and turn
        // the remaining backspaces loose on the user's text.
        eraser.performGuardedErase(
            plan: erasePlan,
            afterPossibleWrite: attemptedAXWrite,
            onUnverifiableAfterWrite: { why in
                // Self-healing: an attempted AX write left the field unreadable even after the
                // settle retry — the Chromium/Electron signature (a fresh web-app shell hits
                // this on its very first expansion). Strikes escalate rather than condemn
                // outright: a transient (focus stolen mid-inject) looks identical on one
                // observation, and a wrong condemnation is effectively permanent. The second
                // strike condemns, so a genuinely broken shell heals on the user's next retry
                // and every expansion after that skips the AX write for the HID paste path.
                // `.mismatch` never reaches here, so a moved caret cannot strike a healthy app.
                guard let bundleID = context.frontBundleID, !bundleID.isEmpty else { return }
                switch AXWriteCapabilityStore.shared.recordUnverifiableAfterWrite(
                    bundleID: bundleID,
                    role: focusedRole
                ) {
                case .struck(let count):
                    DevTypeLog.inject.notice(
                        "[Inject] unverifiable after AX write (\(why, privacy: .public)) — strike \(count, privacy: .public)/\(AXWriteCapabilityStore.unverifiableStrikesToCondemn, privacy: .public) for \(bundleID, privacy: .public)"
                    )
                case .condemned:
                    DevTypeLog.inject.notice(
                        "[Inject] unverifiable after AX write (\(why, privacy: .public)) — verdict learned for \(bundleID, privacy: .public); this expansion is refused, the next uses HID paste"
                    )
                case .alreadyCondemned:
                    break
                }
            }
        ) { erased in
            guard erased else {
                self.refuseInject(
                    "Erase precondition failed before paste — field no longer holds the trigger",
                    path: "guardedErase",
                    swallowed: swallowed,
                    completion: completion
                )
                return
            }
            if shellLike {
                // Bracket paste for terminals / IDE shells — refuse multi-line only handled above.
                // Verify against the unbracketed text (hosts strip OSC 200/201); hold clipboard until
                // AX confirms, retries once on confirmed miss, or hold timeout (unverified).
                //
                // §3.10: no longer unconditional. A host that has been observed echoing the literal
                // markers gets a plain paste instead — the escapes are only a defence against a
                // pasted newline executing, and a host that shows them is not parsing them.
                let shouldBracket = self.bracketedPaste.shouldBracketPaste(bundleID: context.frontBundleID)
                let payload = shouldBracket ? TextInjectionPipeline.bracketPastePayload(textToInject) : textToInject
                let hidPasteBaseline = self.verifier.captureFocusedTextObservation()
                self.clipboard.pasteViaClipboard(
                    text: payload,
                    expectedText: textToInject,
                    baseline: hidPasteBaseline,
                    bundleID: context.frontBundleID,
                    focusedRole: focusedRole,
                    staleProbe: erasePlan.expectedText,
                    staleProbeCaseInsensitive: erasePlan.caseInsensitive
                ) { result in
                    // #region agent log
                    TextInjectionPipeline.debugLogInject(
                        hypothesisId: "M4",
                        message: "inject path",
                        data: [
                            "frontmostBundle": frontBundle,
                            "path": "shellBracketPaste",
                            "bracketed": shouldBracket,
                            "result": TextInjectionPipeline.pasteResultLabel(result)
                        ]
                    )
                    // #endregion
                    if shouldBracket {
                        // §3.10: learn from what the field actually shows. AX-opaque terminals
                        // teach nothing and stay on the safe default.
                        self.bracketedPaste.learn(
                            fromObservedValue: self.verifier.captureFocusedTextObservation()?.value,
                            bundleID: context.frontBundleID
                        )
                    }
                    self.finishPasteDelivery(
                        result: result,
                        expectedText: textToInject,
                        baseline: hidPasteBaseline,
                        context: context,
                        focusedRole: focusedRole,
                        path: "shellBracketPaste",
                        cursorOffset: cursorOffset,
                        totalUTF16Length: totalUTF16,
                        trailingKeys: keysToPress,
                        completion: completion
                    )
                }
                return
            }

            // Weak-AX apps: skip direct AX set (same false-success class as range replace).
            if !preferHID,
               self.ax.attemptAXDirectInjection(
                   text: textToInject,
                   bundleID: context.frontBundleID
               ) {
                // #region agent log
                TextInjectionPipeline.debugLogInject(
                    hypothesisId: "M3",
                    message: "inject path",
                    data: ["frontmostBundle": frontBundle, "path": "axDirect", "outcome": "succeeded"]
                )
                // #endregion
                self.positionCursorIfNeeded(
                    text: textToInject,
                    cursorOffset: cursorOffset,
                    totalUTF16Length: totalUTF16,
                    allowHID: true
                ) {
                    self.hid.postTrailingKeys(keysToPress)
                    self.finishSucceeded(
                        outcome: .succeeded,
                        path: "axDirect",
                        context: context,
                        injectedText: textToInject,
                        completion: completion
                    )
                }
                return
            }

            let hidPasteBaseline = self.verifier.captureFocusedTextObservation()
            self.clipboard.pasteViaClipboard(
                text: textToInject,
                expectedText: textToInject,
                baseline: hidPasteBaseline,
                bundleID: context.frontBundleID,
                focusedRole: focusedRole,
                staleProbe: erasePlan.expectedText,
                staleProbeCaseInsensitive: erasePlan.caseInsensitive
            ) { result in
                // #region agent log
                TextInjectionPipeline.debugLogInject(
                    hypothesisId: "M4",
                    message: "inject path",
                    data: [
                        "frontmostBundle": frontBundle,
                        "path": "hidPaste",
                        "result": TextInjectionPipeline.pasteResultLabel(result)
                    ]
                )
                // #endregion
                self.finishPasteDelivery(
                    result: result,
                    expectedText: textToInject,
                    baseline: hidPasteBaseline,
                    context: context,
                    focusedRole: focusedRole,
                    path: "hidPaste",
                    cursorOffset: cursorOffset,
                    totalUTF16Length: totalUTF16,
                    trailingKeys: keysToPress,
                    completion: completion
                )
            }
        }
    }

    /// Explicit Inline Search / hotkey path: HID clipboard Cmd+V only (never AX).
    /// Bypasses live Secure Input, secure-field, and missing-focus-under-SI refuses.
    private func injectSecureClipboardPasteOnMain(
        snippet: SnippetModel,
        clipboardOverride: String?,
        swallowed: SwallowedKey,
        preResolvedText: String?,
        trailingKeys: [String],
        snippetLookup: ((String) -> String?)?,
        completion: @escaping () -> Void
    ) {
        if snippet.isImageSnippet {
            refuseInject(
                "Secure clipboard paste does not support image snippets",
                path: "secureClipboardPaste",
                swallowed: swallowed,
                completion: completion
            )
            return
        }

        let clipboardArg = clipboardOverride.map { DynamicTemplateEngine.sanitizeClipboardText($0) }
        let textToInject: String
        let keysToPress: [String]
        if let preResolvedText {
            textToInject = preResolvedText
            keysToPress = trailingKeys
        } else {
            let lookup = snippetLookup ?? { _ in nil }
            let expanded = MacroRenderer.expand(
                content: snippet.replacementText,
                fillValues: [:],
                lookup: lookup,
                clipboardText: clipboardArg
            )
            if expanded.needsFillIn {
                refuseInject(
                    "Fill-in required — present FillInPanel before inject",
                    path: "secureClipboardPaste",
                    swallowed: swallowed,
                    completion: completion
                )
                return
            }
            textToInject = expanded.text
            keysToPress = expanded.trailingKeys
        }

        let underSecureInput = AXContextChecker.isSecureEventInputEnabledLive()
        let frontBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        let frontBundle = frontBundleID ?? "nil"
        // #region agent log
        TextInjectionPipeline.debugLogInject(
            hypothesisId: "M4",
            message: "inject path",
            data: [
                "frontmostBundle": frontBundle,
                "path": "secureClipboardPaste",
                "underSecureInput": underSecureInput,
                "textLen": textToInject.utf16.count
            ]
        )
        // #endregion

        // No AX verification for password fields (often unreadable). Longer hold under SI so
        // the user can press ⌘V if synthetic paste is dropped.
        //
        // §1.7: `completeBeforeRestore` releases the inject queue while our payload is still on the
        // pasteboard for up to `secureClipboardPasteHoldTimeout`. That is deliberate — the user may
        // need to press ⌘V themselves — and it is safe only because `PasteboardBroker` now tracks
        // ownership: the next expansion inherits this pending restore instead of snapshotting our
        // concealed payload as if it were the user's clipboard.
        clipboard.pasteViaClipboard(
            text: textToInject,
            expectedText: nil,
            baseline: nil,
            bundleID: frontBundleID,
            leaveClipboardOnFailure: underSecureInput,
            holdTimeoutOverride: underSecureInput ? TextInjectionPipeline.secureClipboardPasteHoldTimeout : nil,
            completeBeforeRestore: true
        ) { result in
            switch result {
            case .delivered:
                self.hid.postTrailingKeys(keysToPress)
                PermissionCoordinator.shared.recordInjectOutcome(
                    .succeeded,
                    refuseContext: nil,
                    path: "secureClipboardPaste"
                )
                completion()

            case .unavailable:
                // Cmd+V posted; password fields usually cannot confirm via AX.
                self.hid.postTrailingKeys(keysToPress)
                PermissionCoordinator.shared.recordInjectOutcome(
                    .postedUnverified,
                    refuseContext: nil,
                    path: "secureClipboardPaste"
                )
                completion()

            case .notPosted, .failed:
                if underSecureInput {
                    DevTypeLog.inject.notice(
                        "[Inject] secure clipboard paste \(TextInjectionPipeline.pasteResultLabel(result), privacy: .public) under SI — leaving concealed clipboard for manual ⌘V"
                    )
                    self.notifySecureClipboardManualPaste()
                    PermissionCoordinator.shared.recordInjectOutcome(
                        .postedUnverified,
                        refuseContext: nil,
                        path: "secureClipboardPaste"
                    )
                } else {
                    DevTypeLog.inject.error(
                        "[Inject] secure clipboard paste \(TextInjectionPipeline.pasteResultLabel(result), privacy: .public)"
                    )
                    PermissionCoordinator.shared.recordInjectOutcome(
                        .failedSilent,
                        refuseContext: nil,
                        path: "secureClipboardPaste"
                    )
                }
                completion()
            }
        }
    }

    private func notifySecureClipboardManualPaste() {
        DevTypeLog.inject.notice(
            "[Inject] \(TextInjectionPipeline.secureClipboardManualPasteMessage, privacy: .public)"
        )
        onSecureClipboardManualPasteHint?()
    }

    private static func pasteResultLabel(_ result: PasteDeliveryResult) -> String {
        PasteboardBroker.label(for: result)
    }

    // MARK: - Terminal paths

    /// Records outcome, restores the erased trigger on confirmed paste failure, and finishes the expand.
    private func finishPasteDelivery(
        result: PasteDeliveryResult,
        expectedText: String,
        baseline: FocusedTextObservation?,
        context: InjectContext,
        focusedRole: String? = nil,
        path: String,
        cursorOffset: Int?,
        totalUTF16Length: Int,
        trailingKeys: [String] = [],
        completion: @escaping () -> Void
    ) {
        // §8.4 defense-in-depth: a `.failed` verdict may only drive the trigger restore when this
        // `(bundle, role)` is a proven truthful witness. The hold loop applies the same gate
        // before ever emitting `.failed`, but this function is reachable from more than one
        // broker path and the proof can be revoked mid-flight — re-check at the point of harm.
        // Suppressed failures are handled as `.unavailable`: outcome `postedUnverified`, field
        // left alone, with the deferred re-verify still able to upgrade to success.
        var result = result
        if result == .failed,
           !AXWriteCapabilityStore.shared.mayActOnDeliveryFailure(
               bundleID: context.frontBundleID,
               role: focusedRole
           ) {
            DevTypeLog.inject.notice(
                """
                [Inject] paste delivery: AX says missing but \
                \(context.frontBundleID ?? "(unknown)", privacy: .public) is not a proven delivery \
                witness — leaving the field alone (restore would duplicate)
                """
            )
            InjectTelemetryLog.shared.recordSuppressedMissVerdict(bundleID: context.frontBundleID)
            result = .unavailable
        }
        switch result {
        case .delivered:
            positionCursorIfNeeded(
                text: expectedText,
                cursorOffset: cursorOffset,
                totalUTF16Length: totalUTF16Length,
                allowHID: true
            ) {
                self.hid.postTrailingKeys(trailingKeys)
                self.finishSucceeded(
                    outcome: .succeeded,
                    path: path,
                    context: context,
                    injectedText: expectedText,
                    completion: completion
                )
            }

        case .unavailable:
            // Cmd+V posted; AX cannot confirm. Do not treat as urgent failure — common for
            // Chrome/Electron/terminals — but keep a deferred upgrade if the text appears later.
            finishSucceeded(
                outcome: .postedUnverified,
                path: path,
                context: context,
                injectedText: expectedText,
                completion: completion
            )
            DispatchQueue.main.asyncAfter(deadline: .now() + TextInjectionPipeline.pasteReverifyDelay) {
                let retry = self.verifier.verifyFocusedTextDelivery(
                    expectedText: expectedText,
                    baseline: baseline,
                    staleProbe: context.erasePlan.expectedText,
                    staleProbeCaseInsensitive: context.erasePlan.caseInsensitive
                )
                switch retry {
                case .delivered:
                    // Late confirmation upgrades the recorded outcome but deliberately does NOT
                    // record delivery-read proof: a mirror that confirms only after the hold
                    // window cannot be trusted to justify in-window corrections next time.
                    DevTypeLog.inject.info("[Inject] paste re-verify: text confirmed after settle delay")
                    PermissionCoordinator.shared.recordInjectOutcome(
                        .succeeded,
                        refuseContext: nil,
                        path: path
                    )
                case .failed where !AXWriteCapabilityStore.shared.mayActOnDeliveryFailure(
                    bundleID: context.frontBundleID,
                    role: focusedRole
                ):
                    // §8.1/§8.4: the other half of the duplicate report. The hold loop already
                    // refuses to re-paste on this app's `.failed` verdict, but this deferred
                    // re-read used to act on the very same false negative — writing the trigger
                    // back *after* an expansion that did land. This is the most dangerous restore
                    // in the pipeline (it fires ~a second after a paste that usually landed), so
                    // it demands the strongest evidence: a proven, role-matched truthful witness.
                    DevTypeLog.inject.notice(
                        """
                        [Inject] paste re-verify: AX says missing but \
                        \(context.frontBundleID ?? "(unknown)", privacy: .public) is not a proven \
                        delivery witness — leaving the field alone (restoring the trigger would duplicate)
                        """
                    )
                    InjectTelemetryLog.shared.recordSuppressedMissVerdict(bundleID: context.frontBundleID)
                case .failed:
                    // Late confirmation that paste never landed — escalate + restore trigger.
                    DevTypeLog.inject.error("[Inject] paste re-verify: AX readable but text missing — treating as failed")
                    // §3.1: the expansion did not happen, so there is nothing to undo. Matched on
                    // the injected text so a *newer* expansion's undo point is not thrown away.
                    self.clearLastExpansion(ifInjectedTextIs: expectedText)
                    self.restoreTriggerAfterFailedPaste(
                        erasePlan: context.erasePlan,
                        swallowed: context.swallowed,
                        bundleID: context.frontBundleID
                    )
                    PermissionCoordinator.shared.recordInjectOutcome(
                        .failedSilent,
                        refuseContext: nil,
                        path: path
                    )
                case .unavailable:
                    break
                }
            }

        case .notPosted, .failed:
            DevTypeLog.inject.error(
                """
                [Inject] paste delivery \(TextInjectionPipeline.pasteResultLabel(result), privacy: .public) \
                — restoring trigger (app=\(context.frontBundleID ?? "(unknown)", privacy: .public) path=\(path, privacy: .public))
                """
            )
            restoreTriggerAfterFailedPaste(
                erasePlan: context.erasePlan,
                swallowed: context.swallowed,
                bundleID: context.frontBundleID,
                countsAsDuplicateRisk: result != .notPosted
            )
            PermissionCoordinator.shared.recordInjectOutcome(
                .failedSilent,
                refuseContext: nil,
                path: path
            )
            completion()
        }
    }

    /// Best-effort: put the erased trigger back so a failed paste does not leave a hole in the field.
    ///
    /// §3.1 note: this is the same operation `undoLastExpansion` performs — the difference is only
    /// who asked for it.
    private func restoreTriggerAfterFailedPaste(
        erasePlan: ErasePlan,
        swallowed: SwallowedKey,
        bundleID: String? = nil,
        countsAsDuplicateRisk: Bool = true
    ) {
        if let text = erasePlan.expectedText, !text.isEmpty {
            // Counted, not just logged: a restore that runs after a paste which actually landed is
            // indistinguishable from a legitimate one in the outcome histogram, and both show up
            // to the user as text they did not type. `countsAsDuplicateRisk` is false only when
            // ⌘V provably never posted, where putting the trigger back cannot duplicate anything.
            if countsAsDuplicateRisk {
                InjectTelemetryLog.shared.recordTriggerRestore(bundleID: bundleID)
            }
            if ax.attemptAXDirectInjection(text: text, bundleID: nil) {
                if swallowed.mustReinjectOnRefuse {
                    _ = reinjectSwallowedKey(swallowed)
                }
                return
            }
            // AX cannot restore — clipboard paste the trigger, then reinject the swallowed key.
            clipboard.pasteViaClipboard(text: text) { _ in
                if swallowed.mustReinjectOnRefuse {
                    _ = self.reinjectSwallowedKey(swallowed)
                }
            }
            return
        }
        if swallowed.mustReinjectOnRefuse {
            _ = reinjectSwallowedKey(swallowed)
        }
    }

    /// §8.2: the single refuse path. There were nine near-identical eight-line call sites of this
    /// in `injectOnMain` differing only in a reason string.
    ///
    /// The swallow contract lives here: an asynchronous refuse owes the user the key the tap ate.
    private func refuseInject(
        _ reason: String,
        path: String,
        swallowed: SwallowedKey,
        refuseContext: PermissionCoordinator.InjectRefuseProvenance? = nil,
        completion: @escaping () -> Void
    ) {
        if swallowed.mustReinjectOnRefuse {
            _ = reinjectSwallowedKey(swallowed)
        }
        PermissionCoordinator.shared.recordInjectOutcome(
            .refused(reason),
            refuseContext: refuseContext,
            path: path
        )
        completion()
    }

    /// §3.2 + §3.1: one place where a delivered expansion is recorded. The path string is the
    /// field `InjectTelemetryLog` was built for and could not be given, because only this file
    /// knows which branch ran.
    private func finishSucceeded(
        outcome: PermissionCoordinator.InjectOutcome,
        path: String,
        context: InjectContext,
        injectedText: String,
        completion: @escaping () -> Void
    ) {
        PermissionCoordinator.shared.recordInjectOutcome(
            outcome,
            refuseContext: nil,
            path: path
        )
        rememberExpansion(context: context, injectedText: injectedText)
        completion()
    }

    /// §3.1: records the undo point. Only expansions that replaced a real trigger are recorded —
    /// an explicit hotkey / inline-search insert has nothing to revert *to*.
    private func rememberExpansion(context: InjectContext, injectedText: String) {
        guard !injectedText.isEmpty else { return }
        guard let trigger = context.erasePlan.expectedText, !trigger.isEmpty else { return }
        // The swallowed key never reached the field, but the user did type it, so undo restores it
        // along with the erased text — matching what every other expander puts back.
        let typed = context.swallowed.didSwallow
            ? trigger + context.swallowed.unicode
            : trigger
        let record = LastExpansion(
            erasePlan: context.erasePlan,
            injectedText: injectedText,
            triggerText: typed,
            bundleID: context.frontBundleID
        )
        lastExpansionLock.lock()
        _lastExpansion = record
        lastExpansionLock.unlock()
    }

    // MARK: - Cursor placement

    private func positionCursorIfNeeded(
        text: String,
        cursorOffset: Int?,
        totalUTF16Length: Int,
        allowHID: Bool,
        completion: @escaping () -> Void
    ) {
        guard let offset = cursorOffset, offset <= totalUTF16Length else {
            completion()
            return
        }
        let utf16FromEnd = totalUTF16Length - offset
        guard utf16FromEnd > 0 else {
            completion()
            return
        }
        // Prefer AX caret (works for AX-only Finish-without-Post); HID arrows only when allowed.
        // The AX path is unit-correct: AX ranges and `utf16FromEnd` are both UTF-16 code units.
        if ax.attemptAXCaretPosition(utf16OffsetFromEnd: utf16FromEnd) {
            completion()
            return
        }
        guard allowHID else {
            // AX caret failed and Post unavailable — accept inject without cursor placement.
            completion()
            return
        }
        // §1.6: a posted arrow moves one **grapheme cluster**, not one UTF-16 code unit. Posting
        // `utf16FromEnd` arrows overshot for every snippet with an emoji, an astral character or a
        // combining mark after `{{cursor}}` — and since the AX path above is correct, only the HID
        // fallback (Chrome/Electron, the majority path) was ever affected.
        let arrowCount = HIDKeyPoster.leftArrowCount(text: text, utf16OffsetFromEnd: utf16FromEnd)
        guard arrowCount > 0 else {
            completion()
            return
        }
        // Fixed settle before HID arrows — best-effort; CGEvent.post success ≠ delivery proof.
        DispatchQueue.main.asyncAfter(deadline: .now() + InjectTiming.preArrowSettleDelay) {
            self.hid.sendLeftArrowsAsync(count: arrowCount, completion: completion)
        }
    }

    // MARK: - Delegating surface (unchanged signatures; mechanics live in the collaborators)

    /// Posts a keyDown/keyUp carrying `unicode` (best-effort delivery; post ≠ guaranteed delivery).
    @discardableResult
    public func postUnicodeKeyEvent(unicode: String, keyCode: CGKeyCode, flags: CGEventFlags) -> Bool {
        hid.postUnicodeKeyEvent(unicode: unicode, keyCode: keyCode, flags: flags)
    }

    /// Posts `%key:` trailing keys after successful inject (enter/tab/…).
    public func postTrailingKeys(_ names: [String]) {
        hid.postTrailingKeys(names)
    }

    public static func keyCode(forTrailingKeyName name: String) -> CGKeyCode? {
        HIDKeyPoster.keyCode(forTrailingKeyName: name)
    }

    @discardableResult
    public func postCmdVKeyEvents() -> Bool {
        hid.postCmdVKeyEvents()
    }

    public func sendBackspaces(count: Int) {
        hid.sendBackspaces(count: count)
    }

    public func sendLeftArrows(count: Int) {
        hid.sendLeftArrows(count: count)
    }

    /// Moves selection start left by `utf16OffsetFromEnd` using AX selected-text range.
    @discardableResult
    public func attemptAXCaretPosition(utf16OffsetFromEnd: Int) -> Bool {
        ax.attemptAXCaretPosition(utf16OffsetFromEnd: utf16OffsetFromEnd)
    }

    /// Transactional AX replace. See `AXTextWriter` for the no-side-effect contract.
    public func performAXRangeReplace(
        text: String,
        eraseCount: Int,
        bundleID: String?
    ) -> AXReplaceOutcome {
        ax.performAXRangeReplace(text: text, eraseCount: eraseCount, bundleID: bundleID)
    }

    public func attemptAXDirectInjection(text: String, bundleID: String? = nil) -> Bool {
        ax.attemptAXDirectInjection(text: text, bundleID: bundleID)
    }

    @discardableResult
    public func collapseSelectionToCaret(element: AXUIElement? = nil) -> Bool {
        ax.collapseSelectionToCaret(element: element)
    }

    public func pasteViaClipboard(text: String, completion: ((Bool) -> Void)? = nil) {
        clipboard.pasteViaClipboard(text: text, completion: completion)
    }

    public func pasteViaClipboard(
        text: String,
        expectedText: String?,
        baseline: FocusedTextObservation?,
        leaveClipboardOnFailure: Bool = false,
        holdTimeoutOverride: TimeInterval? = nil,
        completeBeforeRestore: Bool = false,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        clipboard.pasteViaClipboard(
            text: text,
            expectedText: expectedText,
            baseline: baseline,
            bundleID: nil,
            leaveClipboardOnFailure: leaveClipboardOnFailure,
            holdTimeoutOverride: holdTimeoutOverride,
            completeBeforeRestore: completeBeforeRestore,
            completion: completion
        )
    }

    public func pasteImageViaClipboard(image: NSImage, completion: ((Bool) -> Void)? = nil) {
        clipboard.pasteImageViaClipboard(image: image, bundleID: nil) { result in
            completion?(result != .notPosted)
        }
    }

    @discardableResult
    public func beginRestoreGeneration() -> UInt64 {
        clipboard.beginRestoreGeneration()
    }

    public func currentRestoreGeneration() -> UInt64 {
        clipboard.currentRestoreGeneration()
    }

    public func captureFocusedTextObservation() -> FocusedTextObservation? {
        verifier.captureFocusedTextObservation()
    }

    public func verifyFocusedTextDelivery(
        expectedText: String,
        baseline: FocusedTextObservation?
    ) -> TextDeliveryVerification {
        verifier.verifyFocusedTextDelivery(expectedText: expectedText, baseline: baseline)
    }

    public static func verifyTextDelivery(
        expectedText: String,
        baseline: FocusedTextObservation?,
        after: FocusedTextObservation?
    ) -> TextDeliveryVerification {
        DeliveryVerifier.verifyTextDelivery(
            expectedText: expectedText,
            baseline: baseline,
            after: after
        )
    }

    // #region agent log
    /// Opt-in and off-thread. See `DebugTrace` — this used to write synchronously to a hardcoded
    /// path on every inject. `data` is an autoclosure so the dictionary literals at the call sites
    /// are never allocated while tracing is off.
    ///
    /// Module-internal (not private) so the extracted collaborators can keep their trace lines.
    static func debugLogInject(
        hypothesisId: String,
        message: String,
        location: String = "TextInjectionPipeline",
        data: @autoclosure () -> [String: Any]
    ) {
        guard DebugTrace.isEnabled else { return }
        DebugTrace.write(
            location: location,
            hypothesisId: hypothesisId,
            message: message,
            data: data()
        )
    }
    // #endregion
}

/// §1.3: guards the single-completion contract of one inject.
///
/// Two failure modes, both of which used to corrupt the serial inject queue silently: a path that
/// never calls its completion (the queue blocks forever and `isExpanding` never clears), and a path
/// that calls it twice (leaving a `DispatchGroup` more times than it was entered traps).
private final class InjectCompletionGuard {
    private let lock = UnfairLock()
    private var invocations = 0
    private var timedOut = false

    /// Returns the 1-based invocation index. Only `1` may leave the group.
    func markCompleted() -> Int {
        lock.lock()
        invocations += 1
        let count = invocations
        lock.unlock()
        return count
    }

    func markTimedOut() {
        lock.lock()
        timedOut = true
        lock.unlock()
    }

    var didTimeOut: Bool {
        lock.withLock { timedOut }
    }
}
