import AppKit
import ApplicationServices
import Carbon
import CoreGraphics
import Foundation

public final class TextInjectionPipeline {
    public static let shared = TextInjectionPipeline()

    public struct FocusedTextObservation: Equatable {
        public let value: String?
        public let selectedText: String?

        public init(value: String?, selectedText: String?) {
            self.value = value
            self.selectedText = selectedText
        }
    }

    public enum TextDeliveryVerification: Equatable {
        case delivered
        case failed
        case unavailable
    }

    /// Outcome of clipboard paste after optional AX verification + Cmd+V retry.
    public enum PasteDeliveryResult: Equatable {
        /// Cmd+V could not be posted (Post Events denied / CGEvent create failed).
        case notPosted
        /// AX confirmed the expected text landed.
        case delivered
        /// AX can read the field and the expected text is still missing after retries.
        case failed
        /// Cmd+V was posted but AX cannot confirm (normal for Chrome / Electron / many terminals).
        case unavailable
    }

    /// Pure policy for the post-Cmd+V clipboard-hold loop (unit-tested without AppKit paste).
    public enum PasteHoldDecision: Equatable {
        case succeed
        case failConfirmed
        case retryPaste
        case waitMore
        case giveUpUnverified
    }

    public let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    public let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    public let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Serializes inject + pasteboard restore so back-to-back expands cannot contaminate clipboard.
    private let injectQueue = DispatchQueue(label: "com.devtype.inject", qos: .userInteractive)
    private let restoreLock = NSLock()
    private var restoreGeneration: UInt64 = 0
    private let planner = InjectionPlanner()

    public init() {}

    /// Floor raised from 0.10 → 0.15 so slow Chromium/Electron hosts can read the pasteboard
    /// before we restore the user's previous clipboard contents.
    public func calculateRestoreDelay(payloadBytes: Int) -> Double {
        let calculated = Double(payloadBytes) / 40_000.0
        return max(0.15, min(0.45, calculated))
    }

    /// Settle between Cmd+V and the first AX delivery check (while our text is still on the board).
    public static let pasteDeliverySettleDelay: TimeInterval = 0.05
    /// Max time to hold our pasteboard contents waiting for AX to become readable / catch up.
    public static let pasteDeliveryHoldTimeout: TimeInterval = 0.35
    /// Longer hold for password-field secure clipboard paste so the user can press ⌘V if
    /// synthetic paste is dropped under Secure Input.
    public static let secureClipboardPasteHoldTimeout: TimeInterval = 8.0
    /// First Cmd+V + one retry when AX proves the field did not change.
    public static let pasteDeliveryMaxAttempts = 2

    /// Shown when secure clipboard paste cannot confirm delivery under Secure Input —
    /// concealed payload stays on the pasteboard for a manual ⌘V.
    public static let secureClipboardManualPasteMessage =
        "Password on clipboard — press ⌘V"

    /// Optional UI hook when secure clipboard paste leaves the payload for manual ⌘V.
    public var onSecureClipboardManualPasteHint: (() -> Void)?

    /// Decide the next step of the clipboard-hold loop. `pasteAttemptsCompleted` counts Cmd+V posts so far.
    public static func decidePasteHold(
        delivery: TextDeliveryVerification,
        pasteAttemptsCompleted: Int,
        maxAttempts: Int = pasteDeliveryMaxAttempts,
        elapsed: TimeInterval,
        holdTimeout: TimeInterval = pasteDeliveryHoldTimeout
    ) -> PasteHoldDecision {
        switch delivery {
        case .delivered:
            return .succeed
        case .failed:
            if pasteAttemptsCompleted < maxAttempts {
                return .retryPaste
            }
            return .failConfirmed
        case .unavailable:
            if elapsed < holdTimeout {
                return .waitMore
            }
            return .giveUpUnverified
        }
    }

    /// Apps whose AX `AXSelectedText` / range replace returns success without mutating the field,
    /// or whose AX focus/selection is too weak to trust. Prefer HID backspace + paste (axPlusHID).
    ///
    /// This is only the *seed* list. The live decision goes through `AXWriteCapabilityStore`, which
    /// also learns unknown apps at runtime — see `shouldSkipAXSelectedText(bundleID:)`.
    public static func prefersHIDPasteOverAXSelectedText(bundleID: String) -> Bool {
        AXWriteCapabilityStore.seedVerdict(bundleID: bundleID) == .falseSuccess
    }

    /// Live decision: seeded priors plus anything learned this session.
    public static func shouldSkipAXSelectedText(bundleID: String) -> Bool {
        AXWriteCapabilityStore.shared.shouldSkipAXSelectedText(bundleID: bundleID)
    }

    /// Next restore generation token. Pure helper for tests; production uses `beginRestoreGeneration()`.
    public static func nextRestoreGeneration(current: UInt64) -> UInt64 {
        current &+ 1
    }

    /// UTF-16 code units still present in the focused field that must be erased before injection.
    /// When the event tap swallows the final trigger key (`return nil`), that key never
    /// reaches the field, so only `triggerLength - lastEventCharacterCount` units remain.
    /// Both `triggerLength` and `lastEventCharacterCount` are UTF-16 lengths.
    public static func eraseCount(
        triggerLength: Int,
        swallowedFinalKey: Bool,
        lastEventCharacterCount: Int = 1
    ) -> Int {
        guard triggerLength > 0 else { return 0 }
        if swallowedFinalKey {
            let swallowed = max(1, lastEventCharacterCount)
            return max(0, triggerLength - swallowed)
        }
        return triggerLength
    }

    /// Erase planning for AbbreviationMatcher results under DevType swallow.
    /// Bare-word terminator is swallowed and must **not** be re-appended (unlike SnipKey listenOnly).
    /// When `terminator` is non-empty, only the trigger remains in the field → erase trigger UTF-16.
    ///
    /// Count-only; prefer `ErasePlan.forMatch` which additionally carries the grapheme count used by
    /// the HID backspace path and the expected text used by the precondition guard.
    public static func eraseCountForMatch(
        triggerUTF16Length: Int,
        terminator: String,
        swallowedFinalKey: Bool,
        lastEventCharacterCount: Int = 1
    ) -> Int {
        if !terminator.isEmpty {
            return max(0, triggerUTF16Length)
        }
        return eraseCount(
            triggerLength: triggerUTF16Length,
            swallowedFinalKey: swallowedFinalKey,
            lastEventCharacterCount: lastEventCharacterCount
        )
    }

    /// Settle delay before re-checking a failed precondition. Focus and AX state lag behind AppKit
    /// after a panel closes or an app activates, and a stale read must not cost the user an expand.
    public static let erasePreconditionRetryDelay: TimeInterval = 0.03

    /// Reads the focused field and decides whether the erase described by `plan` is safe to run.
    ///
    /// This is the backstop for the whole pipeline: no matter which path mis-planned the erase (unit
    /// confusion, a stale caret, a half-applied AX edit, a racing keystroke), if AX can read the
    /// field and the expected trigger is not sitting left of the caret, the expand is refused rather
    /// than deleting whatever *is* there.
    ///
    /// - Parameters:
    ///   - element: pre-resolved focused element. Pass one when the caller already holds it;
    ///     `AXContextChecker.focusedElement()` is not free and this runs on the keystroke path.
    ///   - retryOnMismatch: re-probe once, with a freshly resolved element, after a short settle.
    ///     The first read can catch the AX tree mid-transition — notably right after the fill-in
    ///     panel closes and focus returns to the target app — and a transient disagreement must
    ///     degrade to a retry, never to a refused expand.
    public func evaluateErasePrecondition(
        plan: ErasePlan,
        element: AXUIElement? = nil,
        retryOnMismatch: Bool = true
    ) -> ErasePreconditionResult {
        let first = evaluateErasePreconditionOnce(plan: plan, element: element)
        guard retryOnMismatch, first.blocksErase, Thread.isMainThread else { return first }
        Thread.sleep(forTimeInterval: Self.erasePreconditionRetryDelay)
        return evaluateErasePreconditionOnce(plan: plan, element: nil)
    }

    private func evaluateErasePreconditionOnce(
        plan: ErasePlan,
        element: AXUIElement?
    ) -> ErasePreconditionResult {
        if plan.utf16Count == 0 { return .ok }
        guard ErasePreconditionChecker.isEnabled else {
            return .unavailable("erase precondition disabled by user default")
        }
        guard let axElement = element ?? AXContextChecker.shared.focusedElement() else {
            return .unavailable("no focused element")
        }

        var value: String?
        var valueRef: CFTypeRef?
        if AXUIElementCopyAttributeValue(axElement, kAXValueAttribute as CFString, &valueRef) == .success {
            value = valueRef as? String
        }

        var caretLocation: Int?
        var selectionLength: Int?
        var rangeRef: CFTypeRef?
        if AXUIElementCopyAttributeValue(axElement, kAXSelectedTextRangeAttribute as CFString, &rangeRef) == .success,
           let rangeValue = rangeRef,
           CFGetTypeID(rangeValue) == AXValueGetTypeID() {
            var range = CFRange(location: 0, length: 0)
            if AXValueGetValue(unsafeBitCast(rangeValue, to: AXValue.self), .cfRange, &range) {
                caretLocation = range.location
                selectionLength = range.length
            }
        }

        return ErasePreconditionChecker.evaluate(
            plan: plan,
            value: value,
            caretLocation: caretLocation,
            selectionLength: selectionLength
        )
    }

    /// Async inject on a dedicated queue. Calls `completion` only after clipboard restore settles
    /// (or immediately when no pasteboard path was used). Never blocks the event-tap run loop.
    public func inject(
        snippet: SnippetModel,
        triggerLength: Int,
        clipboardOverride: String? = nil,
        swallowedFinalKey: Bool = false,
        lastEventCharacterCount: Int = 1,
        plan: InjectionPlan? = nil,
        swallowedUnicode: String = "",
        swallowedKeyCode: Int64 = 0,
        swallowedFlags: CGEventFlags = [],
        terminator: String = "",
        eraseCountOverride: Int? = nil,
        erasePlan: ErasePlan? = nil,
        preResolvedText: String? = nil,
        preResolvedCursorOffset: Int? = nil,
        trailingKeys: [String] = [],
        snippetLookup: ((String) -> String?)? = nil,
        secureClipboardPaste: Bool = false,
        completion: (() -> Void)? = nil
    ) {
        injectQueue.async { [self] in
            // Prefer the fully-specified plan. Fall back to count-only planning for callers that
            // cannot supply the matched text (tests, Test Expansion Lab, physical Hangul overrides);
            // those degrade to `.unavailable` in the precondition guard rather than blocking.
            let resolvedPlan: ErasePlan
            if let erasePlan {
                resolvedPlan = erasePlan
            } else if let eraseCountOverride {
                resolvedPlan = .counted(eraseCountOverride)
            } else {
                resolvedPlan = .counted(
                    Self.eraseCountForMatch(
                        triggerUTF16Length: triggerLength,
                        terminator: terminator,
                        swallowedFinalKey: swallowedFinalKey,
                        lastEventCharacterCount: lastEventCharacterCount
                    )
                )
            }

            let group = DispatchGroup()
            group.enter()
            DispatchQueue.main.async {
                self.injectOnMain(
                    snippet: snippet,
                    erasePlan: resolvedPlan,
                    clipboardOverride: clipboardOverride,
                    plan: plan,
                    swallowedFinalKey: swallowedFinalKey,
                    swallowedUnicode: swallowedUnicode,
                    swallowedKeyCode: swallowedKeyCode,
                    swallowedFlags: swallowedFlags,
                    preResolvedText: preResolvedText,
                    preResolvedCursorOffset: preResolvedCursorOffset,
                    trailingKeys: trailingKeys,
                    snippetLookup: snippetLookup,
                    secureClipboardPaste: secureClipboardPaste
                ) {
                    group.leave()
                }
            }
            group.wait()
            completion?()
        }
    }

    /// Restores a swallowed trigger key after refuse. Prefers HID post; falls back to AX insert.
    /// Call while `EventTapEngine.isExpanding` so the tap does not rematch the reinjected key.
    @discardableResult
    public func reinjectSwallowedKey(
        unicode: String,
        keyCode: Int64,
        flags: CGEventFlags
    ) -> Bool {
        if unicode.isEmpty && keyCode == 0 {
            return false
        }

        if CGPreflightPostEventAccess() {
            if postUnicodeKeyEvent(unicode: unicode, keyCode: CGKeyCode(truncatingIfNeeded: keyCode), flags: flags) {
                return true
            }
        }

        // AX-only hosts: insert the swallowed character at the caret (no Post Events).
        if !unicode.isEmpty {
            return attemptAXDirectInjection(text: unicode)
        }
        return false
    }

    /// Posts a keyDown/keyUp carrying `unicode` (best-effort delivery; post ≠ guaranteed delivery).
    @discardableResult
    public func postUnicodeKeyEvent(unicode: String, keyCode: CGKeyCode, flags: CGEventFlags) -> Bool {
        guard CGPreflightPostEventAccess() else { return false }
        let source = CGEventSource(stateID: .privateState) ?? CGEventSource(stateID: .hidSystemState)
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false) else {
            return false
        }
        down.flags = flags
        up.flags = flags
        if !unicode.isEmpty {
            let utf16 = Array(unicode.utf16)
            utf16.withUnsafeBufferPointer { buffer in
                if let base = buffer.baseAddress {
                    down.keyboardSetUnicodeString(stringLength: utf16.count, unicodeString: base)
                    up.keyboardSetUnicodeString(stringLength: utf16.count, unicodeString: base)
                }
            }
        }
        down.post(tap: .cghidEventTap)
        up.post(tap: .cghidEventTap)
        return true
    }

    private func injectOnMain(
        snippet: SnippetModel,
        erasePlan: ErasePlan,
        clipboardOverride: String?,
        plan: InjectionPlan?,
        swallowedFinalKey: Bool,
        swallowedUnicode: String,
        swallowedKeyCode: Int64,
        swallowedFlags: CGEventFlags,
        preResolvedText: String?,
        preResolvedCursorOffset: Int?,
        trailingKeys: [String],
        snippetLookup: ((String) -> String?)?,
        secureClipboardPaste: Bool,
        completion: @escaping () -> Void
    ) {
        // Re-check Secure Input / IME / focus at inject time (may have changed since match).
        let snapshot = PermissionCoordinator.shared.cachedSnapshot

        // Probe IME only when focus is available — missing focus stays non-IME for the
        // explicit secure-clipboard intent (Chrome password fields often expose no AX focus).
        var hasIME = false
        if snapshot.canUseAX,
           AXContextChecker.shared.isProcessTrusted(),
           case .available(let element) = AXContextChecker.shared.queryFocusedElement() {
            hasIME = AXContextChecker.shared.hasActiveIMEMarkedText(element: element)
        }

        let allowSecureClipboard = AXContextChecker.mayAllowSecureClipboardPaste(
            intent: secureClipboardPaste,
            canPostEvents: snapshot.canPostEvents,
            eraseEmpty: erasePlan.isEmpty,
            hasIME: hasIME
        )

        if allowSecureClipboard {
            injectSecureClipboardPasteOnMain(
                snippet: snippet,
                clipboardOverride: clipboardOverride,
                swallowedFinalKey: swallowedFinalKey,
                swallowedUnicode: swallowedUnicode,
                swallowedKeyCode: swallowedKeyCode,
                swallowedFlags: swallowedFlags,
                preResolvedText: preResolvedText,
                trailingKeys: trailingKeys,
                snippetLookup: snippetLookup,
                completion: completion
            )
            return
        }

        if AXContextChecker.isSecureEventInputEnabledLive() {
            let decision = AXContextChecker.shared.evaluateExpandGate(
                canUseAX: snapshot.canUseAX,
                canPostEvents: snapshot.canPostEvents
            )
            refuseInjectKeepingSwallow(
                reason: AXContextChecker.secureInputActiveReason,
                swallowedFinalKey: swallowedFinalKey,
                swallowedUnicode: swallowedUnicode,
                swallowedKeyCode: swallowedKeyCode,
                swallowedFlags: swallowedFlags,
                refuseContext: .capture(
                    reason: AXContextChecker.secureInputActiveReason,
                    decision: decision
                ),
                completion: completion
            )
            return
        }
        let decision = AXContextChecker.shared.evaluateExpandGate(
            canUseAX: snapshot.canUseAX,
            canPostEvents: snapshot.canPostEvents
        )
        // Keep the optional: a bundle-less frontmost app must not be learned under the literal
        // key "nil", which would then disable AX writes for every other bundle-less app.
        let frontBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        let frontBundle = frontBundleID ?? "nil"
        // #region agent log
        Self.debugLogInject(
            hypothesisId: "M1",
            message: "injectOnMain gate",
            data: [
                "frontmostBundle": frontBundle,
                "shouldBlock": decision.shouldBlock,
                "reason": decision.reason,
                "focusedAvailable": decision.snapshot.focusedAvailable,
                "isSecure": decision.snapshot.isSecureField.map { $0 ? "true" : "false" } ?? "nil",
                "hasIME": decision.snapshot.hasIMEMarkedText.map { $0 ? "true" : "false" } ?? "nil",
                "eraseUTF16": erasePlan.utf16Count,
                "eraseBackspaces": erasePlan.backspaceCount,
                "triggerLen": snippet.triggerKeyword.utf16.count,
                "textLen": (preResolvedText ?? snippet.replacementText).utf16.count
            ]
        )
        // #endregion
        if decision.shouldBlock {
            refuseInjectKeepingSwallow(
                reason: decision.reason,
                swallowedFinalKey: swallowedFinalKey,
                swallowedUnicode: swallowedUnicode,
                swallowedKeyCode: swallowedKeyCode,
                swallowedFlags: swallowedFlags,
                refuseContext: .capture(reason: decision.reason, decision: decision),
                completion: completion
            )
            return
        }

        // Backstop before anything destructive: if AX can read the field, the trigger must actually
        // be sitting left of the caret. A mismatch means our model of the field is wrong, and
        // erasing would eat the user's own text — refuse instead.
        let eraseCheck = evaluateErasePrecondition(plan: erasePlan)
        // #region agent log
        if eraseCheck != .ok {
            let label: String
            switch eraseCheck {
            case .ok: label = "ok"
            case .unavailable(let why): label = "unavailable: \(why)"
            case .mismatch(let why): label = "mismatch: \(why)"
            }
            Self.debugLogInject(
                hypothesisId: "M5",
                message: "erase precondition",
                data: [
                    "frontmostBundle": frontBundle,
                    "result": label,
                    "eraseUTF16": erasePlan.utf16Count,
                    "hasExpectedText": erasePlan.expectedText != nil
                ]
            )
        }
        // #endregion
        if case .mismatch(let why) = eraseCheck {
            DevTypeLog.inject.error(
                "[Inject] erase precondition failed — \(why, privacy: .public)"
            )
            refuseInjectKeepingSwallow(
                reason: "Erase precondition failed — \(why)",
                swallowedFinalKey: swallowedFinalKey,
                swallowedUnicode: swallowedUnicode,
                swallowedKeyCode: swallowedKeyCode,
                swallowedFlags: swallowedFlags,
                completion: completion
            )
            return
        }

        // Image snippets bypass all text/AX paths: erase the trigger with HID
        // backspaces, then paste the image through the clipboard.
        if snippet.isImageSnippet {
            guard CGPreflightPostEventAccess() else {
                refuseInjectKeepingSwallow(
                    reason: "Image expansion requires Post Events (clipboard paste)",
                    swallowedFinalKey: swallowedFinalKey,
                    swallowedUnicode: swallowedUnicode,
                    swallowedKeyCode: swallowedKeyCode,
                    swallowedFlags: swallowedFlags,
                    completion: completion
                )
                return
            }
            guard let image = ImageAttachmentStore.shared.loadImage(path: snippet.imagePath) else {
                refuseInjectKeepingSwallow(
                    reason: "Image attachment missing or unreadable: \(snippet.imagePath)",
                    swallowedFinalKey: swallowedFinalKey,
                    swallowedUnicode: swallowedUnicode,
                    swallowedKeyCode: swallowedKeyCode,
                    swallowedFlags: swallowedFlags,
                    completion: completion
                )
                return
            }
            performGuardedErase(plan: erasePlan) { [self] erased in
                guard erased else {
                    refuseInjectKeepingSwallow(
                        reason: "Erase precondition failed before image paste — field no longer holds the trigger",
                        swallowedFinalKey: swallowedFinalKey,
                        swallowedUnicode: swallowedUnicode,
                        swallowedKeyCode: swallowedKeyCode,
                        swallowedFlags: swallowedFlags,
                        completion: completion
                    )
                    return
                }
                pasteImageViaClipboard(image: image) { posted in
                    PermissionCoordinator.shared.recordInjectOutcome(posted ? .succeeded : .failedSilent)
                    completion()
                }
            }
            return
        }

        let shellLike = AXContextChecker.shared.isFrontmostShellLikeContext()
        // Snapshot clipboard before any paste mutate when macros need it.
        let clipboardArg = clipboardOverride.map { DynamicTemplateEngine.sanitizeClipboardText($0) }
        let cursorOffset: Int?
        let textToInject: String
        let keysToPress: [String]
        if let preResolvedText {
            textToInject = preResolvedText
            cursorOffset = preResolvedCursorOffset
            keysToPress = trailingKeys
        } else {
            let lookup = snippetLookup ?? { _ in nil }
            let expanded = MacroRenderer.expand(
                content: snippet.replacementText,
                fillValues: [:],
                lookup: lookup,
                clipboardText: clipboardArg
            )
            if expanded.needsFillIn {
                refuseInjectKeepingSwallow(
                    reason: "Fill-in required — present FillInPanel before inject",
                    swallowedFinalKey: swallowedFinalKey,
                    swallowedUnicode: swallowedUnicode,
                    swallowedKeyCode: swallowedKeyCode,
                    swallowedFlags: swallowedFlags,
                    completion: completion
                )
                return
            }
            textToInject = expanded.text
            cursorOffset = expanded.cursorOffset
            keysToPress = expanded.trailingKeys
        }
        let totalUTF16 = textToInject.utf16.count
        let needsCursor = InjectionPlanner.needsCursorHID(
            cursorOffset: cursorOffset,
            totalUTF16Length: totalUTF16
        )
        let isMultiLine = textToInject.contains(where: \.isNewline)

        let effectivePlan = plan ?? planner.plan(
            snapshot: snapshot,
            isTerminal: shellLike,
            needsCursorHID: needsCursor,
            isMultiLine: isMultiLine
        )

        // Shell-like + multi-line without Post: refuse (planner should already catch this).
        if shellLike, isMultiLine, !snapshot.canPostEvents {
            refuseInjectKeepingSwallow(
                reason: "Multi-line shell inject requires Post Events (bracket paste)",
                swallowedFinalKey: swallowedFinalKey,
                swallowedUnicode: swallowedUnicode,
                swallowedKeyCode: swallowedKeyCode,
                swallowedFlags: swallowedFlags,
                completion: completion
            )
            return
        }

        // #region agent log
        let planLabel: String
        switch effectivePlan {
        case .refuse: planLabel = "refuse"
        case .axOnly: planLabel = "axOnly"
        case .axPlusHID: planLabel = "axPlusHID"
        }
        Self.debugLogInject(
            hypothesisId: "M2",
            message: "injectOnMain plan",
            data: [
                "frontmostBundle": frontBundle,
                "shellLike": shellLike,
                "plan": planLabel,
                "isMultiLine": isMultiLine,
                "eraseUTF16": erasePlan.utf16Count,
                "eraseBackspaces": erasePlan.backspaceCount
            ]
        )
        // #endregion

        // Skip the AX selected-text write when this app is known — seeded or learned this session —
        // to report success without mutating. Computed before the plan switch so the AX-only path
        // gets the same protection as the AX+HID path.
        let preferHID = Self.shouldSkipAXSelectedText(bundleID: frontBundle)
        // #region agent log
        if preferHID {
            Self.debugLogInject(
                hypothesisId: "M3",
                message: "skip AX range — weak selected-text app",
                data: ["frontmostBundle": frontBundle, "preferHID": true]
            )
        }
        // #endregion

        switch effectivePlan {
        case .refuse(let reason):
            refuseInjectKeepingSwallow(
                reason: reason,
                swallowedFinalKey: swallowedFinalKey,
                swallowedUnicode: swallowedUnicode,
                swallowedKeyCode: swallowedKeyCode,
                swallowedFlags: swallowedFlags,
                completion: completion
            )
            return

        case .axOnly:
            // AX only — no HID. Range replace + optional AX caret; never erase-less direct inject.
            // A known-lying app has no fallback here, so this correctly refuses rather than
            // pretending the expand happened.
            let axOnlyOutcome = (shellLike || preferHID)
                ? AXReplaceOutcome.unavailable(shellLike ? "shell-like context" : "weak AX app")
                : performAXRangeReplace(
                    text: textToInject,
                    eraseCount: erasePlan.utf16Count,
                    bundleID: frontBundleID
                )
            if axOnlyOutcome == .replaced {
                // #region agent log
                Self.debugLogInject(
                    hypothesisId: "M3",
                    message: "inject path",
                    data: ["frontmostBundle": frontBundle, "path": "axOnlyRange", "outcome": "degradedAXOnly"]
                )
                // #endregion
                positionCursorIfNeeded(
                    cursorOffset: cursorOffset,
                    totalUTF16Length: totalUTF16,
                    allowHID: false
                ) {
                    self.postTrailingKeys(keysToPress)
                    PermissionCoordinator.shared.recordInjectOutcome(.degradedAXOnly)
                    completion()
                }
                return
            }
            refuseInjectKeepingSwallow(
                reason: "AX-only inject failed — range replace required (no erase-less direct inject); Post Events needed for HID fallback",
                swallowedFinalKey: swallowedFinalKey,
                swallowedUnicode: swallowedUnicode,
                swallowedKeyCode: swallowedKeyCode,
                swallowedFlags: swallowedFlags,
                completion: completion
            )
            return

        case .axPlusHID:
            break
        }

        if !shellLike, !preferHID,
           performAXRangeReplace(
               text: textToInject,
               eraseCount: erasePlan.utf16Count,
               bundleID: frontBundleID
           ) == .replaced {
            // #region agent log
            Self.debugLogInject(
                hypothesisId: "M3",
                message: "inject path",
                data: ["frontmostBundle": frontBundle, "path": "axRange", "outcome": "succeeded"]
            )
            // #endregion
            positionCursorIfNeeded(
                cursorOffset: cursorOffset,
                totalUTF16Length: totalUTF16,
                allowHID: true
            ) {
                self.postTrailingKeys(keysToPress)
                PermissionCoordinator.shared.recordInjectOutcome(.succeeded)
                completion()
            }
            return
        }

        // Fallback: HID backspaces then AX set or paste.
        // The guarded erase collapses any stray selection and re-verifies the trigger is still left
        // of the caret, so a half-applied AX edit above cannot be swallowed by backspace #1 and turn
        // the remaining backspaces loose on the user's text.
        performGuardedErase(plan: erasePlan) { [self] erased in
            guard erased else {
                refuseInjectKeepingSwallow(
                    reason: "Erase precondition failed before paste — field no longer holds the trigger",
                    swallowedFinalKey: swallowedFinalKey,
                    swallowedUnicode: swallowedUnicode,
                    swallowedKeyCode: swallowedKeyCode,
                    swallowedFlags: swallowedFlags,
                    completion: completion
                )
                return
            }
            if shellLike {
                // Bracket paste for terminals / IDE shells — refuse multi-line only handled above.
                // Verify against the unbracketed text (hosts strip OSC 200/201); hold clipboard until
                // AX confirms, retries once on confirmed miss, or hold timeout (unverified).
                let payload = Self.bracketPastePayload(textToInject)
                let hidPasteBaseline = self.captureFocusedTextObservation()
                pasteViaClipboard(
                    text: payload,
                    expectedText: textToInject,
                    baseline: hidPasteBaseline
                ) { result in
                    // #region agent log
                    Self.debugLogInject(
                        hypothesisId: "M4",
                        message: "inject path",
                        data: [
                            "frontmostBundle": frontBundle,
                            "path": "shellBracketPaste",
                            "result": Self.pasteResultLabel(result)
                        ]
                    )
                    // #endregion
                    self.finishPasteDelivery(
                        result: result,
                        expectedText: textToInject,
                        baseline: hidPasteBaseline,
                        erasePlan: erasePlan,
                        swallowedFinalKey: swallowedFinalKey,
                        swallowedUnicode: swallowedUnicode,
                        swallowedKeyCode: swallowedKeyCode,
                        swallowedFlags: swallowedFlags,
                        cursorOffset: cursorOffset,
                        totalUTF16Length: totalUTF16,
                        trailingKeys: keysToPress,
                        completion: completion
                    )
                }
                return
            }

            // Weak-AX apps: skip direct AX set (same false-success class as range replace).
            if !preferHID, self.attemptAXDirectInjection(text: textToInject) {
                // #region agent log
                Self.debugLogInject(
                    hypothesisId: "M3",
                    message: "inject path",
                    data: ["frontmostBundle": frontBundle, "path": "axDirect", "outcome": "succeeded"]
                )
                // #endregion
                self.positionCursorIfNeeded(
                    cursorOffset: cursorOffset,
                    totalUTF16Length: totalUTF16,
                    allowHID: true
                ) {
                    self.postTrailingKeys(keysToPress)
                    PermissionCoordinator.shared.recordInjectOutcome(.succeeded)
                    completion()
                }
                return
            }

            let hidPasteBaseline = self.captureFocusedTextObservation()
            self.pasteViaClipboard(
                text: textToInject,
                expectedText: textToInject,
                baseline: hidPasteBaseline
            ) { result in
                // #region agent log
                Self.debugLogInject(
                    hypothesisId: "M4",
                    message: "inject path",
                    data: [
                        "frontmostBundle": frontBundle,
                        "path": "hidPaste",
                        "result": Self.pasteResultLabel(result)
                    ]
                )
                // #endregion
                self.finishPasteDelivery(
                    result: result,
                    expectedText: textToInject,
                    baseline: hidPasteBaseline,
                    erasePlan: erasePlan,
                    swallowedFinalKey: swallowedFinalKey,
                    swallowedUnicode: swallowedUnicode,
                    swallowedKeyCode: swallowedKeyCode,
                    swallowedFlags: swallowedFlags,
                    cursorOffset: cursorOffset,
                    totalUTF16Length: totalUTF16,
                    trailingKeys: keysToPress,
                    completion: completion
                )
            }
        }
    }

    /// Explicit Inline Search / hotkey path: HID clipboard Cmd+V only (never AX).
    /// Bypasses live Secure Input, secure-field, and missing-focus-under-SI refuses.
    private func injectSecureClipboardPasteOnMain(
        snippet: SnippetModel,
        clipboardOverride: String?,
        swallowedFinalKey: Bool,
        swallowedUnicode: String,
        swallowedKeyCode: Int64,
        swallowedFlags: CGEventFlags,
        preResolvedText: String?,
        trailingKeys: [String],
        snippetLookup: ((String) -> String?)?,
        completion: @escaping () -> Void
    ) {
        if snippet.isImageSnippet {
            refuseInjectKeepingSwallow(
                reason: "Secure clipboard paste does not support image snippets",
                swallowedFinalKey: swallowedFinalKey,
                swallowedUnicode: swallowedUnicode,
                swallowedKeyCode: swallowedKeyCode,
                swallowedFlags: swallowedFlags,
                completion: completion
            )
            return
        }

        let clipboardArg = clipboardOverride.map { DynamicTemplateEngine.sanitizeClipboardText($0) }
        let textToInject: String
        let keysToPress: [String]
        if let preResolvedText {
            textToInject = preResolvedText
            keysToPress = trailingKeys
        } else {
            let lookup = snippetLookup ?? { _ in nil }
            let expanded = MacroRenderer.expand(
                content: snippet.replacementText,
                fillValues: [:],
                lookup: lookup,
                clipboardText: clipboardArg
            )
            if expanded.needsFillIn {
                refuseInjectKeepingSwallow(
                    reason: "Fill-in required — present FillInPanel before inject",
                    swallowedFinalKey: swallowedFinalKey,
                    swallowedUnicode: swallowedUnicode,
                    swallowedKeyCode: swallowedKeyCode,
                    swallowedFlags: swallowedFlags,
                    completion: completion
                )
                return
            }
            textToInject = expanded.text
            keysToPress = expanded.trailingKeys
        }

        let underSecureInput = AXContextChecker.isSecureEventInputEnabledLive()
        let frontBundle = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "nil"
        // #region agent log
        Self.debugLogInject(
            hypothesisId: "M4",
            message: "inject path",
            data: [
                "frontmostBundle": frontBundle,
                "path": "secureClipboardPaste",
                "underSecureInput": underSecureInput,
                "textLen": textToInject.utf16.count
            ]
        )
        // #endregion

        // No AX verification for password fields (often unreadable). Longer hold under SI so
        // the user can press ⌘V if synthetic paste is dropped.
        pasteViaClipboard(
            text: textToInject,
            expectedText: nil,
            baseline: nil,
            leaveClipboardOnFailure: underSecureInput,
            holdTimeoutOverride: underSecureInput ? Self.secureClipboardPasteHoldTimeout : nil,
            completeBeforeRestore: true
        ) { [self] result in
            switch result {
            case .delivered:
                postTrailingKeys(keysToPress)
                PermissionCoordinator.shared.recordInjectOutcome(.succeeded)
                completion()

            case .unavailable:
                // Cmd+V posted; password fields usually cannot confirm via AX.
                postTrailingKeys(keysToPress)
                PermissionCoordinator.shared.recordInjectOutcome(.postedUnverified)
                completion()

            case .notPosted, .failed:
                if underSecureInput {
                    DevTypeLog.inject.notice(
                        "[Inject] secure clipboard paste \(Self.pasteResultLabel(result), privacy: .public) under SI — leaving concealed clipboard for manual ⌘V"
                    )
                    notifySecureClipboardManualPaste()
                    PermissionCoordinator.shared.recordInjectOutcome(.postedUnverified)
                } else {
                    DevTypeLog.inject.error(
                        "[Inject] secure clipboard paste \(Self.pasteResultLabel(result), privacy: .public)"
                    )
                    PermissionCoordinator.shared.recordInjectOutcome(.failedSilent)
                }
                completion()
            }
        }
    }

    private func notifySecureClipboardManualPaste() {
        DevTypeLog.inject.notice(
            "[Inject] \(Self.secureClipboardManualPasteMessage, privacy: .public)"
        )
        onSecureClipboardManualPasteHint?()
    }

    /// Bracketed paste sequence for shell-like contexts (prevents metachar execution).
    public static func bracketPastePayload(_ text: String) -> String {
        "\u{1B}[200~" + text + "\u{1B}[201~"
    }

    private static func pasteResultLabel(_ result: PasteDeliveryResult) -> String {
        switch result {
        case .notPosted: return "notPosted"
        case .delivered: return "delivered"
        case .failed: return "failed"
        case .unavailable: return "unavailable"
        }
    }

    /// Records outcome, restores the erased trigger on confirmed paste failure, and finishes the expand.
    private func finishPasteDelivery(
        result: PasteDeliveryResult,
        expectedText: String,
        baseline: FocusedTextObservation?,
        erasePlan: ErasePlan,
        swallowedFinalKey: Bool,
        swallowedUnicode: String,
        swallowedKeyCode: Int64,
        swallowedFlags: CGEventFlags,
        cursorOffset: Int?,
        totalUTF16Length: Int,
        trailingKeys: [String] = [],
        completion: @escaping () -> Void
    ) {
        switch result {
        case .delivered:
            positionCursorIfNeeded(
                cursorOffset: cursorOffset,
                totalUTF16Length: totalUTF16Length,
                allowHID: true
            ) {
                self.postTrailingKeys(trailingKeys)
                PermissionCoordinator.shared.recordInjectOutcome(.succeeded)
                completion()
            }

        case .unavailable:
            // Cmd+V posted; AX cannot confirm. Do not treat as urgent failure — common for
            // Chrome/Electron/terminals — but keep a deferred upgrade if the text appears later.
            PermissionCoordinator.shared.recordInjectOutcome(.postedUnverified)
            completion()
            DispatchQueue.main.asyncAfter(deadline: .now() + Self.pasteReverifyDelay) { [self] in
                let retry = verifyFocusedTextDelivery(expectedText: expectedText, baseline: baseline)
                switch retry {
                case .delivered:
                    DevTypeLog.inject.info("[Inject] paste re-verify: text confirmed after settle delay")
                    PermissionCoordinator.shared.recordInjectOutcome(.succeeded)
                case .failed:
                    // Late confirmation that paste never landed — escalate + restore trigger.
                    DevTypeLog.inject.error("[Inject] paste re-verify: AX readable but text missing — treating as failed")
                    restoreTriggerAfterFailedPaste(
                        erasePlan: erasePlan,
                        swallowedFinalKey: swallowedFinalKey,
                        swallowedUnicode: swallowedUnicode,
                        swallowedKeyCode: swallowedKeyCode,
                        swallowedFlags: swallowedFlags
                    )
                    PermissionCoordinator.shared.recordInjectOutcome(.failedSilent)
                case .unavailable:
                    break
                }
            }

        case .notPosted, .failed:
            DevTypeLog.inject.error(
                "[Inject] paste delivery \(Self.pasteResultLabel(result), privacy: .public) — restoring trigger"
            )
            restoreTriggerAfterFailedPaste(
                erasePlan: erasePlan,
                swallowedFinalKey: swallowedFinalKey,
                swallowedUnicode: swallowedUnicode,
                swallowedKeyCode: swallowedKeyCode,
                swallowedFlags: swallowedFlags
            )
            PermissionCoordinator.shared.recordInjectOutcome(.failedSilent)
            completion()
        }
    }

    /// Best-effort: put the erased trigger back so a failed paste does not leave a hole in the field.
    private func restoreTriggerAfterFailedPaste(
        erasePlan: ErasePlan,
        swallowedFinalKey: Bool,
        swallowedUnicode: String,
        swallowedKeyCode: Int64,
        swallowedFlags: CGEventFlags
    ) {
        if let text = erasePlan.expectedText, !text.isEmpty {
            if attemptAXDirectInjection(text: text) {
                if EventTapEngine.mustReinjectOnRefuse(didSwallow: swallowedFinalKey) {
                    _ = reinjectSwallowedKey(
                        unicode: swallowedUnicode,
                        keyCode: swallowedKeyCode,
                        flags: swallowedFlags
                    )
                }
                return
            }
            // AX cannot restore — clipboard paste the trigger, then reinject the swallowed key.
            pasteViaClipboard(text: text) { [self] _ in
                if EventTapEngine.mustReinjectOnRefuse(didSwallow: swallowedFinalKey) {
                    _ = reinjectSwallowedKey(
                        unicode: swallowedUnicode,
                        keyCode: swallowedKeyCode,
                        flags: swallowedFlags
                    )
                }
            }
            return
        }
        if EventTapEngine.mustReinjectOnRefuse(didSwallow: swallowedFinalKey) {
            _ = reinjectSwallowedKey(
                unicode: swallowedUnicode,
                keyCode: swallowedKeyCode,
                flags: swallowedFlags
            )
        }
    }

    /// Settle delay for the deferred AX re-verification pass after unverified HID paste.
    public static let pasteReverifyDelay: TimeInterval = 0.25

    /// Posts `%key:` trailing keys after successful inject (enter/tab/…).
    public func postTrailingKeys(_ names: [String]) {
        guard !names.isEmpty, CGPreflightPostEventAccess() else { return }
        let source = makeTaggedEventSource()
        for name in names {
            guard let keyCode = Self.keyCode(forTrailingKeyName: name) else { continue }
            if let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
               let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false) {
                down.post(tap: .cghidEventTap)
                up.post(tap: .cghidEventTap)
            }
        }
    }

    public static func keyCode(forTrailingKeyName name: String) -> CGKeyCode? {
        switch name.lowercased() {
        case "enter", "return": return CGKeyCode(kVK_Return)
        case "tab": return CGKeyCode(kVK_Tab)
        case "escape", "esc": return CGKeyCode(kVK_Escape)
        case "space": return CGKeyCode(kVK_Space)
        default: return nil
        }
    }

    private func makeTaggedEventSource() -> CGEventSource? {
        let source = CGEventSource(stateID: .privateState) ?? CGEventSource(stateID: .hidSystemState)
        source?.userData = SyntheticEventMarker.magicUserData
        return source
    }

    private func refuseInjectKeepingSwallow(
        reason: String,
        swallowedFinalKey: Bool,
        swallowedUnicode: String,
        swallowedKeyCode: Int64,
        swallowedFlags: CGEventFlags,
        refuseContext: PermissionCoordinator.InjectRefuseProvenance? = nil,
        completion: @escaping () -> Void
    ) {
        if EventTapEngine.mustReinjectOnRefuse(didSwallow: swallowedFinalKey) {
            _ = reinjectSwallowedKey(
                unicode: swallowedUnicode,
                keyCode: swallowedKeyCode,
                flags: swallowedFlags
            )
        }
        PermissionCoordinator.shared.recordInjectOutcome(
            .refused(reason),
            refuseContext: refuseContext
        )
        completion()
    }

    private func positionCursorIfNeeded(
        cursorOffset: Int?,
        totalUTF16Length: Int,
        allowHID: Bool,
        completion: @escaping () -> Void
    ) {
        guard let offset = cursorOffset, offset <= totalUTF16Length else {
            completion()
            return
        }
        let moveLeftCount = totalUTF16Length - offset
        guard moveLeftCount > 0 else {
            completion()
            return
        }
        // Prefer AX caret (works for AX-only Finish-without-Post); HID arrows only when allowed.
        if attemptAXCaretPosition(utf16OffsetFromEnd: moveLeftCount) {
            completion()
            return
        }
        guard allowHID else {
            // AX caret failed and Post unavailable — accept inject without cursor placement.
            completion()
            return
        }
        // Fixed settle before HID arrows — best-effort; CGEvent.post success ≠ delivery proof.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.04) { [self] in
            self.sendLeftArrowsAsync(count: moveLeftCount, completion: completion)
        }
    }

    /// Moves selection start left by `utf16OffsetFromEnd` using AX selected-text range.
    @discardableResult
    public func attemptAXCaretPosition(utf16OffsetFromEnd: Int) -> Bool {
        guard utf16OffsetFromEnd > 0 else { return true }
        guard let axElement = AXContextChecker.shared.focusedElement() else { return false }

        var rangeRef: CFTypeRef?
        guard AXUIElementCopyAttributeValue(axElement, kAXSelectedTextRangeAttribute as CFString, &rangeRef) == .success,
              let rangeValue = rangeRef,
              CFGetTypeID(rangeValue) == AXValueGetTypeID() else {
            return false
        }

        let axRangeValue = unsafeBitCast(rangeValue, to: AXValue.self)
        var range = CFRange(location: 0, length: 0)
        guard AXValueGetValue(axRangeValue, .cfRange, &range) else { return false }

        let newLocation = max(0, range.location - utf16OffsetFromEnd)
        var caret = CFRange(location: newLocation, length: 0)
        guard let caretValue = AXValueCreate(.cfRange, &caret) else { return false }
        return AXUIElementSetAttributeValue(axElement, kAXSelectedTextRangeAttribute as CFString, caretValue) == .success
    }

    /// Outcome of an AX selected-text replace attempt.
    public enum AXReplaceOutcome: Equatable {
        /// The field actually changed — inject is done.
        case replaced
        /// AX returned `.success` but the field is byte-identical. The app lies; condemn it.
        case falseSuccess
        /// Could not attempt or could not judge (no focus, unreadable range, set failed).
        case unavailable(String)
    }

    /// Transactional AX replace.
    ///
    /// Contract: when this returns anything other than `.replaced`, the field and its selection are
    /// left **exactly** as they were found. Callers fall back to HID backspace + paste, which
    /// assumes an untouched field — leaving a widened selection behind is what caused backspace #1
    /// to eat the selection and the remaining backspaces to eat the user's preceding text.
    public func performAXRangeReplace(
        text: String,
        eraseCount: Int,
        bundleID: String?
    ) -> AXReplaceOutcome {
        guard let axElement = AXContextChecker.shared.focusedElement() else {
            // #region agent log
            Self.debugLogInject(
                hypothesisId: "M3",
                message: "axRangeReplace",
                data: ["ok": false, "fail": "noFocusedElement"]
            )
            // #endregion
            return .unavailable("no focused element")
        }

        var roleRef: CFTypeRef?
        let role: String =
            (AXUIElementCopyAttributeValue(axElement, kAXRoleAttribute as CFString, &roleRef) == .success)
            ? ((roleRef as? String) ?? "")
            : ""

        var rangeRef: CFTypeRef?
        let rangeCopy = AXUIElementCopyAttributeValue(
            axElement,
            kAXSelectedTextRangeAttribute as CFString,
            &rangeRef
        )
        guard rangeCopy == .success,
              let rangeValue = rangeRef,
              CFGetTypeID(rangeValue) == AXValueGetTypeID() else {
            // #region agent log
            Self.debugLogInject(
                hypothesisId: "M3",
                message: "axRangeReplace",
                data: [
                    "ok": false,
                    "fail": "selectedTextRange",
                    "rangeAXError": Int(rangeCopy.rawValue),
                    "role": role
                ]
            )
            // #endregion
            return .unavailable("AXSelectedTextRange unreadable (\(rangeCopy.rawValue))")
        }

        let axRangeValue = unsafeBitCast(rangeValue, to: AXValue.self)
        var range = CFRange(location: 0, length: 0)
        guard AXValueGetValue(axRangeValue, .cfRange, &range) else {
            // #region agent log
            Self.debugLogInject(
                hypothesisId: "M3",
                message: "axRangeReplace",
                data: ["ok": false, "fail": "rangeDecode", "role": role]
            )
            // #endregion
            return .unavailable("AXSelectedTextRange undecodable")
        }

        // Caller falls back to HID backspace + paste when this returns false. That fallback assumes
        // the field is untouched, so every failure path below MUST undo the widened selection —
        // otherwise backspace #1 eats the selection and the rest eat preceding user text.
        let originalRange = range
        func restoreOriginalSelection() {
            var restore = originalRange
            guard let restoreValue = AXValueCreate(.cfRange, &restore) else { return }
            _ = AXUIElementSetAttributeValue(
                axElement,
                kAXSelectedTextRangeAttribute as CFString,
                restoreValue
            )
        }

        // Baseline value: the only reliable way to tell "AX reported success but did not mutate"
        // (Messages / Electron) apart from a real edit we simply cannot re-read.
        var beforeValueRef: CFTypeRef?
        let beforeValue: String? =
            (AXUIElementCopyAttributeValue(axElement, kAXValueAttribute as CFString, &beforeValueRef) == .success)
            ? (beforeValueRef as? String)
            : nil

        let erase = max(0, eraseCount)
        let newLocation = max(0, range.location - erase)
        let newLength = (range.location - newLocation) + range.length
        var expanded = CFRange(location: newLocation, length: newLength)

        guard let newRangeValue = AXValueCreate(.cfRange, &expanded) else {
            return .unavailable("AXValueCreate failed for widened range")
        }
        let setRange = AXUIElementSetAttributeValue(
            axElement,
            kAXSelectedTextRangeAttribute as CFString,
            newRangeValue
        )
        guard setRange == .success else {
            // #region agent log
            Self.debugLogInject(
                hypothesisId: "M3",
                message: "axRangeReplace",
                data: [
                    "ok": false,
                    "fail": "setSelectedRange",
                    "setRangeAXError": Int(setRange.rawValue),
                    "role": role,
                    "loc": range.location,
                    "len": range.length,
                    "erase": erase
                ]
            )
            // #endregion
            // Selection unchanged (the set failed), so there is nothing to roll back.
            return .unavailable("setSelectedTextRange failed (\(setRange.rawValue))")
        }

        let setResult = AXUIElementSetAttributeValue(axElement, kAXSelectedTextAttribute as CFString, text as CFTypeRef)
        var valueLen = -1
        /// Only a read-back comparison is evidence about this app's AX behaviour. Assuming success
        /// because we could not read the field must never be recorded as trust — that would
        /// overwrite a seeded `.falseSuccess` verdict and re-enable the broken path for the session.
        var verdictIsEvidence = false
        let outcome: AXReplaceOutcome

        if setResult != .success {
            outcome = .unavailable("setSelectedText failed (\(setResult.rawValue))")
        } else {
            // Reject false AX success: setSelectedText can return `.success` without mutating
            // (Messages, Chromium/Electron web views). The test is "did the field change", NOT
            // "can we find `text` in the value" — some hosts return a stale or virtualised AXValue
            // right after a real edit, and treating that as failure sends the HID fallback at an
            // already-mutated field, which duplicates text or deletes past the trigger.
            var valueRef: CFTypeRef?
            if AXUIElementCopyAttributeValue(axElement, kAXValueAttribute as CFString, &valueRef) == .success,
               let value = valueRef as? String {
                valueLen = value.utf16.count
                verdictIsEvidence = true
                if let beforeValue {
                    outcome = value == beforeValue ? .falseSuccess : .replaced
                } else {
                    // No baseline to compare against — fall back to containment.
                    outcome = value.contains(text) ? .replaced : .falseSuccess
                }
            } else {
                // AX write claimed success and we cannot read the field back. We must not assume it
                // was a no-op (that would double-apply); treat it as applied but unverified, and
                // learn nothing about the app from it.
                outcome = .replaced
            }
        }

        if outcome != .replaced {
            restoreOriginalSelection()
        }

        if let bundleID, !bundleID.isEmpty, verdictIsEvidence {
            switch outcome {
            case .replaced:
                AXWriteCapabilityStore.shared.recordTrusted(bundleID: bundleID)
            case .falseSuccess:
                AXWriteCapabilityStore.shared.recordFalseSuccess(bundleID: bundleID)
            case .unavailable:
                break
            }
        }

        // #region agent log
        let failLabel: String
        switch outcome {
        case .replaced: failLabel = "none"
        case .falseSuccess: failLabel = "valueVerifyFailed"
        case .unavailable(let why): failLabel = why
        }
        Self.debugLogInject(
            hypothesisId: "M3",
            message: "axRangeReplace",
            data: [
                "ok": outcome == .replaced,
                "fail": failLabel,
                "setTextAXError": Int(setResult.rawValue),
                "role": role,
                "loc": range.location,
                "len": range.length,
                "erase": erase,
                "textLen": text.utf16.count,
                "valueLen": valueLen
            ]
        )
        // #endregion
        return outcome
    }

    // #region agent log
    /// Opt-in and off-thread. See `DebugTrace` — this used to write synchronously to a hardcoded
    /// path on every inject. `data` is an autoclosure so the dictionary literals at the call sites
    /// are never allocated while tracing is off.
    private static func debugLogInject(
        hypothesisId: String,
        message: String,
        data: @autoclosure () -> [String: Any]
    ) {
        guard DebugTrace.isEnabled else { return }
        DebugTrace.write(
            location: "TextInjectionPipeline",
            hypothesisId: hypothesisId,
            message: message,
            data: data()
        )
    }
    // #endregion

    public func attemptAXDirectInjection(text: String) -> Bool {
        guard let axElement = AXContextChecker.shared.focusedElement() else { return false }
        // Baseline before the write so `verifyTextDelivery` can distinguish "nothing happened" from
        // "it happened but the host reports a stale value". Without it a real insert can be judged
        // failed, and the caller then pastes the same text a second time.
        let baseline = focusedTextObservation(for: axElement)
        let result = AXUIElementSetAttributeValue(axElement, kAXSelectedTextAttribute as CFString, text as CFTypeRef)
        guard result == .success else { return false }
        switch Self.verifyTextDelivery(
            expectedText: text,
            baseline: baseline,
            after: focusedTextObservation(for: axElement)
        ) {
        case .failed:
            return false
        case .delivered, .unavailable:
            return true
        }
    }

    public func pasteViaClipboard(text: String, completion: ((Bool) -> Void)? = nil) {
        pasteViaClipboard(text: text, expectedText: nil, baseline: nil) { result in
            completion?(result != .notPosted)
        }
    }

    /// Clipboard paste that holds our payload until AX confirms delivery, a confirmed miss exhausts
    /// retries, or the hold timeout expires (unverified). Restores the prior pasteboard afterward.
    ///
    /// - Parameters:
    ///   - leaveClipboardOnFailure: When true, skip immediate restore on `.notPosted` / `.failed` so the
    ///     concealed payload remains for a manual ⌘V (secure clipboard paste under Secure Input).
    ///   - holdTimeoutOverride: Optional longer hold (e.g. secure clipboard paste under SI).
    ///   - completeBeforeRestore: When true and no `expectedText`, report `.unavailable` right after
    ///     Cmd+V so callers are not blocked for the full hold window.
    public func pasteViaClipboard(
        text: String,
        expectedText: String?,
        baseline: FocusedTextObservation?,
        leaveClipboardOnFailure: Bool = false,
        holdTimeoutOverride: TimeInterval? = nil,
        completeBeforeRestore: Bool = false,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        // Re-check Post Events at paste time.
        guard CGPreflightPostEventAccess() else {
            DevTypeLog.inject.error("[Inject] paste refused — Post Events denied at paste time")
            completion(.notPosted)
            return
        }

        let pasteboard = NSPasteboard.general

        let oldItems = pasteboard.pasteboardItems?.compactMap { item -> [NSPasteboard.PasteboardType: Data]? in
            var dict = [NSPasteboard.PasteboardType: Data]()
            for type in item.types {
                if let data = item.data(forType: type) {
                    dict[type] = data
                }
            }
            return dict
        }

        let generation = beginRestoreGeneration()

        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        pasteboard.setData(Data(), forType: transientType)
        pasteboard.setData(Data(), forType: concealedType)
        pasteboard.setData(Data(), forType: autoGeneratedType)

        let targetChangeCount = pasteboard.changeCount
        let restoreDelay = holdTimeoutOverride
            ?? calculateRestoreDelay(payloadBytes: text.utf8.count)
        let holdTimeout = holdTimeoutOverride
            ?? max(Self.pasteDeliveryHoldTimeout, restoreDelay)

        DispatchQueue.main.asyncAfter(deadline: .now() + 0.015) { [self] in
            let posted = self.postCmdVKeyEvents()
            if !posted {
                if leaveClipboardOnFailure {
                    // Leave concealed payload for manual ⌘V; restore after the extended hold.
                    DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelay) {
                        self.restorePasteboard(
                            pasteboard: pasteboard,
                            oldItems: oldItems,
                            generation: generation,
                            targetChangeCount: targetChangeCount
                        )
                    }
                } else {
                    self.restorePasteboard(
                        pasteboard: pasteboard,
                        oldItems: oldItems,
                        generation: generation,
                        targetChangeCount: targetChangeCount
                    )
                }
                completion(.notPosted)
                return
            }

            guard let expectedText, !expectedText.isEmpty else {
                if completeBeforeRestore {
                    completion(.unavailable)
                    DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelay) {
                        self.restorePasteboard(
                            pasteboard: pasteboard,
                            oldItems: oldItems,
                            generation: generation,
                            targetChangeCount: targetChangeCount
                        )
                    }
                } else {
                    DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelay) {
                        self.restorePasteboard(
                            pasteboard: pasteboard,
                            oldItems: oldItems,
                            generation: generation,
                            targetChangeCount: targetChangeCount
                        )
                        completion(.unavailable)
                    }
                }
                return
            }

            self.runPasteHoldLoop(
                expectedText: expectedText,
                baseline: baseline,
                pasteAttemptsCompleted: 1,
                holdStarted: Date(),
                holdTimeout: holdTimeout,
                pasteboard: pasteboard,
                oldItems: oldItems,
                generation: generation,
                targetChangeCount: targetChangeCount,
                leaveClipboardOnFailure: leaveClipboardOnFailure,
                completion: completion
            )
        }
    }

    private func runPasteHoldLoop(
        expectedText: String,
        baseline: FocusedTextObservation?,
        pasteAttemptsCompleted: Int,
        holdStarted: Date,
        holdTimeout: TimeInterval,
        pasteboard: NSPasteboard,
        oldItems: [[NSPasteboard.PasteboardType: Data]]?,
        generation: UInt64,
        targetChangeCount: Int,
        leaveClipboardOnFailure: Bool = false,
        completion: @escaping (PasteDeliveryResult) -> Void
    ) {
        DispatchQueue.main.asyncAfter(deadline: .now() + Self.pasteDeliverySettleDelay) { [self] in
            let delivery = verifyFocusedTextDelivery(expectedText: expectedText, baseline: baseline)
            let elapsed = Date().timeIntervalSince(holdStarted)
            let decision = Self.decidePasteHold(
                delivery: delivery,
                pasteAttemptsCompleted: pasteAttemptsCompleted,
                elapsed: elapsed,
                holdTimeout: holdTimeout
            )

            switch decision {
            case .succeed:
                restorePasteboard(
                    pasteboard: pasteboard,
                    oldItems: oldItems,
                    generation: generation,
                    targetChangeCount: targetChangeCount
                )
                completion(.delivered)

            case .failConfirmed:
                DevTypeLog.inject.error(
                    "[Inject] paste hold: AX readable but expected text missing after \(pasteAttemptsCompleted, privacy: .public) Cmd+V attempt(s)"
                )
                if leaveClipboardOnFailure {
                    DispatchQueue.main.asyncAfter(deadline: .now() + holdTimeout) {
                        self.restorePasteboard(
                            pasteboard: pasteboard,
                            oldItems: oldItems,
                            generation: generation,
                            targetChangeCount: targetChangeCount
                        )
                    }
                } else {
                    restorePasteboard(
                        pasteboard: pasteboard,
                        oldItems: oldItems,
                        generation: generation,
                        targetChangeCount: targetChangeCount
                    )
                }
                completion(.failed)

            case .giveUpUnverified:
                restorePasteboard(
                    pasteboard: pasteboard,
                    oldItems: oldItems,
                    generation: generation,
                    targetChangeCount: targetChangeCount
                )
                completion(.unavailable)

            case .retryPaste:
                DevTypeLog.inject.notice(
                    "[Inject] paste hold: retrying Cmd+V (attempt \(pasteAttemptsCompleted + 1, privacy: .public))"
                )
                if postCmdVKeyEvents() {
                    runPasteHoldLoop(
                        expectedText: expectedText,
                        baseline: baseline,
                        pasteAttemptsCompleted: pasteAttemptsCompleted + 1,
                        holdStarted: holdStarted,
                        holdTimeout: holdTimeout,
                        pasteboard: pasteboard,
                        oldItems: oldItems,
                        generation: generation,
                        targetChangeCount: targetChangeCount,
                        leaveClipboardOnFailure: leaveClipboardOnFailure,
                        completion: completion
                    )
                } else {
                    if leaveClipboardOnFailure {
                        DispatchQueue.main.asyncAfter(deadline: .now() + holdTimeout) {
                            self.restorePasteboard(
                                pasteboard: pasteboard,
                                oldItems: oldItems,
                                generation: generation,
                                targetChangeCount: targetChangeCount
                            )
                        }
                    } else {
                        restorePasteboard(
                            pasteboard: pasteboard,
                            oldItems: oldItems,
                            generation: generation,
                            targetChangeCount: targetChangeCount
                        )
                    }
                    completion(.failed)
                }

            case .waitMore:
                runPasteHoldLoop(
                    expectedText: expectedText,
                    baseline: baseline,
                    pasteAttemptsCompleted: pasteAttemptsCompleted,
                    holdStarted: holdStarted,
                    holdTimeout: holdTimeout,
                    pasteboard: pasteboard,
                    oldItems: oldItems,
                    generation: generation,
                    targetChangeCount: targetChangeCount,
                    leaveClipboardOnFailure: leaveClipboardOnFailure,
                    completion: completion
                )
            }
        }
    }

    /// Clipboard-pastes an image (TIFF + PNG reps) with the same snapshot/restore
    /// discipline as `pasteViaClipboard`. Used by image snippets only.
    public func pasteImageViaClipboard(image: NSImage, completion: ((Bool) -> Void)? = nil) {
        guard CGPreflightPostEventAccess() else {
            DevTypeLog.inject.error("[Inject] image paste refused — Post Events denied at paste time")
            completion?(false)
            return
        }

        let pasteboard = NSPasteboard.general

        let oldItems = pasteboard.pasteboardItems?.compactMap { item -> [NSPasteboard.PasteboardType: Data]? in
            var dict = [NSPasteboard.PasteboardType: Data]()
            for type in item.types {
                if let data = item.data(forType: type) {
                    dict[type] = data
                }
            }
            return dict
        }

        let generation = beginRestoreGeneration()

        pasteboard.clearContents()
        var wrote = false
        if let tiff = image.tiffRepresentation {
            pasteboard.setData(tiff, forType: .tiff)
            wrote = true
        }
        if let cgImage = image.cgImage(forProposedRect: nil, context: nil, hints: nil) {
            let rep = NSBitmapImageRep(cgImage: cgImage)
            if let png = rep.representation(using: .png, properties: [:]) {
                pasteboard.setData(png, forType: .png)
                wrote = true
            }
        }
        guard wrote else {
            completion?(false)
            return
        }
        pasteboard.setData(Data(), forType: transientType)
        pasteboard.setData(Data(), forType: concealedType)
        pasteboard.setData(Data(), forType: autoGeneratedType)

        let targetChangeCount = pasteboard.changeCount
        let payloadBytes = (pasteboard.data(forType: .tiff)?.count ?? 0) + (pasteboard.data(forType: .png)?.count ?? 0)
        let restoreDelay = calculateRestoreDelay(payloadBytes: payloadBytes)

        DispatchQueue.main.asyncAfter(deadline: .now() + 0.015) { [self] in
            let posted = self.postCmdVKeyEvents()
            if !posted {
                self.restorePasteboard(
                    pasteboard: pasteboard,
                    oldItems: oldItems,
                    generation: generation,
                    targetChangeCount: targetChangeCount
                )
                completion?(false)
                return
            }

            DispatchQueue.main.asyncAfter(deadline: .now() + restoreDelay) {
                defer { completion?(true) }
                self.restorePasteboard(
                    pasteboard: pasteboard,
                    oldItems: oldItems,
                    generation: generation,
                    targetChangeCount: targetChangeCount
                )
            }
        }
    }

    private func restorePasteboard(
        pasteboard: NSPasteboard,
        oldItems: [[NSPasteboard.PasteboardType: Data]]?,
        generation: UInt64,
        targetChangeCount: Int
    ) {
        // Generation gate: a newer expand owns the pasteboard — skip stale restore.
        guard currentRestoreGeneration() == generation else { return }
        guard pasteboard.changeCount == targetChangeCount else { return }

        pasteboard.clearContents()
        guard let oldItems, !oldItems.isEmpty else { return }

        let restoredItems: [NSPasteboardItem] = oldItems.map { itemDict in
            let newItem = NSPasteboardItem()
            itemDict.forEach { type, data in
                newItem.setData(data, forType: type)
            }
            return newItem
        }
        pasteboard.writeObjects(restoredItems)
    }

    @discardableResult
    public func beginRestoreGeneration() -> UInt64 {
        restoreLock.lock()
        restoreGeneration = Self.nextRestoreGeneration(current: restoreGeneration)
        let token = restoreGeneration
        restoreLock.unlock()
        return token
    }

    public func currentRestoreGeneration() -> UInt64 {
        restoreLock.lock()
        defer { restoreLock.unlock() }
        return restoreGeneration
    }

    @discardableResult
    /// Physical ⌘V: Command down → V → Command up (15 ms gaps). Flag-only ⌘V fails under many IMEs.
    /// Used only on the HID clipboard paste path — never on AX range replace.
    public func postCmdVKeyEvents() -> Bool {
        // Re-check at post time — CGEvent create-success is not delivery proof if Post was revoked.
        guard CGPreflightPostEventAccess() else {
            DevTypeLog.inject.error(
                "[Inject] Cmd+V refused — CGPreflightPostEventAccess false at post time"
            )
            return false
        }

        let source = makeTaggedEventSource()
        let command = CGKeyCode(kVK_Command)
        let vKeyCode = resolveVirtualKeyCodeForChar("v") ?? CGKeyCode(kVK_ANSI_V)

        if let cmdDown = CGEvent(keyboardEventSource: source, virtualKey: command, keyDown: true) {
            cmdDown.flags = .maskCommand
            cmdDown.post(tap: .cghidEventTap)
        }
        usleep(15_000)

        guard let vDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true),
              let vUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false) else {
            DevTypeLog.inject.error(
                "[Inject] Cmd+V CGEvent create failed — Post Events may be revoked or CG HID unavailable"
            )
            return false
        }
        vDown.flags = .maskCommand
        vUp.flags = .maskCommand
        vDown.post(tap: .cghidEventTap)
        vUp.post(tap: .cghidEventTap)
        usleep(15_000)

        if let cmdUp = CGEvent(keyboardEventSource: source, virtualKey: command, keyDown: false) {
            cmdUp.flags = []
            cmdUp.post(tap: .cghidEventTap)
        }
        return true
    }

    private func resolveVirtualKeyCodeForChar(_ targetChar: Character) -> CGKeyCode? {
        guard let inputSource = TISCopyCurrentKeyboardInputSource()?.takeRetainedValue(),
              let layoutData = TISGetInputSourceProperty(inputSource, kTISPropertyUnicodeKeyLayoutData) else {
            return 9
        }

        let data = unsafeBitCast(layoutData, to: CFData.self)
        guard let bytes = CFDataGetBytePtr(data) else { return 9 }

        return bytes.withMemoryRebound(to: UCKeyboardLayout.self, capacity: 1) { keyboardLayout -> CGKeyCode in
            var chars = [UniChar](repeating: 0, count: 4)
            var realLength = 0

            for code: CGKeyCode in 0..<128 {
                var deadKeyState: UInt32 = 0
                let status = UCKeyTranslate(
                    keyboardLayout,
                    code,
                    UInt16(kUCKeyActionDisplay),
                    0,
                    UInt32(KBGetLayoutType(0)),
                    OptionBits(kUCKeyTranslateNoDeadKeysBit),
                    &deadKeyState,
                    4,
                    &realLength,
                    &chars
                )
                if status == noErr && realLength > 0 {
                    let str = String(utf16CodeUnits: chars, count: realLength)
                    if str.lowercased() == String(targetChar).lowercased() {
                        return code
                    }
                }
            }
            return 9
        }
    }

    public func captureFocusedTextObservation() -> FocusedTextObservation? {
        guard let axElement = AXContextChecker.shared.focusedElement() else { return nil }
        return focusedTextObservation(for: axElement)
    }

    public func verifyFocusedTextDelivery(
        expectedText: String,
        baseline: FocusedTextObservation?
    ) -> TextDeliveryVerification {
        Self.verifyTextDelivery(
            expectedText: expectedText,
            baseline: baseline,
            after: captureFocusedTextObservation()
        )
    }

    public static func verifyTextDelivery(
        expectedText: String,
        baseline: FocusedTextObservation?,
        after: FocusedTextObservation?
    ) -> TextDeliveryVerification {
        guard !expectedText.isEmpty else { return .delivered }
        guard let after else { return .unavailable }
        if after.selectedText == expectedText {
            return .delivered
        }
        guard let value = after.value else {
            return .unavailable
        }
        guard value.contains(expectedText) else {
            return .failed
        }
        guard let baseline else {
            return .delivered
        }
        let baselineContainsExpected = baseline.value?.contains(expectedText) == true
        if value != baseline.value || after.selectedText != baseline.selectedText || !baselineContainsExpected {
            return .delivered
        }
        return .unavailable
    }

    private func focusedTextObservation(for axElement: AXUIElement) -> FocusedTextObservation {
        var value: String?
        var selectedText: String?

        var valueRef: CFTypeRef?
        if AXUIElementCopyAttributeValue(axElement, kAXValueAttribute as CFString, &valueRef) == .success {
            value = valueRef as? String
        }

        var selectedTextRef: CFTypeRef?
        if AXUIElementCopyAttributeValue(axElement, kAXSelectedTextAttribute as CFString, &selectedTextRef) == .success {
            selectedText = selectedTextRef as? String
        }

        return FocusedTextObservation(value: value, selectedText: selectedText)
    }

    public func sendBackspaces(count: Int) {
        guard count > 0 else { return }
        guard CGPreflightPostEventAccess() else {
            DevTypeLog.inject.error(
                "[Inject] backspace refused — CGPreflightPostEventAccess false at post time count=\(count, privacy: .public)"
            )
            return
        }
        let source = makeTaggedEventSource()
        var posted = 0
        for _ in 0..<count {
            if let bDown = CGEvent(keyboardEventSource: source, virtualKey: 51, keyDown: true),
               let bUp = CGEvent(keyboardEventSource: source, virtualKey: 51, keyDown: false) {
                bDown.post(tap: .cghidEventTap)
                bUp.post(tap: .cghidEventTap)
                posted += 1
            }
        }
        if posted == 0 {
            DevTypeLog.inject.error(
                "[Inject] backspace CGEvent create failed count=\(count, privacy: .public) — Post Events may be revoked"
            )
        } else if posted < count {
            DevTypeLog.inject.notice(
                "[Inject] backspace CGEvent partial posted=\(posted, privacy: .public)/\(count, privacy: .public)"
            )
        }
    }

    private func sendBackspacesAsync(count: Int, completion: @escaping () -> Void) {
        guard count > 0 else {
            completion()
            return
        }
        sendBackspaces(count: count)
        DispatchQueue.main.asyncAfter(deadline: .now() + Double(count) * 0.002 + 0.01, execute: completion)
    }

    /// Collapses any non-empty selection to the caret at its trailing edge.
    ///
    /// A selection sitting in the field when we are about to post backspaces is almost always our
    /// own leftover (an AX replace that widened the range then failed). Backspace #1 would consume
    /// the whole selection and every subsequent backspace would eat the user's preceding text — the
    /// "expansion deleted the previous N characters" bug. Collapsing to the trailing edge makes the
    /// backspace count mean exactly what it says.
    @discardableResult
    public func collapseSelectionToCaret(element: AXUIElement? = nil) -> Bool {
        guard let axElement = element ?? AXContextChecker.shared.focusedElement() else { return false }

        var rangeRef: CFTypeRef?
        guard AXUIElementCopyAttributeValue(axElement, kAXSelectedTextRangeAttribute as CFString, &rangeRef) == .success,
              let rangeValue = rangeRef,
              CFGetTypeID(rangeValue) == AXValueGetTypeID() else {
            return false
        }
        var range = CFRange(location: 0, length: 0)
        guard AXValueGetValue(unsafeBitCast(rangeValue, to: AXValue.self), .cfRange, &range) else {
            return false
        }
        guard range.length > 0 else { return true }

        DevTypeLog.inject.notice(
            "[Inject] collapsing stray selection before erase length=\(range.length, privacy: .public)"
        )
        // Trailing edge, deliberately. The selection we are cleaning up was produced by a failed AX
        // replace, which widens *backwards* from the caret to cover the trigger — so the trailing
        // edge is where the caret was before we touched it, and `backspaceCount` backspaces from
        // there remove exactly the trigger.
        var caret = CFRange(location: range.location + range.length, length: 0)
        guard let caretValue = AXValueCreate(.cfRange, &caret) else { return false }
        return AXUIElementSetAttributeValue(
            axElement,
            kAXSelectedTextRangeAttribute as CFString,
            caretValue
        ) == .success
    }

    /// Collapse stray selection → re-verify the erase precondition → post backspaces.
    ///
    /// The precondition is checked again here (not only at the top of `injectOnMain`) because
    /// everything between the two checks — an AX replace attempt, a macro resolve, a fill-in panel —
    /// can move the caret or change the field. This is the last gate before text is destroyed.
    /// `completion(false)` means the erase was refused and the caller must abort the expand.
    private func performGuardedErase(plan: ErasePlan, completion: @escaping (Bool) -> Void) {
        guard plan.backspaceCount > 0 else {
            completion(true)
            return
        }
        // Resolve focus once and share it: `AXContextChecker.focusedElement()` is a multi-step AX
        // round trip and this sits on the keystroke path. Attribute reads through the handle stay
        // live, so the precondition still sees the post-collapse selection.
        let element = AXContextChecker.shared.focusedElement()
        collapseSelectionToCaret(element: element)
        if case .mismatch(let why) = evaluateErasePrecondition(plan: plan, element: element) {
            DevTypeLog.inject.error(
                "[Inject] erase aborted before backspaces — \(why, privacy: .public)"
            )
            // #region agent log
            Self.debugLogInject(
                hypothesisId: "M5",
                message: "guarded erase aborted",
                data: ["why": why, "eraseBackspaces": plan.backspaceCount]
            )
            // #endregion
            completion(false)
            return
        }
        sendBackspacesAsync(count: plan.backspaceCount) { completion(true) }
    }

    public func sendLeftArrows(count: Int) {
        guard count > 0 else { return }
        guard CGPreflightPostEventAccess() else {
            DevTypeLog.inject.error(
                "[Inject] left-arrow refused — CGPreflightPostEventAccess false at post time count=\(count, privacy: .public)"
            )
            return
        }
        let source = CGEventSource(stateID: .privateState) ?? CGEventSource(stateID: .hidSystemState)
        var posted = 0
        for _ in 0..<count {
            if let aDown = CGEvent(keyboardEventSource: source, virtualKey: 123, keyDown: true),
               let aUp = CGEvent(keyboardEventSource: source, virtualKey: 123, keyDown: false) {
                aDown.post(tap: .cghidEventTap)
                aUp.post(tap: .cghidEventTap)
                posted += 1
            }
        }
        if posted == 0 {
            DevTypeLog.inject.error(
                "[Inject] left-arrow CGEvent create failed count=\(count, privacy: .public) — Post Events may be revoked"
            )
        } else if posted < count {
            DevTypeLog.inject.notice(
                "[Inject] left-arrow CGEvent partial posted=\(posted, privacy: .public)/\(count, privacy: .public)"
            )
        }
    }

    private func sendLeftArrowsAsync(count: Int, completion: @escaping () -> Void) {
        guard count > 0 else {
            completion()
            return
        }
        sendLeftArrows(count: count)
        DispatchQueue.main.asyncAfter(deadline: .now() + Double(count) * 0.0015 + 0.005, execute: completion)
    }
}
